percona/percona-server-mongodb-operator

- README.md
This is to fix failures when the service-DNS is pointed at a non-PRIMARY.
The mongo-level commands in the README.md can only be exec'd on a Primary host, which is always rs0-0 on startup.
> Update README to use Primary for mongo commands 

- pkg/stub/secrets.go
The corev1.Service must have the OwnerReference _(via .addOwnerRefToObject())_ set to be deleted with the service automatically with the other resources.
> Ensure SDK deletes service on delete

- README.md
- pkg/stub/psmdb.go
Before this change SRV records were not being made for the ServicePort.
After:
```
root@dns-client:/# dig _mongodb._tcp.my-cluster-name.psmdb.svc.cluster.local SRV
; <<>> DiG 9.9.5-9+deb8u16-Debian <<>> _mongodb._tcp.my-cluster-name.psmdb.svc.cluster.local SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 44675
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;_mongodb._tcp.my-cluster-name.psmdb.svc.cluster.local. IN SRV
;; ANSWER SECTION:
_mongodb._tcp.my-cluster-name.psmdb.svc.cluster.local. 5 IN SRV	0 33 27017 rs0-0.my-cluster-name.psmdb.svc.cluster.local.
_mongodb._tcp.my-cluster-name.psmdb.svc.cluster.local. 5 IN SRV	0 33 27017 …
```
> Add ServicePort 'Name' field so SRV records are made

- pkg/stub/exec.go
Add missing "\n" to fmt.Fprint() so we get proper stdout logging, instead of this ugly 1-line blob:
```
time="2018-11-14T14:43:00Z" level=info msg="/mongodb/k8s-mongodb-initiator stdout:"
/mongodb/k8s-mongodb-initiator (my-cluster-name-rs0-0): 2018-11-14 14:42:56.908 k8s-mongodb-initiator  initiator.go:219 INFO   Mongod replset initiator started  service=my-cluster-name/mongodb/k8s-mongodb-initiator (my-cluster-name-rs0-0): 2018-11-14 14:42:56.908 k8s-mongodb-initiator  initiator.go:223 INFO   Waiting to start initiation  sleep=0s/mongodb/k8s-mongodb-initiator (my-cluster-name-rs0-0): 2018-11-14 14:42:56.910 k8s-mongodb-initiator  initiator.go:154 INFO   Connected to MongoDB  auth=false host=localhost:27017 replset= ssl=false ssl_secure=false/mongodb/k8s-mongodb-initiator …
```
> Fix stdout/stderr from execCommandInContainer() logging

- deploy/rbac.yaml
- pkg/stub/exec_test.go
1. Add exact verbs to rbac.yaml
1. Remove unused 'endpoints', 'event', and 'configmaps' resources from core API group
1. Remove unused 'daemonset' resource from apps API group
1. Fix test failure in pkg/stub/exec_test.go due to last PR #31
> Update rbac.yaml to not use "*" verbs and resources

- pkg/apis/psmdb/v1alpha1/types.go
- pkg/stub/container.go
- pkg/stub/container_test.go
- pkg/stub/exec.go
- pkg/stub/handler.go
- pkg/stub/pod.go
- pkg/stub/pod_test.go
- pkg/stub/psmdb.go
- pkg/stub/psmdb_test.go
- pkg/stub/replset.go
1. Update Pods if the resources, mongodb config or version changes.
1. Move building of mongod container args to a new func.
MongoDB stays readable and writeable during Pod update on replsets >= 3 nodes. The rollout starts at node 2, then 1, then 0. When the Primary node is updated MongoDB has a normal failover to node 1 or 2.
Tested on:
- OpenShift 3.11
> CLOUD-20: Support updating Pods on resources, mongodb config+version change

- deploy/cr.yaml
- pkg/stub/handler.go
- pkg/stub/handler_test.go
- pkg/stub/replset.go
1. Fix panic on 'Deleted' SDK event when watchdog not started _(close() on a nil channel panic)_
1. Fix for starting watchdog after restart of operator on initialized replset.
1. Add test to test start/stop of watchdog.
>  Fix for watchdog failing to start after operator restart

- pkg/stub/container.go
error itself
```
$ mongod --wiredTigerIndexPrefixCompression
Error parsing command line: the required argument for option '--wiredTigerIndexPrefixCompression' is missing
try 'mongod --help' for more information
```
> fix wiredTigerIndexPrefixCompression argument error in 3.6.8

- Makefile
- pkg/stub/replset.go
- pkg/stub/replset_test.go
1. Throw an error if there is no 'resource.limits.storage' set.
1. Test that ^^^ error is thrown.
> CLOUD-42: Add error if no 'resources.limits.storage' is set (required for PVC)

- Gopkg.lock
- cmd/percona-server-mongodb-operator/main.go
- deploy/operator.yaml
- internal/sdk/client.go
While investigating CLOUD-32 (spec not updating) I needed more verbose logs from the operator. This PR adds the ability to enable verbose operator logging when it is running in Docker/Kubernetes or in development-mode.
Verbose logging is now enabled by setting "LOG_VERBOSE" to "true" in deploy/operator.yaml. Enabling this may help @heartwilltell get a good log of a bug he has noticed. --verbose on the command enables the same in development mode.
1. Added verbose feature.
1. Added debug logs for SDK calls (to help CLOUD-32).
> Add debug logging to operator

- deploy/rbac.yaml
- pkg/stub/handler_test.go
- pkg/stub/psmdb.go
- pkg/stub/replset.go
- pkg/stub/replset_test.go
This PR fixes a strange problem that caused scale/up down to break when changed by deploy/cr.yaml.
Previously the 'Get' to check the replica count was using the 'Create' appsv1.StatefulSet payload that contains a pointer to a v1alpha1.ReplsetSpec 'Size' field. This was causing the value we read to check the replica count to be overridden by the Get, causing the deploy/cr.yaml change to 'size' to be ignored.
The code has been reworked so the 'Get' does not override the value (added newStatefulSet func)
> CLOUD-32: Fix for scale up/down

- deploy/cr.yaml
- pkg/stub/container.go
- pkg/stub/psmdb_test.go
- pkg/stub/replset.go
- pkg/stub/util.go
- pkg/stub/util_test.go
1. Don't set cpu or memory 'requests' if there are no 'limits'.
1. Don't set wiredTigerCacheSizeGB if we don't know the memory 'limit' _(defaults cache size to 50% of the Kubelet system memory  - so no 'limits' is not-really recommended)_
1. Add unit tests.
> CLOUD-44: Resources limits should be optional

- Makefile
- deploy/operator.yaml
- version/version.go
This will work better if we plan to build a 'release-X.Y.Z' branch for every release. If you pull 'master' you will use the 'master' Dockertag+version after this PR which is easy to spot in issues.
1. Update master to use 'master' version
1. Update Makefile for release-X.Y.Z branches
> Update master to use 'master' version, update Makefile for release branches

- configure/operator.md
Fix Markdown typo + link.
Fix for this:
> Fix broken markdown syntax on mongod CR config section

- pkg/stub/handler.go
The 'replsets' section of the spec has an array of replica sets for forward-compatibility but many replica sets is not yet tested/supported.
This PR will log and skip replica sets when the slice-index is greater than 0.
> Do not allow multiple replica sets (yet)

- Makefile
- internal/util/container.go
- internal/util/resources.go
- internal/util/resources_test.go
- pkg/stub/container.go
- pkg/stub/psmdb_test.go
- pkg/stub/replset.go
- pkg/stub/util.go
This is fixes for the '0' CPU and/or Memory resource limits/requests when they are commented out.
1. Make func for parsing container resources. This was done in internal/util because the same resource logic needs to be shared with the upcoming backup code.
1. Improve unit tests to check for this issue.
> CLOUD-51 and CLOUD-52: Allow cpu+mem limits + requests to be commented-out

- .travis.yml
This is check for an issue @heartwilltell noticed when running operator-sdk on the API files for every build.
Travis-CI logs:
```
4.21s$ curl -sLo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.0.7/operator-sdk-v0.0.7-x86_64-linux-gnu
0.00s$ chmod +x operator-sdk
7.32s$ ./operator-sdk generate k8s
Run code-generation for custom resources
Generating deepcopy funcs
```
> Make Travis-CI check operator-sdk can generate deep copy code

- pkg/stub/backup/agent.go
1. Fix typo in 'API' vs 'RPC' port number for agent coordinator address. The agent needs to connect to the RPC port, not API port
1. Fix for rename of env var 'PBM_AGENT_MONGODB_USER' -> 'PBM_AGENT_MONGODB_USERNAME'. This was renamed in the backup tool.
1. Remove 'PBM_AGENT_MONGODB_HOST' == '127.0.0.1' env var now that the backup agent defaults to '127.0.0.1'
> Fix backup agent port-number typo from PR #93, update for cli var renames

- pkg/stub/handler.go
- pkg/stub/handler_test.go
1. Unregister watchdog prometheus metrics on CR delete to fix panic.
NOTE: this logic will change later when many CRs are fixed/supported.
> CLOUD-73: Unregister watchdog metrics

- internal/mongod/container.go
This increases the timeouts of the mongod liveness check. This may resolve intermittent issues in CLOUD-87.
1. Increase initial delay to from 45 -> 60 seconds (to delay the liveness probe starting)
1. Increase the timeout from 2 -> 5 seconds in case the host is very slow on startup.
1. Increase period of check from 5 -> 10 seconds.
1. Failure threshold from 5 - 12.
The result:
1. The liveness check doesn't start for 1 minute.
1. It needs to fail for 2 minutes (10 x 12 seconds) before the pod is killed. Total of 3 minutes with the 1 minute initial delay.
> CLOUD-87: Increase mongod liveness timeouts to realistic thresholds

- backup-restorer.sh
- deploy/backup-restore.yaml
1. Check if gzip was enabled properly by doing 'aws s3 ls'.
1. Allow environment variables to set backup name, bucket name and mongodb dsn.
1. Add Kubernetes Job to call the restorer script. This job uses the Kubernetes secret for 
@fiowro, the restore steps will be:
1. Edit deploy/backup-restorer.yaml to have correct:
1. The name of the Kubernetes secret containing the AWS S3 credentials (should be same as deploy/cr.yaml backup section).
1. S3 bucket name (should be same as deploy/cr.yaml backup section)
1. Backup name (this name is unique for each backup - see S3 browser to get the name of available backups)
1. The mongodb+srv:// connect string with the backup-user username+password (from deploy/mongodb-users.yaml secret file).
1. Run the restore job:
```
oc create -f …
```
> Add restore Kubernetes Job, fix restorer script

- backup-restorer.sh
In PBM 0.2.1 it is normal that there is no oplog to restore if there were no changes to the oplog during backup.
In PBM 0.2.2+ restores will work through the agent.
> Exit 0 if no oplog to restore

- Gopkg.lock
- Gopkg.toml
- internal/testutil/errors.go
- pkg/stub/backup/controller_test.go
- pkg/stub/backup/coordinator_test.go
- pkg/stub/backup/status_test.go
- vendor/github.com/stretchr/testify/LICENSE
- vendor/github.com/stretchr/testify/assert/assertions.go
- vendor/github.com/stretchr/testify/mock/mock.go
- version/version.go
1. Move 'UnexpectedError' and 'AlreadyExistsError' from pkg/stub/backup -> internal/testutil so it can be used in pkg/stub unit tests in PR https://github.com/Percona-Lab/percona-server-mongodb-operator/pull/138.
1. Update testify library.
> Move mock error vars from pkg/stub/backup to internal/testutil, update testify

- pkg/stub/arbiter.go
- pkg/stub/psmdb.go
- pkg/stub/unsafeconf.go
- pkg/stub/unsafeconf_test.go
1. There is should be a way to set the 0 replset size in unsafe mode.
2. Now the operator switches off the arbiter instead of adding one more node when the nodes+arbiter size is even. This behavior is better aligned with the requirements in https://jira.percona.com/browse/CLOUD-117.
3. Improved the logic of the arbiter size updating.
4. Cut off redundant checks.
> Fix arbiter logic

- pkg/stub/handler_test.go
Test case wasn't expect a Delete method in handler: https://github.com/Percona-Lab/percona-server-mongodb-operator/blob/f2ffc95b03fb81765cfee050f8cf2646e7641997/pkg/stub/replset.go#L226
> Introduction the Delete method for arbiter in the handler broke unit tests

- Gopkg.lock
- Gopkg.toml
- vendor/github.com/percona/mongodb-orchestration-tools/Makefile
- vendor/github.com/percona/mongodb-orchestration-tools/cmd/dcos-mongodb-controller/main.go
- vendor/github.com/percona/mongodb-orchestration-tools/cmd/mongodb-executor/main.go
- vendor/github.com/percona/mongodb-orchestration-tools/internal/dcos/env.go
- vendor/github.com/percona/mongodb-orchestration-tools/internal/dcos/util.go
- vendor/github.com/percona/mongodb-orchestration-tools/pkg/pod/dcos/task.go
- vendor/github.com/percona/mongodb-orchestration-tools/watchdog/watcher/watcher.go
Use the 0.4.2 release (latest) of percona/mongodb-orchestration-tools (instead of a git-revision):
https://github.com/percona/mongodb-orchestration-tools/releases/tag/0.4.2
This includes a fix that should allow replset watchers to retry if they have no members.
> Use the 0.4.2 tag of mongodb-orchestration-tools

- Jenkinsfile
* GKE has limit on lenght of cluster name, we need use shorter
names for our clusters
> JEN-1118 remove branch name from name of cluster

- pkg/controller/perconaservermongodb/ssl.go
some libraries perform a reverse lookup of the dns entry and then report an untrusted certificate because the certificate does not contain the fqdn. this pr adds more sans to cover those cases.
> K8SPSMDB-197 - added more sans to certificate

- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml
- e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml
security-context and scheduled-backup tests compare cronjob definitions and since in https://github.com/percona/percona-server-mongodb-operator/pull/353 it was changed this is failing now.
I have based my branch on top of the branch from PR#353 to see if the tests will pass in jenkins.
Tests were failing because the diff here was not empty:
```
+ diff -u /home/plavi/percona-server-mongodb-operator/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml /tmp/tmp.ur6lFj6ABU/cronjob.batch_sec-context-backup-each-hour.yml
--- /home/plavi/percona-server-mongodb-operator/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml 2020-05-11 13:57:31.362665000 +0000
+++ /tmp/tmp.ur6lFj6ABU/cronjob.batch_sec-context-backup-each-hour.yml  2020-05-11 …
```
> K8SPSMDB-194 - Fix security-context and scheduled-backup tests from PR#353

- .gitattributes
[![CLOUD-543](https://badgen.net/badge/JIRA/CLOUD-543/green)](https://jira.percona.com/browse/CLOUD-543)
according to https://help.github.com/en/github/administering-a-repository/customizing-how-changed-files-appear-on-github
> CLOUD-543 hide vendor changes in PRs

- e2e-tests/functions
This is needed so that the `compare_mongo_user` function can work with images like `percona/percona-server-mongodb:4.2.8-8` instead of just with `percona/percona-server-mongodb-operator:1.4.0-mongod4.2`.
`init_deploy` is the only test currently using this and it is passing for me locally.
We had the same fix for PXC.
> Fix compare_mongo_user for generic PSMDB docker images

- e2e-tests/one-pod/run
Tried to play with waiting for PBM locks, but it looks like a PBM bug where no locks are listed in admin.pbmLock collection, but the agent still reports that previous operation is in progress and refuses to do restore.
So for now went with the sleep and will investigate and report PBM issue if needed.
There's a possibility that this affects only 1 node replica set.
> Fix one-pod test - PBM doesn't release a lock soon enough after backup

- e2e-tests/upgrade/run
This allows for the test to be run regardless if the new image is from `percona-server-mongodb-operator` or from `percona-server-mongodb` docker repository.
> Fix upgrade test to allow using images from percona-server-mongodb repo

- source/System-Requirements.rst
[![K8SPSMDB-234](https://badgen.net/badge/JIRA/K8SPSMDB-234/green)](https://jira.percona.com/browse/K8SPSMDB-234)
Since 1.14 is no longer available in stable channel
versions have to be updated
> K8SPSMDB-234 GKE version upgrade

- e2e-tests/functions
In PBM 1.3.x log messages have changed so our function to check if agent is listening is not working any more.
Here's how the log looks now:
```
2020/09/04 06:36:46 starting pitr routine
2020/09/04 06:36:46 listening for the commands
2020/09/04 06:36:46 node: rs0/some-name-rs0-0.some-name-rs0.demand-backup-31889.svc.cluster.local:27017
2020/09/04 06:37:01 [ERROR] pitr: check if on: get config: get: mongo: no documents in result
2020/09/04 06:37:16 [ERROR] pitr: check if on: get config: get: mongo: no documents in result
2020/09/04 06:37:31 [ERROR] pitr: check if on: get config: get: mongo: no documents in result
2020/09/04 06:37:46 [ERROR] pitr: check if on: get config: get: mongo: no documents in result
```
date and time was added and some additional lines
> Fix wait_backup_agent func in e2e-tests for PBM 1.3.x

- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/psmdb/mongo/mongo.go
This PR fixes issue when connection with MongoDB was established but after that Ping command was unsuccessful.
It adds logic which controls that if any error occurred in Dial function connection should be closed.
> Fix connections leak

- pkg/apis/psmdb/v1/psmdb_types.go
~Also, convert all state constants from untyped strings to AppState.
Staticcheck linter (a part of gopls and golangci-lint) can catch this
bug, and it is present in many other places across operators code
bases.~
That was already done in `master`.
> Remove unused pending state

- e2e-tests/functions
PBM 1.3.2 has changed log messages so `wait_backup_agent` doesn't check correctly if agent is running and listening.
```
GoVersion: go1.14.12
2020-11-19T14:22:13.000+0000 I node: rs0/some-name-rs0-0.some-name-rs0.demand-backup-sharded-29033.svc.cluster.local:27017
2020-11-19T14:22:13.000+0000 I listening for the commands
2020-11-19T14:22:13.000+0000 I starting PITR routine
```
This fixes the backup tests with the image `perconalab/percona-server-mongodb-operator:master-backup` since they are now waiting forever for backup agent.
> Fix wait_backup_agent function for parsing new PBM logs

- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/operator.yaml
Check which PSMDB version should be default in cr.yaml 4.2 or 4.4?
Also notice this is merge to release-1.6.0 branch, not sure if it should go into release branch and only after release to master.
> Update for 1.6.0 release

- e2e-tests/version-service/run
Fix version-service test to not use psmdb_spinup because it disables SmartUpdate apply option
Needed after this change: https://github.com/percona/percona-server-mongodb-operator/pull/498
This copies commands from functions `psmdb_spinup` to the test and fixes parameters, removes the sed to disable `apply` option since it is needed for this test.
I have executed the test locally and it passed.
> Fix version-service test to not use psmdb_spinup

- e2e-tests/functions
Seems this was a typo or some leftover from before (if it was renamed).
> Rename psmdb-recovery to psmdb-restore in e2e-tests functions

- e2e-tests/demand-backup-sharded/run
- e2e-tests/functions
This fixes `monitoring-2-0` and `demand-backup-sharded` tests which were failing on GKE 1.15 with something like:
Here's the test run with GKE 1.15: https://cloud.cd.percona.com/job/psmdb-operator-gke-version/248/
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml /tmp/tmp.FeZx9y4Xr5/deployment_monitoring-mongos.yml
--- /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml	2020-12-13 16:31:40.000000000 +0000
+++ /tmp/tmp.FeZx9y4Xr5/deployment_monitoring-mongos.yml	2020-12-13 16:48:19.851401485 +0000
@@ -1,4 +1,4 @@
-apiVersion: apps/v1
+apiVersion: extensions/v1beta1
kind: Deployment
metadata:
annotations:
```
> Fix compare mongos deployment on GKE 1.15

- e2e-tests/functions
- pkg/controller/perconaservermongodb/ssl.go
[![K8SPSMDB-340](https://badgen.net/badge/JIRA/K8SPSMDB-340/green)](https://jira.percona.com/browse/K8SPSMDB-340)
Sometimes certmanager do not issue certificates fast enough, and we have test fail because of that.
This pr fixes this(service per pod) test
> K8SPSMDB-340: add sleep to certmanager install

- e2e-tests/version-service/conf/crd.yaml
> K8PSMDB-341 CRD version settings breaks test execution on 3.11

- deploy/crd.yaml
- e2e-tests/functions
- e2e-tests/upgrade-consistency/compare/service_some-name-rs0-170.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-170-oc.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-170.yml
- e2e-tests/upgrade-consistency/run
- e2e-tests/upgrade-sharded/run
- e2e-tests/version-service/conf/crd.yaml
- version/version.go
Two backup tests are failing because of: https://github.com/percona/percona-server-mongodb-operator/pull/515
`upgrade-consistency` is fixed in the second commit
> K8SPSMDB-341 - Increment versions after 1.6.0 release

- e2e-tests/functions
Latest logs in main branch look like:
```
2020-12-18T16:53:20.000+0000 I node: rs0/some-name-rs0-0.some-name-rs0.demand-backup-18921.svc.cluster.local:27017
2020-12-18T16:53:20.000+0000 I listening for the commands
2020-12-18T16:53:20.000+0000 I starting PITR routine
2020-12-18T16:53:25.000+0000 E [agentCheckup] check storage connecion: unable to get storage: get config: get: mongo: no documents in result
```
So wait_backup_agent just waits forever because it's not filtering the last message - although we need to check if this is really something we want to filter.
> Fix filtering PBM logs in wait_backup_agent e2e function

- source/users.rst
[![K8SPSMDB-354](https://badgen.net/badge/JIRA/K8SPSMDB-354/green)](https://jira.percona.com/browse/K8SPSMDB-354) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPSMDB-354 fix quotes in the password change command

- e2e-tests/data-sharded/conf/some-name.yml
- e2e-tests/functions
`data-sharded` already had `antiAffinityTopologyKey: none` defined for some pods, but not for all, so this sets them for all so it can run on Minikube.
`init-deploy` fails on Minikube with:
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-minikube/source/e2e-tests/init-deploy/compare/service_some-name-rs0.yml /tmp/tmp.S3v6LoJCuC/service_some-name-rs0.yml
--- /mnt/jenkins/workspace/psmdb-operator-minikube/source/e2e-tests/init-deploy/compare/service_some-name-rs0.yml	2021-02-10 16:32:17.000000000 +0000
+++ /tmp/tmp.S3v6LoJCuC/service_some-name-rs0.yml	2021-02-10 16:38:45.253306738 +0000
@@ -7,6 +7,8 @@
kind: PerconaServerMongoDB
name: some-name
spec:
+  clusterIPs:
+    - None
ports:
- name: mongodb
port: 27017
```
> Fix init-deploy and data-sharded e2e-tests for Minikube

- e2e-tests/data-sharded/run
`data-sharded` test was failing on PSMDB 4.0 and 3.6 and it seems because of small chunk size and some performance issues if bulk data insertion is happening together with data migrations on older versions.
So I have changed a little bit how it works:
1. first insert data, then enable sharding on collection (this way migrations and data insert are not happening at the same time)
2. put `_id` field as a shard field instead of `zipcode` since this is already indexed so the second index is not created (it's not important for us)
3. increased chunk size from 1MB to half of the default value to 32Mb (default is 64Mb) - this might not even be important with the changed operation order, but it shouldn't hurt.
> Make data-sharded test run on older MongoDB versions

- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml
monitoring-2-0 test was failing with this diff:
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml /tmp/tmp.y48SGaoAZY/deployment_monitoring-mongos.yml
--- /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml	2021-02-24 14:20:36.000000000 +0000
+++ /tmp/tmp.y48SGaoAZY/deployment_monitoring-mongos.yml	2021-02-24 14:32:19.047396776 +0000
@@ -52,9 +52,9 @@
- --bind_ip_all
- --port=27017
- --sslAllowInvalidCertificates
-            - --relaxPermChecks
- --configdb
- cfg/monitoring-cfg-0.monitoring-cfg.NAME_SPACE.svc.cluster.local:27017,monitoring-cfg-1.monitoring-cfg.NAME_SPACE.svc.cluster.local:27017,monitoring-cfg-2.monitoring-cfg.NAME_SP …
```
> Fix diff in monitoring-2-0 e2e test for mongos deployment

- e2e-tests/arbiter/run
[![K8SPSMDB-408](https://badgen.net/badge/JIRA/K8SPSMDB-408/green)](https://jira.percona.com/browse/K8SPSMDB-408) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Due to the issue with livenessprobe failure we need
to check whether arbiter pod is restated or not.
> K8SPSMDB-408 Arbiter liveness check

- .github/workflows/reviewdog.yml
[![CLOUD-616](https://badgen.net/badge/JIRA/CLOUD-616/green)](https://jira.percona.com/browse/CLOUD-616) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> CLOUD-616 fix golangci-lint timeout issue

- pkg/controller/perconaservermongodb/backup.go
[![K8SPSMDB-386](https://badgen.net/badge/JIRA/K8SPSMDB-386/green)](https://jira.percona.com/browse/K8SPSMDB-386) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-386
Cluster with enabled PITR and no full backup has error status and requires a backup. But it's not possible to create a backup in such a cluster.
Also, as described in spec, the operator must try to enable PITR once there is a backup.
> K8SPSMDB-386 fix: cluster status for enabled PITR without full backup

- pkg/controller/perconaservermongodb/finalizers.go
- pkg/controller/perconaservermongodb/getters.go
[![K8SPSMDB-430](https://badgen.net/badge/JIRA/K8SPSMDB-430/green)](https://jira.percona.com/browse/K8SPSMDB-430) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Fixing https://jira.percona.com/browse/K8SPSMDB-430
Double checking the UID of the controllerRef of the statefulset before deleting it in `deleteAllStatefulsets`.
It seems that PVC is not tagged with the controllerRef. We can later issue another patch to label PVC with UID of PerconaServerMongoDB and perform the check before deleting PVC.
> K8SPSMDB-430: checking UID before deleting sts

- pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-434](https://badgen.net/badge/JIRA/K8SPSMDB-434/green)](https://jira.percona.com/browse/K8SPSMDB-434) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Fixing https://jira.percona.com/browse/K8SPSMDB-434
Checking nil pointer before dereferencing `cr.Status.Mongos`
> K8SPSMDB-434 fixed by checking nil pointer before dereference

- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-4-oc.yml
- e2e-tests/demand-backup-sharded/compare/statefulset_some-name-cfg-4-oc.yml
- e2e-tests/limits/run
- e2e-tests/rs-shard-migration/run
- e2e-tests/service-per-pod/run
Fixes rs-shard-migration and service-per-pod on openshift 4 and some sporadic failures in other environments.
> K8SPSMDB-442 - fix rs-shard-migration and service-per-pod tests

- e2e-tests/pitr/compare/find-3rd.json
- e2e-tests/pitr/run
Fixes the same issue @dAdAbird mentioned in #637 but for PITR test in a non-sharded cluster
> K8SPSMDB-387: improve e2e pitr test (restore to date)

- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
[![K8SPSMDB-365](https://badgen.net/badge/JIRA/K8SPSMDB-365/green)](https://jira.percona.com/browse/K8SPSMDB-365) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
> K8SPSMDB-365: Allow backups even if just a single node is available

- e2e-tests/functions
Several tests are failing on kubernetes 1.21 like this:
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/service_monitoring-rs0.yml /tmp/tmp.3ptFKa1i6I/service_monitoring-rs0.yml
--- /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/monitoring-2-0/compare/service_monitoring-rs0.yml	2021-06-14 08:00:27.000000000 +0000
+++ …
```
> K8SPSMDB-488 - Fix diff in some e2e-tests on kubernetes 1.21

- deploy/cr.yaml
This removes the operationProfiling.mode option from custom config example for `mongos` since this is something that can only be configured for `mongod`, so the error was visible:
```
+ exec mongos --bind_ip_all --port=27017 --configdb cfg/my-cluster-name-cfg-0.my-cluster-name-cfg.psmdb-test.svc.cluster.local:27017,my-cluster-name-cfg-1.my-cluster-name-cfg.psmdb-test.svc.cluster.local:27017,my-cluster-name-cfg-2.my-cluster-name- …
```
> K8SPSMDB-488 - Remove operationProfiling option from mongos (not supported)

- e2e-tests/demand-backup-sharded/run
- e2e-tests/functions
- e2e-tests/init-deploy/run
- e2e-tests/pitr-sharded/run
I'm seeing following issue on EKS 1.20:
`Warning  FailedCreatePodSandBox  60s (x71 over 16m)  kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = RuntimeHandler "runc" not supported`
so this will continue to use `docker` instead of `runc` on EKS.
> K8SPSMDB-488 - Fix runtimeclass handler for EKS in e2e-tests

- e2e-tests/version-service/conf/version-service-exact-rs0.yml
- e2e-tests/version-service/conf/version-service-latest-rs0.yml
- e2e-tests/version-service/conf/version-service-major-rs0.yml
- e2e-tests/version-service/conf/version-service-recommended-rs0.yml
- e2e-tests/version-service/conf/version-service-unreachable-rs0.yml
Jenkins nodes don't have too much space in `/tmp` and seems minikube is storing stuff inside `/tmp/hostpath-provisioner`
so sometimes tests start failing with disk space issue.
We already added cleanup before every test, but since this test is running several tests inside one test the cleanup doesn't start so this is adding finalizer for pvc's.
> K8SPSMDB-488 - Fix version-service test for minikube

- e2e-tests/functions
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio-oc.yml
- e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml
- e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml
`security-context` and `scheduled-backup` tests are failing on 1.21 with:
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml /tmp/tmp.1OtgrJU1dl/cronjob.batch_sec-context-backup-each-hour.yml
--- /mnt/jenkins/workspace/psmdb-operator-gke-version/source/e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour …
```
> K8SPSMDB-488 - Fix security-context and scheduled-backup tests

- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/status.go
- pkg/psmdb/service.go
[![K8SPSMDB-504](https://badgen.net/badge/JIRA/K8SPSMDB-504/green)](https://jira.percona.com/browse/K8SPSMDB-504) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This commit fixes a sporadic bug. It occurs as follows:
1. You apply the CR with replset is exposed with LoadBalancer type and
sharding disabled.
2. Operator creates the statefulset and first pod is created.
3. A service with type LoadBalancer and same name as pod is created.
Then, operator blocks the reconciliation until an external IP is
assigned to LoadBalancer or reaches timeout.
4. Second pod is created while waiting the …
> K8SPSMDB-504: Fix cluster failure if replset exposed with LoadBalancer

- pkg/psmdb/mongo/models.go
- pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-512](https://badgen.net/badge/JIRA/K8SPSMDB-512/green)](https://jira.percona.com/browse/K8SPSMDB-512) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The `GetLastErrorModes` setting is defined as the wrong type. Configuring `getLastErrorModes` in the replicaset causes the Operator to fail to reconcile with the error:
```
get mongo config: failed to decoge to replSetGetConfig: cannot decode 32-bit integer into a string type
```
Currently, the Operator defines GetLastErrorModes as a `map[string]ReplsetTags`, where `ReplsetTags` is a `map[string]string`. In mongoDB, the …
> K8SPSMDB-512: Add CustomWriteConcern type

- pkg/controller/perconaservermongodb/smart.go
- pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-506](https://badgen.net/badge/JIRA/K8SPSMDB-506/green)](https://jira.percona.com/browse/K8SPSMDB-506) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We try to decide which pod is primary by running `rs.status()` and
getting `name` field of PRIMARY. If replset is not exposed `name` is
local FQDN of service and since service name and pod name is the same, we
can select the right pod. But if replset is exposed, node names are
external hostnames and selecting the primary pod is not straightforward.
We need to get the external address of each pod in the replset and
compare with …
> K8SPSMDB-506: Fix restarting primary pod on smart update

- deploy/cr.yaml
[![K8SPSMDB-554](https://badgen.net/badge/JIRA/K8SPSMDB-554/green)](https://jira.percona.com/browse/K8SPSMDB-554) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
It was mentioned in the spec that default should be ClusterIP everywhere as default.
> K8SPSMDB-554 - Change default exposeType from LoadBalancer to ClusterIP

- pkg/controller/perconaservermongodbbackup/backup.go
[![K8SPSMDB-553](https://badgen.net/badge/JIRA/K8SPSMDB-553/green)](https://jira.percona.com/browse/K8SPSMDB-553) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-553
Actually, in the right conditions backup will be updated as "error" if s3 credentials are wrong:
```
% kubectl get perconaservermongodbbackup.psmdb.percona.com/backup2 -o yaml | yq r - status
destination: "2021-09-09T04:57:01Z"
error: "mongodump: write data: upload to S3: InvalidAccessKeyId: The Access Key Id you provided does not exist in our records.\n\tstatus code: 403, request …
```
> K8SPSMDB-553: Don't allow running status in stuck backups

- build/Dockerfile
[![K8SPXC-761](https://badgen.net/badge/JIRA/K8SPXC-761/green)](https://jira.percona.com/browse/K8SPXC-761) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
1. Use numeric id instead of username in USER instruction
2. Use id 2(daemon), reasons:
- nobody user id changed in rhel/centos/ubi 8 from 2 to 65534
- unify with percona-postgresql-operator
> K8SPXC-761 use numeric id in USER instruction

- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-4-oc.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-oc.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-secret.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos.yml
- e2e-tests/functions
- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-4-oc.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-oc.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos.yml
- pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-527](https://badgen.net/badge/JIRA/K8SPSMDB-527/green)](https://jira.percona.com/browse/K8SPSMDB-527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
[K8SPSMDB-527](https://jira.percona.com/browse/K8SPSMDB-527)
timeout should be less or equal than the period otherwise possible to get errors in some configurations
```
Normal   LoadBalancerNegWithoutHealthCheck  10m   neg-readiness-reflector  Pod is in NEG "Key{\"k8s1-2615dab0-run-main-4664-my-cluster-name-mongo-2701-24107fd7\", zone: \"europe-west1-c\"}". NEG is not attached to any BackendService with health checking. Marking …
```
> K8SPSMDB-527 timeout should be less or equal than period

- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/psmdb/mongos.go
[![K8SPSMDB-605](https://badgen.net/badge/JIRA/K8SPSMDB-605/green)](https://jira.percona.com/browse/K8SPSMDB-605) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
- create sidecars `PersistentVolumeClaim`s for mongos deployment
- provide volumes for mongos sidecars
- link sidecar PVCs to sidecar pods
> [K8SPSMDB-605] custom sidecar volumes not supported in mongos pods

- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-4-oc.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-oc.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-secret.yml
- e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos.yml
- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-4-oc.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-oc.yml
- e2e-tests/pitr-sharded/compare/deployment_some-name-mongos.yml
- pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-604](https://badgen.net/badge/JIRA/K8SPSMDB-604/green)](https://jira.percona.com/browse/K8SPSMDB-604) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-604
> K8SPSMDB-604: Add `startupDelaySeconds` option for mongos liveness probe

- Jenkinsfile
- go.mod
- go.sum
- vendor/modules.txt
[![CVE-2020](https://badgen.net/badge/JIRA/CVE-2020/green)](https://jira.percona.com/browse/CVE-2020) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://github.com/dgrijalva/jwt-go/issues/482#issuecomment-950205708
> fix for CVE-2020-26160

- e2e-tests/functions
arbiter and users tests were failing in some environments with following diffs:
arbiter
```
+ diff /Users/plavi/Development/percona/kubernetes-operators/production/percona-server-mongodb-operator/e2e-tests/arbiter/compare/find.json /var/folders/fw/lxhtthdn7d9610w5p3wb33340000gn/T/tmp.zZiizUaJ/find
0a1
> 2021-12-09T16:15:22.023+0000 F NETWORK  [ReplicaSetMonitor-TaskExecutor-0] ReplicaSetMonitor rs0 recieved error while …
```
> K8SPSMDB-571 - Fix failures in some tests

- e2e-tests/default-cr/compare/statefulset_minimal-cluster-cfg-oc.yml
- e2e-tests/default-cr/compare/statefulset_minimal-cluster-rs0-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0.yml
- e2e-tests/default-cr/run
- e2e-tests/init-deploy/compare/clusterAdmin-50.json
- fix default-cr test for openshift
- remove antiAffinity in default-cr to allow the test to run on more environments
- fix init-deploy for PSMDB 5.0
> K8SPSMDB - Fixes for tests for 1.11.0 release

- deploy/cr.yaml
- pkg/apis/psmdb/v1/psmdb_defaults.go
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/psmdb/container.go
- pkg/psmdb/statefulset.go
[![K8SPSMDB-596](https://badgen.net/badge/JIRA/K8SPSMDB-596/green)](https://jira.percona.com/browse/K8SPSMDB-596) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-596
Create variable `spec.secrets.encryptionKey` and still support backward-compatibility for `spec.mongod.security.encryptionKeySecret`
> K8SPSMDB-596: Move encryptionKeySecret to new variable

- e2e-tests/data-sharded/run
`config.chunks` collection in 5.0 doesn't use `ns`, but started using `UUID`'s for collections.
> K8SPSMDB-571 - Fix data-sharded test for MongoDB 5.0

- pkg/controller/perconaservermongodb/ssl.go
[![K8SPSMDB-574](https://badgen.net/badge/JIRA/K8SPSMDB-574/green)](https://jira.percona.com/browse/K8SPSMDB-574) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
rollback https://github.com/percona/percona-server-mongodb-operator/pull/779
reason: security concern, certificates should be rotated every 3 months, we are going to add a field that allows configuring certificate age.
https://jira.percona.com/browse/K8SPSMDB-574
> K8SPSMDB-574 Rollback Set certificate duration for external certificates to 100 years

- pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-560](https://badgen.net/badge/JIRA/K8SPSMDB-560/green)](https://jira.percona.com/browse/K8SPSMDB-560) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-560
Fix `(m *ConfigMembers) FixTags` method
> K8SPSMDB-560: `serviceName` tag not set to all members in rs

- e2e-tests/functions
Diff:
```
+ diff -u /mnt/jenkins/workspace/psmdb-operator-minikube/source/e2e-tests/scaling/compare/pvc_mongod-data-some-name-rs0-3.yml /tmp/tmp.HhcdGDSkU8/pvc_mongod-data-some-name-rs0-3.yml
--- /mnt/jenkins/workspace/psmdb-operator-minikube/source/e2e-tests/scaling/compare/pvc_mongod-data-some-name-rs0-3.yml	2022-01-24 09:12:20.000000000 +0000
+++ /tmp/tmp.HhcdGDSkU8/pvc_mongod-data-some-name-rs0-3.yml	2022-01-24 …
```
> K8SPSMDB-631 - Fix diff in scaling test for Minikube 1.23

- pkg/controller/perconaservermongodb/smart.go
[![K8SPSMDB-632](https://badgen.net/badge/JIRA/K8SPSMDB-632/green)](https://jira.percona.com/browse/K8SPSMDB-632) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The operator was starting smart update just after the CR applied. When
statefulset is created, its update revision is empty and it's updated
after some time.
> K8SPSMDB-632: Fix smart update on initial deployment

- Jenkinsfile
A few hours ago v1.1.0 released and now it breaks our builds.
See: https://github.com/google/go-licenses/issues/125
> Fix version of go-licenses

- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/psmdb/statefulset.go
[![K8SPSMDB-669](https://badgen.net/badge/JIRA/K8SPSMDB-669/green)](https://jira.percona.com/browse/K8SPSMDB-669) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-669
Fixed `isEncyptionEnabled` func. On the 1.12.0 version, we were ignoring the `mongod.security.enableEncryption` field and set it to true by default if another value was not specified in the replset's `configuration` section. Now we use mongod's value if it's not specified in the configuration section
> K8SPSMDB-669 fix: encryption turns on while updating to 1.12.0

- deploy/bundle.yaml
- deploy/crd.yaml
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/ssl.go
[![K8SPSMDB-681](https://badgen.net/badge/JIRA/K8SPSMDB-681/green)](https://jira.percona.com/browse/K8SPSMDB-681) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
After upgrading the operator from 1.11.0, SSL secrets are updated
immediately to include MCS SANs. This were causing SSL errors during
smart update since the operator immediately starts using the new
certificate but the mongod containers continue using the old ones. We
shouldn't update SSL certs when their secrets already exist.
> K8SPSMDB-681: Fix SSL errors after upgrading from 1.11.0

- deploy/cr.yaml
So `cacheSizeRatio` and `inMemorySizeRatio` need to be used from `replsets.storage` section since they are not mongodb options but operator options.
> K8SPSMDB-631 - Remove cacheSizeRatio/inMemorySizeRatio from custom config

- pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-691](https://badgen.net/badge/JIRA/K8SPSMDB-691/green)](https://jira.percona.com/browse/K8SPSMDB-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Patch updates the object with values returned from API server. This behavior removes our in-memory values.
> K8SPSMDB-691: Fix empty SSL secret name after patching CR

- pkg/psmdb/pdb.go
[![K8SPSMDB-760](https://badgen.net/badge/JIRA/K8SPSMDB-760/green)](https://jira.percona.com/browse/K8SPSMDB-760) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Since version 1.21.0 of kubernetes, PodDisruptionBudget is at policy/v1, and since v1.25.0, policy/v1beta is not available anymore. This change will use v1 instead of v1beta for the PDB.
> K8SPSMDB-760 pdb is policy/v1 since v1.21.0

- healthcheck/tools/db/config.go
- healthcheck/tools/db/db.go
[![K8SPSMDB-763](https://badgen.net/badge/JIRA/K8SPSMDB-763/green)](https://jira.percona.com/browse/K8SPSMDB-763) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Turns out TLS configuration in mongodb-healthcheck is broken since
v1.12.0. kingpin fills config variables after `app.Parse` is called,
which makes effing sense.
> K8SPSMDB-763: Fix TLS config in healthcheck

- cmd/manager/main.go
- pkg/k8s/utils.go
[![CLOUD-739](https://badgen.net/badge/JIRA/CLOUD-739/green)](https://jira.percona.com/browse/CLOUD-739) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
The bug in K8SPXC-1123 revealed the flaw in our cw operation mode - basically we are ignoring the namespace where operator resides and it could lead to some issues. Fixing that.
> CLOUD-739 Watch the operators' namespace in any case

- e2e-tests/demand-backup-sharded/run
- pkg/controller/perconaservermongodbbackup/backup.go
[![K8SPSMDB-836](https://badgen.net/badge/JIRA/K8SPSMDB-836/green)](https://jira.percona.com/browse/K8SPSMDB-836) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Backups in starting status get immediatly tagged as error.
**Cause:**
`pbmStartingDeadline` variable is not set properly to 120 seconds, but uses nanoseconds instead.
**Solution:**
Convert variable to seconds.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-836 - Fix pbmStartingDeadline for backups in starting status

- build/Dockerfile
[![K8SPSMDB-798](https://badgen.net/badge/JIRA/K8SPSMDB-798/green)](https://jira.percona.com/browse/K8SPSMDB-798) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Wrong name for a stage in Dockerfile
**Solution:**
rename stage
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-798 rename stage in Dockerfile

- e2e-tests/conf/container-rc.yaml
- e2e-tests/init-deploy/conf/another-name-rs0.yml
- e2e-tests/limits/conf/no-limits-rs0.yml
- e2e-tests/limits/conf/no-requests-no-limits-rs0.yml
- e2e-tests/limits/conf/no-requests-rs0.yml
- e2e-tests/limits/conf/no-storage-rs0.yml
[![K8SPSMDB-844](https://badgen.net/badge/JIRA/K8SPSMDB-844/green)](https://jira.percona.com/browse/K8SPSMDB-844) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The node.k8s.io/v1beta1 RuntimeClass is deprecated in v1.22
**Solution:**
Update API for RuntimeClass to node.k8s.io/v1, starting from the next release operator will not support k8s 1.21
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-844 update API for RuntimeClass

- deploy/cr.yaml
[![K8SPSMDB-793](https://badgen.net/badge/JIRA/K8SPSMDB-793/green)](https://jira.percona.com/browse/K8SPSMDB-793) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Due to https://github.com/percona/percona-server-mongodb-operator/blob/804f6418792732b189b2b5bde1d03560da8cac7e/pkg/apis/psmdb/v1/psmdb_types.go#L549 we need to keep annotations only under persistentVolumeClaim
---
**Problem:**
*Some annotations/labels example is misleading*
**Cause:**
*Human factor possible*
**Solution:**
*Remove irrelevant*
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-793 Removing irrelavent example

- pkg/controller/perconaservermongodb/backup.go
[![K8SPSMDB-820](https://badgen.net/badge/JIRA/K8SPSMDB-820/green)](https://jira.percona.com/browse/K8SPSMDB-820) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
With cluster-wide adoption we may need to extend some of our loggin messages
---
**Problem:**
*Namespace for backup job to be removed is not displayed. Operator log message is not informative in cluster-wide mode.*
`2023-02-01T14:38:53.680ZINFO    controller_psmdb        deleting outdated backup job    {"name": "weekly"}`
**Cause:**
*Just an improvement.*
**Solution:**
*Extending logmessage like in …
> K8SPSMDB-820 Display namespace for removed backup job

- healthcheck/tools/db/config.go
- healthcheck/tools/db/ssl.go
- healthcheck/tools/util.go
- pkg/controller/perconaservermongodb/backup.go
- pkg/controller/perconaservermongodb/balancer.go
- pkg/controller/perconaservermongodb/fcv.go
- pkg/controller/perconaservermongodb/finalizers.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/smart.go
- pkg/controller/perconaservermongodb/ssl.go
- pkg/controller/perconaservermongodb/status.go
- pkg/controller/perconaservermongodb/users.go
- pkg/controller/perconaservermongodb/version.go
- pkg/controller/perconaservermongodbbackup/backup.go
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
- pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
- pkg/k8s/utils.go
[![K8SPSMDB-754](https://badgen.net/badge/JIRA/K8SPSMDB-754/green)](https://jira.percona.com/browse/K8SPSMDB-754) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The log level that is set in the operator is not respected.
**Cause:**
The logger is instantiated in the manager and passed down to our controllers, but then there is a new global logger that is used throughout the controller.
**Solution:**
Use the logger we instantiate and pass to the controller.
*Note*: This PR also fixes [K8SPSMDB-770](https://jira.percona.com/browse/K8SPSMDB-770) 
- …
> K8SPSMDB-754: Use proper logger in controllers

- Jenkinsfile
[![K8SPSMDB-856](https://badgen.net/badge/JIRA/K8SPSMDB-856/green)](https://jira.percona.com/browse/K8SPSMDB-856) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*License lookup fails.*
**Cause:**
*vsc related flag is missing*
**Solution:**
*Setting proper buildvcs flag.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-856 Fix for license check

- e2e-tests/upgrade-consistency/compare/service_some-name-rs0-1120.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120-oc.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1130-oc.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1130.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1140-oc.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1140.yml
- e2e-tests/upgrade-consistency/run
[![K8SPSMDB-856](https://badgen.net/badge/JIRA/K8SPSMDB-856/green)](https://jira.percona.com/browse/K8SPSMDB-856) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Previously there was some inconsistency between updating crVersion and target files to compare with.*
**Cause:**
*Human factor.*
**Solution:**
*Updating all corresponding files.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-856 Sync crVersion and compare files

- pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-658](https://badgen.net/badge/JIRA/K8SPSMDB-658/green)](https://jira.percona.com/browse/K8SPSMDB-658) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Pausing the cluster is not clearly visible in the operator logs
**Cause:**
**Solution:**
Add a logline that says that the cluster is being paused.
For a non-sharded cluster, logs look like this:
```
2023-02-03T08:43:57.333Z	INFO	controller_psmdb	StatefulSet is not up to date	{"sts": "my-cluster-name-rs0"}
2023-02-03T08:43:57.333Z	INFO	controller_psmdb	Cluster state changed	{"previous": …
```
> K8SPSMDB-658: Improve cluster pausing logs

- e2e-tests/demand-backup-sharded/conf/backup-aws-s3.yml
- e2e-tests/demand-backup-sharded/conf/backup-azure-blob.yml
- e2e-tests/demand-backup-sharded/conf/backup-gcp-cs.yml
- e2e-tests/demand-backup-sharded/conf/backup-minio.yml
- e2e-tests/demand-backup-sharded/run
- e2e-tests/demand-backup/run
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
[![K8SPSMDB-845](https://badgen.net/badge/JIRA/K8SPSMDB-845/green)](https://jira.percona.com/browse/K8SPSMDB-845) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-845
---
**Problem:**
*When we run backup on different storages and then delete the first one, `delete-backup` finalizer fails*
**Cause:**
*Every time we create a backup we set a new pbm config, which contains info about storage.  `delete-backup` finalizer uses pbm to delete backups. When we delete the backup with other storage, we don't set a new pbm config with info …
> K8SPSMDB-845: delete backup finalizer fails with PBM v2 

- pkg/controller/perconaservermongodb/backup.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/psmdb/container.go
- pkg/psmdb/init.go
- pkg/psmdb/pmm.go
- pkg/psmdb/service.go
- pkg/psmdb/statefulset.go
[![K8SPSMDB-770](https://badgen.net/badge/JIRA/K8SPSMDB-770/green)](https://jira.percona.com/browse/K8SPSMDB-770) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Couple of logs were missing namespace and cluster name keys.
**Cause:**
Couple of logs were written with a logger not coming from the context.
**Solution:**
Pass a context where necessary and get the logger from it.
**Note**: PR also fixes duplicate cluster name and namespace keys in some logs. Also adds a bit of refactoring.
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB- 770: Enrich the rest of the logs with namespace and cluster name keys

- e2e-tests/upgrade-sharded/run
- e2e-tests/upgrade/run
[![K8SPSMDB-852](https://badgen.net/badge/JIRA/K8SPSMDB-852/green)](https://jira.percona.com/browse/K8SPSMDB-852) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
After moving to v1 for all operator version we don’t need anymore API vars in our upgrade tests
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-852 delete unsused API vars

- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/finalizers.go
[![K8SPSMDB-767](https://badgen.net/badge/JIRA/K8SPSMDB-767/green)](https://jira.percona.com/browse/K8SPSMDB-767) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-767
---
**Problem:**
*When multiple finalizers are used, only the first one executes and removes the other ones*
**Cause:**
*In the function `checkFinalizers`, when one of the finalizers throws an error, it's getting added to the new finalizers array and saved to the cr without the next ones.*
**Solution:**
*We should save other finalizers when some of them throw …
> K8SPSMDB-767: fix finalizers

- pkg/controller/perconaservermongodb/users.go
[![K8SPSMDB-866](https://badgen.net/badge/JIRA/K8SPSMDB-866/green)](https://jira.percona.com/browse/K8SPSMDB-866) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Fix the logs condition. It should be printed only if pmm enabled: true
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-866 fix the log condition

- Jenkinsfile
- e2e-tests/expose-sharded/run
- e2e-tests/recover-no-primary/conf/some-name-exposed.yml
- e2e-tests/recover-no-primary/conf/some-name-sharded.yml
- e2e-tests/recover-no-primary/conf/some-name.yml
- e2e-tests/recover-no-primary/run
- pkg/apis/psmdb/v1/psmdb_defaults.go
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/psmdb/service.go
[![K8SPSMDB-867](https://badgen.net/badge/JIRA/K8SPSMDB-867/green)](https://jira.percona.com/browse/K8SPSMDB-867) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
We were using exposed IPs in replset configuration in case replset is exposed. This was causing occasional full cluster crashes, hard to reason about and apparently against the MongoDB best practices.
Having exposed IP addresses in replset configuration is especially important for enabling multi cluster deployments. In a multi cluster setup, replset members can be in different Kubernetes cluster but …
> K8SPSMDB-867: Use local FQDNs unless DNS mode is external

- deploy/cr.yaml
[![K8SPSMDB-708](https://badgen.net/badge/JIRA/K8SPSMDB-708/green)](https://jira.percona.com/browse/K8SPSMDB-708) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*The example mentioned wrong initImage name due to some copypaste*
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-708 Fix the initImage example in cr.yaml

- deploy/backup/restore.yaml
---
**Solution:**
*New option for backup type is missing from backupSource example in restore.yaml so add it in.*
**CHECKLIST**
---
**Jira**
**Tests**
> Add backup type into restore example for backupSource

- pkg/controller/perconaservermongodb/version_test.go
[![K8SPSMDB-853](https://badgen.net/badge/JIRA/K8SPSMDB-853/green)](https://jira.percona.com/browse/K8SPSMDB-853) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-853
---
**Problem:**
*`version_test.go` sometimes fails in our pipelines*
**Cause:**
*Version service gateway is launched in another goroutine and starts after sending requests to it*
**Solution:**
*We should wait until the gateway starts to listen for connections and then serve it in another goroutine*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-853: fix `version_test` unit-test

- build/ps-entry.sh
- deploy/cr.yaml
[![K8SPSMDB-873](https://badgen.net/badge/JIRA/K8SPSMDB-873/green)](https://jira.percona.com/browse/K8SPSMDB-873) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
**Problem:**
Parsing config fails due to mongosh writes the error message to the config file.
**Cause:**
On openshift 4.11 mongosh wants to write to the root home dir which has no permissions, it returns the error and writes it to the config file which then fails when trying to parse it as JSON.
**Solution:**
When executing `mongosh` set home dir to `/tmp` rather than `/`
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-873: Change HOME dir for mongosh

- e2e-tests/demand-backup-physical/compare/statefulset_some-name-rs0_restore-oc.yml
- e2e-tests/functions
- e2e-tests/mongod-major-upgrade-sharded/run
- e2e-tests/mongod-major-upgrade/run
- e2e-tests/service-per-pod/compare/statefulset_node-port-rs0-oc.yml
- e2e-tests/service-per-pod/run
- e2e-tests/version-service/run
---
**Problem:**
6.0.4-3 results in 4-3-recommended
**Cause:**
Human factor
**Solution:**
Utilize the already existing infrastructure
**CHECKLIST**
---
**Jira**
**Tests**
> Fix for version-service semver channel name

- e2e-tests/demand-backup-sharded/run
- e2e-tests/expose-sharded/run
- e2e-tests/init-deploy/run
- e2e-tests/multi-cluster-service/run
- e2e-tests/pitr-sharded/run
- e2e-tests/upgrade-consistency/run
[![K8SPSMDB-878](https://badgen.net/badge/JIRA/K8SPSMDB-878/green)](https://jira.percona.com/browse/K8SPSMDB-878) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*`upgrade-consistency` test is running 3 node replica but only checking for running 1 pod and it doesn't check cluster readyness.
Some tests try to add docker handler for container runtimeclass, but it is unavailable in EKS 1.24*
**Solution:**
*Add missing checks and use runc in EKS 1.24*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-878 - Fix EKS tests

- pkg/controller/perconaservermongodb/version_test.go
- pkg/controller/perconaservermongodbrestore/physical.go
[![K8SPSMDB-713](https://badgen.net/badge/JIRA/K8SPSMDB-713/green)](https://jira.percona.com/browse/K8SPSMDB-713) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
PBM describe-restore command not retried on failure
**Solution:**
On `container is not created or running` error retry PBM describe-restore command.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-713: Retry PBM describe-restore on failure

- e2e-tests/functions
[![K8SPSMDB-881](https://badgen.net/badge/JIRA/K8SPSMDB-881/green)](https://jira.percona.com/browse/K8SPSMDB-881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
we should not wait any longer if the restore error happened
---
**Problem:**
The testing framework blindly expects for OK state
**Cause:**
Human factor
**Solution:**
Additional error checking
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-881 Force error exit on restore error

- e2e-tests/cross-site-sharded/conf/cross-site-sharded-main.yml
- e2e-tests/cross-site-sharded/conf/cross-site-sharded-replica.yml
- e2e-tests/cross-site-sharded/disaster_recovery.js
- e2e-tests/cross-site-sharded/run
---
**Problem:**
cross-site-sharded sometimes fails on failover check.
**Cause:**
this test mixes exposed IPs and local FQDNs in the replset config. 
**Solution:**
* we should use `clusterServiceDNSMode: External` in main and replica clusters.
* now test output is a bit more informative.
* now test waits for replica cluster to be ready.
> fix cross-site-sharded

- Jenkinsfile
[![CLOUD-775](https://badgen.net/badge/JIRA/CLOUD-775/green)](https://jira.percona.com/browse/CLOUD-775) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Currently in dev pipelines when a new commit is pushed we delete the associated kubernetes clusters for the previous build, but if the pipeline was in its parallel stage in that case the jenkins executor might get stuck so the executor spot instance will be killed only later.*
**Solution:**
*In the clusterRunner() and in runTest() when the test needs to be re-run on next test run check if there …
> CLOUD-775 - Fix cancelation of parallel pipeline build

- build/pbm-entry.sh
[![K8SPSMDB-911](https://badgen.net/badge/JIRA/K8SPSMDB-911/green)](https://jira.percona.com/browse/K8SPSMDB-911) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
delete connection str from backup-agent  logs
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-911 delete connection str from backup-agent  logs

- Jenkinsfile
[![CLOUD-783](https://badgen.net/badge/JIRA/CLOUD-783/green)](https://jira.percona.com/browse/CLOUD-783) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Services which use LoadBalancer can leave external objects in GKE when the cluster is deleted.*
**Solution:**
*We delete operator/services and some other objects prior to cluster deletion so external LoadBalancers and related objects should get cleaned up.*
**CHECKLIST**
---
**Jira**
**Tests**
> CLOUD-783 - Cleanup test cluster before deletion

- e2e-tests/demand-backup-sharded/run
- e2e-tests/demand-backup/run
- e2e-tests/functions
- e2e-tests/init-deploy/run
- e2e-tests/monitoring-2-0/run
[![CLOUD-789](https://badgen.net/badge/JIRA/CLOUD-789/green)](https://jira.percona.com/browse/CLOUD-789) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Create a test to start the cluster with some fixed passwords and then let the script loop over pods/containers and check the logs for the strings.
> CLOUD-789 - adding password leak check in demand-backup, init-deploy, monitoring-2-0

- .gitignore
- cmd/mongodb-healthcheck/main.go
- healthcheck/health.go
- healthcheck/readiness.go
- healthcheck/tools/db/db.go
- pkg/controller/perconaservermongodb/backup.go
- pkg/controller/perconaservermongodb/balancer.go
- pkg/controller/perconaservermongodb/connections.go
- pkg/controller/perconaservermongodb/connections_test.go
- pkg/controller/perconaservermongodb/fcv.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/secrets.go
- pkg/controller/perconaservermongodb/smart.go
- pkg/controller/perconaservermongodb/status_test.go
- pkg/controller/perconaservermongodb/users.go
- pkg/controller/perconaservermongodb/version.go
- pkg/controller/perconaservermongodbbackup/backup.go
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
- pkg/controller/perconaservermongodbrestore/logical.go
- pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
- pkg/psmdb/backup/backup.go
- pkg/psmdb/backup/fake/pbm.go
- pkg/psmdb/backup/pbm.go
- pkg/psmdb/client.go
- pkg/psmdb/getters.go
- pkg/psmdb/mongo/fake/client.go
- pkg/psmdb/mongo/mongo.go
- pkg/psmdb/mongos.go
[![K8SPSMDB-962](https://badgen.net/badge/JIRA/K8SPSMDB-962/green)](https://jira.percona.com/browse/K8SPSMDB-962) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-962
---
**Problem:**
*While using a cluster with `unmanaged: true`, the operator continually increases both CPU and memory usage.*
**Cause:**
*Regression was introduced in https://github.com/percona/percona-server-mongodb-operator/commit/2fa149d8c0a874944399c96cf9b3c3b1c108ae47. In this commit, I added code to exit the function if the cluster is unmanaged before declaring …
> K8SPSMDB-962: fix memory leak

- e2e-tests/default-cr/run
- e2e-tests/functions
---
**Problem:**
*Test `default-cr` sleeps too much and ends up hitting the 1h timeout if it has issues instead of failing quickly. `OPERATOR_VERSION` in e2e-tests/functions uses yq which is not available everywhere.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-886 - Fix default-cr test and OPERATOR_VERSION in functions

- go.mod
- go.sum
- pkg/controller/perconaservermongodbrestore/logical.go
[![K8SPSMDB-981](https://badgen.net/badge/JIRA/K8SPSMDB-981/green)](https://jira.percona.com/browse/K8SPSMDB-981) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
PITR stopped working.
**Cause:**
PBM now needs the backup name in RestoreCmd.
**Solution:**
Bump PBM and send backup name in RestoreCmd.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-981: Upgrade PBM to v2.3.0

- e2e-tests/finalizer/run
- e2e-tests/functions
[![K8SPSMDB-980](https://badgen.net/badge/JIRA/K8SPSMDB-980/green)](https://jira.percona.com/browse/K8SPSMDB-980) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*It was impossible to delete a cluster if rs0-0 was not primary and we were missing a test case for this so this PR is adding a test case.*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-980 - Add case in finalizer test for delete when rs0-0 is not primary

- e2e-tests/init-deploy/compare/backup-60.json
- e2e-tests/init-deploy/compare/clusterAdmin-60.json
- e2e-tests/init-deploy/compare/clusterMonitor-60.json
- e2e-tests/init-deploy/compare/userAdmin-60.json
- e2e-tests/run-minikube.csv
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-886 - Fix init-deploy test for 6.0 and remove some minikube tests

- Jenkinsfile
- e2e-tests/custom-replset-name/conf/backup-aws-s3.yml
- e2e-tests/custom-replset-name/conf/backup-gcp-cs.yml
- e2e-tests/custom-replset-name/run
- e2e-tests/expose-sharded/run
- e2e-tests/multi-cluster-service/run
- e2e-tests/operator-self-healing-chaos/run
- e2e-tests/pitr-physical/run
- e2e-tests/rs-shard-migration/run
- e2e-tests/smart-update/run
- e2e-tests/upgrade-sharded/run
- e2e-tests/upgrade/run
---
1. Change PR tests to run with cluster wide mode enabled
2. Some tests were calling `wait_cluster_consistency` function with non-existing/old second parameter for cluster size
3. Some tests were not checking things correctly in cluster wide mode`
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-886 - Add cluster wide run for PR tests and fix some tests

- e2e-tests/conf/cmctl.yml
- e2e-tests/default-cr/run
- e2e-tests/security-context/run
- e2e-tests/tls-issue-cert-manager/run
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB - Fix tests

- deploy/bundle.yaml
- deploy/cw-bundle.yaml
- deploy/cw-rbac.yaml
- deploy/rbac.yaml
[![K8SPSMDB-992](https://badgen.net/badge/JIRA/K8SPSMDB-992/green)](https://jira.percona.com/browse/K8SPSMDB-992) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*On OpenShift we started getting issue while issuing certificates with cert-manager: `"errorVerbose": "issuers.cert-manager.io \"my-cluster-name-psmdb-ca-issuer\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on:`*
**Cause:**
*Possibly OpenShift enabled `OwnerReferencesPermissionEnforcement`*
**Solution:**
*Update rbac to …
> K8SPSMDB-992 - Add rbac rules for finalizers (fix issuing certs with cert-manager in OpenShift)

- e2e-tests/default-cr/run
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0.yml
- e2e-tests/monitoring-2-0/run
- pkg/psmdb/pmm.go
[![K8SPSMDB-991](https://badgen.net/badge/JIRA/K8SPSMDB-991/green)](https://jira.percona.com/browse/K8SPSMDB-991) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*In `2.39` PMM changed to use `/usr/local/percona/pmm2/tmp` as a temp directory for pbm-agent which is failing in openshift because of permissions.*
**Solution:**
*We will set `PMM_AGENT_PATHS_TEMPDIR` back under `/tmp`*
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-991 - Add PMM_AGENT_PATHS_TEMPDIR env var for pmm-agent sidecar

- build/pbm-entry.sh
[![K8SPSMDB-1024](https://badgen.net/badge/JIRA/K8SPSMDB-1024/green)](https://jira.percona.com/browse/K8SPSMDB-1024) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*pbm-entry script is having a variable scope issue. 
**Cause:**
*pbm-entry script is having a variable scope issue where the needed env does not get updated by the script. Instead, it keeps the initial value from the previous line even after being updated through the if statement. 
**Solution:**
* The solution is to move the line where it's piping to a file after the variable gets set. …
> K8SPSMDB-1024 fixed variable scope and make sure it always get sets

- .github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-727 we can set day only for weekly interval

- e2e-tests/functions
- e2e-tests/upgrade-consistency-sharded/compare/statefulset_some-name-cfg-1160-oc.yml
- e2e-tests/upgrade-consistency-sharded/compare/statefulset_some-name-cfg-1160.yml
- e2e-tests/upgrade-consistency-sharded/compare/statefulset_some-name-rs0-1160-oc.yml
- e2e-tests/upgrade-consistency-sharded/compare/statefulset_some-name-rs0-1160.yml
- e2e-tests/upgrade-consistency-sharded/conf/some-name.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1160-oc.yml
- e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1160.yml
- e2e-tests/upgrade-consistency/conf/some-name-rs0.yml
[![K8SPSMDB-1018](https://badgen.net/badge/JIRA/K8SPSMDB-1018/green)](https://jira.percona.com/browse/K8SPSMDB-1018) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*There was a bugfix [here](https://github.com/percona/percona-server-mongodb-operator/pull/1382) for new PSMDB images and numactl support, but when it was fixed the `upgrade-consistency` tests stopped working because old docker images don't have numactl.*
**Solution:**
*Temporarily set initImage to perconalab `main` operator image.*
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-1018 - Fix upgrade-consistency test to work with new image

- config/crd/bases/psmdb.percona.com_perconaservermongodbs.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- deploy/cw-operator.yaml
- deploy/operator.yaml
- e2e-tests/version-service/conf/crd.yaml
[![K8SPSMDB-1033](https://badgen.net/badge/JIRA/K8SPSMDB-1033/green)](https://jira.percona.com/browse/K8SPSMDB-1033) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Inconsistency and possibly issues with prometheus monitoring. In other operators we use `8080` for metrics.
We are also missing a liveness probe which we have in other operators.*
**Solution:**
*Change port to 8080 and add liveness probe.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1033]: https://perconadev.atlassian.net/browse/K8SPSMDB-1033?atlOrigin …
> K8SPSMDB-1033 - Change operator container port for metrics to 8080

- .github/workflows/reviewdog.yml
- .github/workflows/scan.yml
- .github/workflows/test.yml
- Jenkinsfile
- build/Dockerfile
- e2e-tests/build
[![K8SPSMDB-948](https://badgen.net/badge/JIRA/K8SPSMDB-948/green)](https://jira.percona.com/browse/K8SPSMDB-948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
https://jira.percona.com/browse/K8SPSMDB-948
https://forums.percona.com/t/mongo-operator-and-arm/24326
**Cause:**
Multi arch image.
**Solution:**
Hello, 
This small changes allows to build PSMDB for different architectures.
```shell
make build DOCKER_DEFAULT_PLATFORM=linux/amd64,linux/arm64 IMAGE=ghcr.io/sergelogvinov/percona-server-mongodb-operator:v1.14.0
```
the result image: …
> K8SPSMDB-948: Multi arch build

- README.md
[![CLOUD-820](https://badgen.net/badge/JIRA/CLOUD-820/green)](https://jira.percona.com/browse/CLOUD-820) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
modified:   README.md
---
**Problem:** 
READMEs across all Operators are misaligned, having different structure, content and lacking links to Documentation
Update README to mention documentation
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira** …
> CLOUD-820 Update README to mention documentation

- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0.yml
- e2e-tests/monitoring-2-0/run
- pkg/psmdb/pmm.go
[![K8SPSMDB-1039](https://badgen.net/badge/JIRA/K8SPSMDB-1039/green)](https://jira.percona.com/browse/K8SPSMDB-1039) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* use 'pmm-admin unregister' command to the instance from server inventory on pod termination
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1039]: …
> K8SPSMDB-1039 fix deletion from server inventory on pod termination

- e2e-tests/functions
[![K8SPSMDB-998](https://badgen.net/badge/JIRA/K8SPSMDB-998/green)](https://jira.percona.com/browse/K8SPSMDB-998) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Chaos mesh objects have finalizers and if you try to delete crd with these objects not yet deleted it might fail and cause next test to fail to re-initialize chaos mesh.*
**Solution:**
*Empty finalizer in chaos mesh objects before deleting the object and crd.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-998]: …
> K8SPSMDB-998 - Fix chaos mesh cleanup

- e2e-tests/users/run
- healthcheck/tools/db/config.go
[![K8SPSMDB-1011](https://badgen.net/badge/JIRA/K8SPSMDB-1011/green)](https://jira.percona.com/browse/K8SPSMDB-1011) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When usernames get changed, mongos crashes.
**Cause:**
When doing liveness/readiness probes, password was read from secret file while username was read from env var. Since the only way for env var to be updated is with a pod restart, mongos pods read old username thus start to fail.
**Solution:**
Read username from secret file rather than env var in mongos, just like we do for …
> K8SPSMDB-1011: Fix broken username change

- build/Dockerfile
[![K8SPSMDB-948](https://badgen.net/badge/JIRA/K8SPSMDB-948/green)](https://jira.percona.com/browse/K8SPSMDB-948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Move mod download to sepparate layer.
Golang builds faster in native architecture.
Part of this changes i've got from https://github.com/percona/percona-server-mysql-operator/blob/main/build/Dockerfile
Thanks.
**Cause:**
**Solution:**
**CHECKLIST**
--- …
> K8SPSMDB-948 Multi arch build improvements

- e2e-tests/build
[![K8SPSMDB-948](https://badgen.net/badge/JIRA/K8SPSMDB-948/green)](https://jira.percona.com/browse/K8SPSMDB-948) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* if the use wants to build different arch or multi-arch
build DOCKER_DEFAULT_PLATFORM env var should be set
Jenkins job PR is https://github.com/Percona-Lab/jenkins-pipelines/pull/2554, test build https://cloud.cd.percona.com/view/PSMDB/job/psmdb-docker-build/1695/ 
---
**Problem:**
**Cause:** …
> K8SPSMDB-948 by default build only 'linux/amd64' arch

- Jenkinsfile
- e2e-tests/functions
- e2e-tests/pitr-physical/run
- go.mod
- go.sum
- pkg/apis/psmdb/v1/perconaservermongodbbackup_types.go
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/backup.go
- pkg/controller/perconaservermongodb/version.go
- pkg/controller/perconaservermongodb/version_test.go
- pkg/controller/perconaservermongodbbackup/backup.go
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
- pkg/controller/perconaservermongodbrestore/logical.go
- pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
- pkg/controller/perconaservermongodbrestore/physical.go
- pkg/psmdb/backup/backup.go
- pkg/psmdb/backup/fake/pbm.go
- pkg/psmdb/backup/job.go
- pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1051](https://badgen.net/badge/JIRA/K8SPSMDB-1051/green)](https://jira.percona.com/browse/K8SPSMDB-1051) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1051]: https://perconadev.atlassian.net/browse/K8SPSMDB-1051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> K8SPSMDB-1051: Bump PBM version to 2.4.0

- pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-1050](https://badgen.net/badge/JIRA/K8SPSMDB-1050/green)](https://jira.percona.com/browse/K8SPSMDB-1050) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Labels were depricated and I changed them to new ones.
failure-domain.beta.kubernetes.io/region
failure-domain.beta.kubernetes.io/zone
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-1050 change labels which were depricated

- Makefile
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Manual steps need to be taken to prepare release branch and also to prepare main branch after release branch is merged.
**Solution:**
With this manifests will be prepared but also next version and main images set in cr.yaml. What we need to still do manually is set specific database/backup and other images before the release since each product has it's own.
Prepare release example:
`make release …
> CLOUD-833 - Add release and after-release targets to Makefile

- e2e-tests/functions
- e2e-tests/pitr-sharded/run
[![K8SPSMDB-1064](https://badgen.net/badge/JIRA/K8SPSMDB-1064/green)](https://jira.percona.com/browse/K8SPSMDB-1064) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Test is sporadically failing because backup is started on non ready cluster.*
**Solution:**
*Wait for cluster readyness before starting backup*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1064]: https://perconadev.atlassian.net/browse/K8SPSMDB-1064?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1064 - Minor fix in pitr-sharded test for sporadic failure

- e2e-tests/functions
- e2e-tests/pitr/run
- pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1065](https://badgen.net/badge/JIRA/K8SPSMDB-1065/green)](https://jira.percona.com/browse/K8SPSMDB-1065) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
To check if PITR is stopped operator uses `GetLocks()` function and it returns nothing because pitr slicing now is under `GetOpLocks()`
**Solution:**
Use `GetOpLocks()`
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1065]: https://perconadev.atlassian.net/browse/K8SPSMDB-1065?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWN …
> K8SPSMDB-1065: Fix checking oplog slicing locks

- e2e-tests/default-cr/compare/statefulset_minimal-cluster-cfg-oc.yml
- e2e-tests/default-cr/compare/statefulset_minimal-cluster-cfg.yml
- e2e-tests/default-cr/compare/statefulset_minimal-cluster-rs0-oc.yml
- e2e-tests/default-cr/compare/statefulset_minimal-cluster-rs0.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-cfg-1140-oc.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-cfg-1150-oc.yml
[![K8SPSMDB-998](https://badgen.net/badge/JIRA/K8SPSMDB-998/green)](https://jira.percona.com/browse/K8SPSMDB-998) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
These tests are not run in PR tests so the option was not added correctly.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-998]: https://perconadev.atlassian.net/browse/K8SPSMDB-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB - Fix default-cr and upgrade-consistency-sharded-tls tests

- pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-1082](https://badgen.net/badge/JIRA/K8SPSMDB-1082/green)](https://jira.percona.com/browse/K8SPSMDB-1082) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
When deleting RS and all associated stateful sets, in some instances due to timing (especially on EKS), the operator fails to delete non-voting/arbiter stateful sets and they stay hanging there.
**Cause:**
The operator first deletes like main RS sts then non-voting/arbiter. When we do that and then we want to remove non-voting RS, the operator fails with the error `Type: …
> K8SPSMDB-1082 - First delete non-voting/arbiter STS

- build/physical-restore-ps-entry.sh
[![K8SPSMDB-1083](https://badgen.net/badge/JIRA/K8SPSMDB-1083/green)](https://jira.percona.com/browse/K8SPSMDB-1083) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Liveness probe should be disabled during physical restore, otherwise it can make restore fail in big databases.
**Solution:**
Have a special file to temporarily disable liveness checks.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1083]: https://perconadev.atlassian.net/browse/K8SPSMDB-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLC …
> K8SPSMDB-1083: Disable liveness probe during physical restore

- .github/workflows/reviewdog.yml
[![CLOUD-849](https://badgen.net/badge/JIRA/CLOUD-849/green)](https://jira.percona.com/browse/CLOUD-849) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*On release branches we don't use main images so the reviewdog for manifests is failing and we need to ignore it.*
**Solution:**
*If a branch is named `release-` then we will use the exact version and instead of `perconalab` use `percona` repository. The check will only be done for operator image and bundles, not for other images since we cannot know all the versions.*
Test run on fake release …
> CLOUD-849 - Fix reviewdog for manifests on release branch

- e2e-tests/functions
- e2e-tests/tls-issue-cert-manager/compare/certificate_some-name-ca-cert-custom.yml
- e2e-tests/tls-issue-cert-manager/compare/certificate_some-name-ssl-custom.yml
- e2e-tests/tls-issue-cert-manager/compare/certificate_some-name-ssl-internal-custom.yml
- e2e-tests/tls-issue-cert-manager/compare/issuer_some-name-psmdb-ca-issuer-custom.yml
- e2e-tests/tls-issue-cert-manager/compare/issuer_some-name-psmdb-issuer-custom.yml
- e2e-tests/tls-issue-cert-manager/conf/some-name-ca-cert.yml
- e2e-tests/tls-issue-cert-manager/conf/some-name-psmdb-ca-issuer.yml
- e2e-tests/tls-issue-cert-manager/conf/some-name-psmdb-issuer.yml
- e2e-tests/tls-issue-cert-manager/conf/some-name-ssl-internal.yml
- e2e-tests/tls-issue-cert-manager/conf/some-name-ssl.yml
- e2e-tests/tls-issue-cert-manager/run
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/ssl.go
- pkg/psmdb/tls/certmanager.go
- pkg/psmdb/tls/tls.go
[![K8SPSMDB-1101](https://badgen.net/badge/JIRA/K8SPSMDB-1101/green)](https://jira.percona.com/browse/K8SPSMDB-1101) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-1101
---
**Problem:**
*Custom certificates created using `cert-manager` are overwritten by operator.*
**Cause:**
*If tls secrets were created using `cert-manager`, the operator doesn't check whether they were created by the user.*
**Solution:**
*Check that the tls secrets created using `cert-manager` have been created by the user.*
**CHECKLIST**
---
**Jira** …
> K8SPSMDB-1101: fix usage of custom cert-manager certificates

- e2e-tests/pvc-resize/run
- pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-1117](https://badgen.net/badge/JIRA/K8SPSMDB-1117/green)](https://jira.percona.com/browse/K8SPSMDB-1117) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Cluster status remains ready during PVC resize. This, sometimes, causes PerconaServerMongoDB object to be deleted before statefulset is recreated.
**Solution:**
Ensure cluster status is initializing during PVC resize.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1117]: https://perconadev.atlassian.net/browse/K8SPSMDB-1117?atlOrigin=eyJpIjoiNWRkNTljNzYxNj …
> K8SPSMDB-1117: Fix pvc-resize test on EKS

- pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-1094](https://badgen.net/badge/JIRA/K8SPSMDB-1094/green)](https://jira.percona.com/browse/K8SPSMDB-1094) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
If `cr.Spec.UpgradeOptions.SetFCV` is set to `true` and we create a fresh cluster, the operator errors out with:
```
"error": "failed to set FCV: invalid version: Malformed version: "
```
**Cause:**
We pass `cr.Status.MongoVersion` to `r.upgradeFCVIfNeeded` and since `cr.Status.MongoVersion` is empty when creating a new cluster, the operator errors with the mentioned error since we …
> K8SPSMDB-1094: Check FCV

- e2e-tests/demand-backup-physical-sharded/run
[![K8SPSMDB-1098](https://badgen.net/badge/JIRA/K8SPSMDB-1098/green)](https://jira.percona.com/browse/K8SPSMDB-1098) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1098]: https://perconadev.atlassian.net/browse/K8SPSMDB-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> K8SPSMDB-1098 fix demand-backup-physical-sharded test

- pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-1089](https://badgen.net/badge/JIRA/K8SPSMDB-1089/green)](https://jira.percona.com/browse/K8SPSMDB-1089) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-1089
---
**Problem:**
*If the user created a cluster with finalizers and wrong options, it would be impossible to delete a cluster.*
**Cause:**
*Part of code which is responsible for deleting finalizers is executed after the `CheckNSetDefaults` method. If this method fails due to invalid cluster options, finalizers will not be deleted.*
**Solution:**
*We need …
> K8SPSMDB-1089: fix deleting cluster with wrong options

- pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-899](https://badgen.net/badge/JIRA/K8SPSMDB-899/green)](https://jira.percona.com/browse/K8SPSMDB-899) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-899
---
This PR adds missing labels to the following secrets:
- `<cluster-name>-mongodb-encryption-key`
- `<cluster-name>-mongodb-keyfile`
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-899]: https://perconadev.atlassian.net/browse/K8SPSMDB-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> K8SPSMDB-899: add missing labels to secrets

- pkg/psmdb/container.go
- pkg/psmdb/mongos.go
[![K8SPSMDB-1175](https://badgen.net/badge/JIRA/K8SPSMDB-1175/green)](https://jira.percona.com/browse/K8SPSMDB-1175) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-1175
---
**Problem:**
*When `.spec.unsafeFlags.tls` is switched to `true` while TLS is enabled, all statefulsets are updated to use `--clusterAuthMode=keyFile` instead of `--clusterAuthMode=x509`. This leads to mongos being stuck in a smartUpdate.*
**Cause:**
*My PR https://github.com/percona/percona-server-mongodb-operator/pull/1639 introduced a regression, by …
> K8SPSMDB-1175: fix `clusterAuthMode`

- deploy/cr.yaml
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/service.go
- pkg/controller/perconaservermongodbrestore/physical.go
[![K8SPSMDB-739](https://badgen.net/badge/JIRA/K8SPSMDB-739/green)](https://jira.percona.com/browse/K8SPSMDB-739) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-739
---
**Problem:**
*Cluster goes into error state when `servicePerPod` is enabled. New services are not created. The following error is displayed in the operator: `failed to get mongos connection: ping mongo: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: , Type: Unknown, Last error: dial tcp: …
> K8SPSMDB-739: fix switching `servicePerPod`

- Jenkinsfile
- e2e-tests/balancer/run
[![K8SPSMDB-739](https://badgen.net/badge/JIRA/K8SPSMDB-739/green)](https://jira.percona.com/browse/K8SPSMDB-739) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We do not have any test that checks that servicePerPOD for mongos works
**Solution:**
Add test
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-739]: https://perconadev.atlassian.net/browse/K8SPSMDB-739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-739: add test for mongos servicePerPod

- Jenkinsfile
- pkg/apis/psmdb/v1/psmdb_defaults.go
- pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-1170](https://badgen.net/badge/JIRA/K8SPSMDB-1170/green)](https://jira.percona.com/browse/K8SPSMDB-1170) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-1170
---
**Problem:**
*When pods are in `CrashLoopBackOff` state, cluster is in `initializing` state. In this situation it's not possible to delete the cluster, when finalizers are set.*
**Solution:**
*Set `error` state when pods are in `CrashLoopBackOff` state.*
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1170]: …
> K8SPSMDB-1170: set `error` state when pods are in `CrashLoopBackOff`

- e2e-tests/conf/client_with_tls.yml
- e2e-tests/demand-backup-physical/run
- e2e-tests/functions
- e2e-tests/pitr-physical/run
- go.mod
- go.sum
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
- pkg/controller/perconaservermongodbrestore/physical.go
- pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1177](https://badgen.net/badge/JIRA/K8SPSMDB-1177/green)](https://jira.percona.com/browse/K8SPSMDB-1177) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Bump PBM to 2.7.0.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1177]: https://perconadev.atlassian.net/browse/K8SPSMDB-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1177: Bump PBM to 2.7.0

- e2e-tests/data-at-rest-encryption/run
- e2e-tests/demand-backup-physical-sharded/run
- e2e-tests/demand-backup-physical/run
- e2e-tests/pvc-resize/run
- e2e-tests/serviceless-external-nodes/compare/statefulset_mydb-rs0-oc.yml
- e2e-tests/serviceless-external-nodes/run
---
**Problem:**
1) `demand-backup-physical-sharded` and `demand-backup-physical` failing
2) `pvc-resize` on `openshift` fails
3) `serviceless-external-nodes` on openshift fails
**Cause:**
1) Restore stays in waiting status for `demand-backup-physical-sharded` and `demand-backup-physical` due to long PBM resync. 
2) `pvc-resize` on openshift fails - starting with 1.18.0 `pvc-resize` is disabled by default. On EKS and openshift we recreate cluster in the middle of `pvc-resise` test (due to limits for resize requests) but did not enable pvc-resize again
3) `serviceless-external-nodes` on openshift fails - check of `secrets` number was added to tests. `secrets` on openshift have dockercfg secrets:
```
k get secret
NAME                                              TYPE …
```
> Release 1.18.0 push test

- deploy/cr.yaml
[![K8SPSMDB-1160](https://badgen.net/badge/JIRA/K8SPSMDB-1160/green)](https://jira.percona.com/browse/K8SPSMDB-1160) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
PVC resize is now disabled by default, but enableVolumeExpansion option in cr.yaml is commented, but true
**Cause:**
Our deploy/cr.yaml contains default values, when applicable.
**Solution:**
We need to set the appropriate option example to false, to keep uniformity.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1160]: …
> K8SPSMDB-1160 Disable PVC resize in the cr.yaml example

- e2e-tests/cross-site-sharded/run
- pkg/apis/psmdb/v1/psmdb_defaults.go
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodbbackup/backup.go
- pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
- pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1205](https://badgen.net/badge/JIRA/K8SPSMDB-1205/green)](https://jira.percona.com/browse/K8SPSMDB-1205) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We don't allow users to run backups in unmanaged clusters.
**Cause:**
We deliberately added this limitation to prevent confusing users. If you run a backup in an unmanaged (and secondary) cluster, backup object will be created in unmanaged cluster but you won't be able to restore it in the same cluster.
**Solution:**
We're removing the limitation. Technically, we don't need to do much …
> K8SPSMDB-1205: Allow backups in unmanaged clusters

- e2e-tests/expose-sharded/compare/statefulset_some-name-cfg-4-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-cfg-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-cfg.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-4-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-disabled-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-disabled.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-enabled-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-enabled.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0.yml
- e2e-tests/run-pr.csv
- e2e-tests/run-release.csv
- e2e-tests/stable-resource-version/conf/some-name.yml
- e2e-tests/stable-resource-version/run
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/version.go
---
**Problem:**
Operator constantly updates status conditions.
**Solution:**
Fix the problem with updating conditions and add an e2e test to check if resourceVersion is stable.
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-675: Fix constantly updated status conditions

- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/controller/perconaservermongodb/custom_users.go
[![K8SPSMDB-1164](https://badgen.net/badge/JIRA/K8SPSMDB-1164/green)](https://jira.percona.com/browse/K8SPSMDB-1164) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
In certain situations, the operator can attempt to update the password for a user with a `$external` DB set. Also, for this user the operator generates the password and stores it in the generated custom user secret.
The `$externalDB` user's password is in an external system like LDAB and the operator shouldn't do anything password-related for users like this.
**CHECKLIST**
---
**Jira** …
> K8SPSMDB-1164: Prevent $external DB user from dealing with passwords

- e2e-tests/demand-backup-fs/run
[![K8SPSMDB-1109](https://badgen.net/badge/JIRA/K8SPSMDB-1109/green)](https://jira.percona.com/browse/K8SPSMDB-1109) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Two problems on EKS:
1. There's no default storage class.
2. NFS mounts using FQDN of the service doesn't work.
**Solution:**
1. Set default storage class.
2. Use IP instead of FQDN for NFS mount.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1109]: https://perconadev.atlassian.net/browse/K8SPSMDB-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
> K8SPSMDB-1109: Fix demand-backup-fs on EKS

- e2e-tests/self-healing-chaos/run
[![K8SPSMDB-1248](https://badgen.net/badge/JIRA/K8SPSMDB-1248/green)](https://jira.percona.com/browse/K8SPSMDB-1248) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Test case `wait_for_running` fails on Minikube just before [enable backups](https://github.com/percona/percona-server-mongodb-operator/blob/31622a4d2b8eb5e020dfe81227469ea9f546335c/e2e-tests/self-healing-chaos/run#L34) and the cluster ends up in "error" state.
**Cause:**
**Solution:**
I thought that we shouldn't care …
> K8SPSMDB-1248 Add wait_for_running check after cluster creation in self-healing-chaos tests

- Makefile
[![CLOUD-881](https://badgen.net/badge/JIRA/CLOUD-881/green)](https://jira.percona.com/browse/CLOUD-881) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The "release" rule was not fully automated, requiring manual replacement of images in the release process.
**Cause:**
**Solution:**
The Makefile rule release can be improved by using the images present in release_versions file, eliminating the manual replacement of the images names.
**CHECKLIST**
---
**Jira**
**Tests** …
> CLOUD-881: Use release_versions in Makefile release rule

- e2e-tests/demand-backup-eks-credentials-irsa/compare/statefulset_some-name-rs0.yml
---
**Problem:**
Compare file is using outdated backup user and password.
**Cause:**
**Solution:**
Update to the correct user and password.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: https://perconadev.atlassian.net/browse/K8SPSMDB-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
> K8SPSMDB-1224: Fix secretKeyRef key in demand-backup-eks-credentials-irsa test

- e2e-tests/demand-backup-fs/run
[![K8SPSMDB-1109](https://badgen.net/badge/JIRA/K8SPSMDB-1109/green)](https://jira.percona.com/browse/K8SPSMDB-1109) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Same as https://github.com/percona/percona-server-mongodb-operator/pull/1773, NFS mounts using FQDN of the service doesn't work in azure.
**Solution:**
Set default storage class and do not use FQDN for platforms different than GKE.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1109]: https://perconadev.atlassian.net/browse/K8SPSMDB-1109?atlOrigin=eyJpIjoi …
> K8SPSMDB-1109: Fix demand-backup-fs in Azure

- Makefile
- e2e-tests/demand-backup-fs/conf/some-name.yaml
- e2e-tests/replset-overrides/conf/some-name-overridden.yml
- e2e-tests/replset-overrides/conf/some-name-override-priority.yml
- e2e-tests/replset-overrides/conf/some-name.yml
- e2e-tests/version-service/conf/operator.9.9.9.psmdb-operator.json
- e2e-tests/version-service/run
- pkg/psmdb/backup/testdata/cr-with-pbm-config.yaml
---
**Problem:**
Tests were using Mongo 7.0 image, but now we have Mongo 8.0 support.
**Solution:**
Change tests to use Mongo 8.0 image.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: https://perconadev.atlassian.net/browse/K8SPSMDB-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1224: Update tests to Mongo 8.0

- Makefile
- config/crd/bases/psmdb.percona.com_perconaservermongodbs.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/default-cr/run
- e2e-tests/preinit-updates/conf/some-name.yml
- e2e-tests/preinit-updates/run
- e2e-tests/run-pr.csv
- e2e-tests/run-release.csv
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/apis/psmdb/v1/zz_generated.deepcopy.go
- pkg/controller/perconaservermongodb/finalizers.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/psmdb_controller.go
- pkg/controller/perconaservermongodb/smart.go
- pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-1249](https://badgen.net/badge/JIRA/K8SPSMDB-1249/green)](https://jira.percona.com/browse/K8SPSMDB-1249) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Operator can not finish smart update if update is triggered before replset is initialized.
Steps to reproduce:
1. Create a new cluster.
2. Immediately patch cluster to trigger smart update.
3. Operator detects the change but waits until all pods are up to start smart update.
4. Wait until all pods are up and running.
5. Operator initializes replset in `cluster1-cfg-0` and creates users …
> K8SPSMDB-1249: Fix smart update for pods that are not member of replset

- Jenkinsfile
[![CLOUD-869](https://badgen.net/badge/JIRA/CLOUD-869/green)](https://jira.percona.com/browse/CLOUD-869) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-869]: https://perconadev.atlassian.net/browse/CLOUD-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
> CLOUD-869 invert the logic and make it an early return(moving to top), reducing nested ifs.

- e2e-tests/pitr-sharded/conf/eks-some-name-rs0.yml
- e2e-tests/pitr-sharded/run
---
**Problem:**
Test fails because of access denied in S3 bucket.
**Cause:**
We [removed](https://github.com/Percona-Lab/jenkins-pipelines/commit/f66eda69b9cb82ef7bda53ab0328609e7a9571ac) the option: `- arn:aws:iam::aws:policy/AmazonS3FullAccess` when creating the EKS cluster because of the [IRSA test](https://github.com/percona/percona-server-mongodb-operator/blob/main/e2e-tests/demand-backup-eks-cred …
> K8SPSMDB-1224 add credentialsSecret to S3 configuration and apply storage secrets in run script

- e2e-tests/default-cr/run
---
**Problem:**
default-cr test was missing the namespace to install the operator when running in CW.
**Solution:**
Add namespace to kubectl command.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: https://perconadev.atlassian.net/browse/K8SPSMDB-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1224 - Fix default-cr test in CW

- e2e-tests/upgrade/run
---
**Problem:**
`upgrade` test fails very often, because it needs to wait a little bit before listing contects of S3 bucket.
**Cause:**
**Solution:**
I added retry just like in [upgrade-sharded](https://github.com/percona/percona-server-mongodb-operator/blob/92cb7e66d06120ca6c25c060fcf2b6f21b5aa2b5/e2e-tests/upgrade-sharded/run#L266) instead of just adding a "dumb" `sleep <seconds>` and it should be more stable now
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-1224 Add retry mechanism for AWS CLI command in upgrade run script

- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-disabled-oc.yml
- e2e-tests/expose-sharded/compare/statefulset_some-name-rs0-sharding-enabled-oc.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-cfg-1170-oc.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-cfg-1180-oc.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-rs0-1170-oc.yml
- e2e-tests/upgrade-consistency-sharded-tls/compare/statefulset_some-name-rs0-1180-oc.yml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: https://perconadev.atlassian.net/browse/K8SPSMDB-1224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> K8SPSMDB-1224 - Fix Openshift Tests

- e2e-tests/demand-backup-fs/run
---
**Problem:**
demand-backup-fs test fails on Openshift due to privileged: true. 
**Cause:**
**Solution:**
Skip test on openshift for now. [Task](https://perconadev.atlassian.net/browse/K8SPSMDB-1262) to add support.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: …
> K8SPSMDB-1224: skip demand-backup-fs test on Openshift

- e2e-tests/upgrade-sharded/run
- e2e-tests/upgrade/run
---
**Problem:**
`upgrade-sharded` test fails very often, because it needs to wait a little bit before listing contects of S3 bucket.
**Solution:**
I increasing retry count. Passes [here](https://cloud.cd.percona.com/view/PSMDB/job/psmdbo-gke-2/39/).
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1224]: https://perconadev.atlassian.net/browse/K8SPSMDB-1224?atlOrigin=eyJpIj …
> K8SPSMDB-1224 fix upgrade-sharded test by increasing retry count

- Jenkinsfile
[![K8SPSMDB-1291](https://badgen.net/badge/JIRA/K8SPSMDB-1291/green)](https://jira.percona.com/browse/K8SPSMDB-1291) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1291]: https://perconadev.atlassian.net/browse/K8SPSMDB-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
> K8SPSMDB-1291 Jenkinsfile cluster-version set to 1.29 from 1.28

- pkg/controller/perconaservermongodb/version.go
- pkg/controller/perconaservermongodb/version_test.go
[![K8SPSMDB-1245](https://badgen.net/badge/JIRA/K8SPSMDB-1245/green)](https://jira.percona.com/browse/K8SPSMDB-1245) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
…a-separated namespaces
---
**Problem:**
Telemetry ClusterWideEnabled not handling multiple comma-separated namespaces
**Cause:**
**Solution:**
Update value for ClusterWideEnabled
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1245]: https://perconadev.atlassian.net/browse/K8SPSMDB-1245?atlOrigin=eyJpIjoiNWR …
> K8SPSMDB-1245 Telemetry ClusterWideEnabled not handling multiple comma-separated namespaces

- config/crd/bases/psmdb.percona.com_perconaservermongodbs.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/psmdb/backup/pbm.go
- pkg/psmdb/backup/pbm_test.go
- pkg/psmdb/backup/testdata/cr-with-pbm-config.yaml
[![K8SPSMDB-1097](https://badgen.net/badge/JIRA/K8SPSMDB-1097/green)](https://jira.percona.com/browse/K8SPSMDB-1097) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Optimize PBM’s resource usage to achieve faster backups without negatively affecting MongoDB’s performance. 
**Cause:**
**Solution:**
Adding the field NumParallelCollections to pbm configuration.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1097]: …
> K8SPSMDB-1097 add NumParallelCollections to CR

- e2e-tests/custom-replset-name/conf/some-name.yml
- pkg/apis/psmdb/v1/psmdb_defaults.go
- pkg/controller/perconaservermongodb/pbm.go
[![K8SPSMDB-1219](https://badgen.net/badge/JIRA/K8SPSMDB-1219/green)](https://jira.percona.com/browse/K8SPSMDB-1219) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Only check main storage stuff if crVersion is >= 1.20
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1219]: https://perconadev.atlassian.net/browse/K8SPSMDB-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1219: Main storage checks should only happen in versions >= 1.20

- pkg/controller/perconaservermongodb/pbm.go
- pkg/controller/perconaservermongodb/pbm_test.go
- pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1306](https://badgen.net/badge/JIRA/K8SPSMDB-1306/green)](https://jira.percona.com/browse/K8SPSMDB-1306) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
These changes also fix mistakenly starting resync when there's no need.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1306]: https://perconadev.atlassian.net/browse/K8SPSMDB-1306?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1306: Fix panic if user has a custom PBM config without timeouts

- config/crd/bases/psmdb.percona.com_perconaservermongodbs.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/psmdb/pmm.go
[![K8SPSMDB-1316](https://badgen.net/badge/JIRA/K8SPSMDB-1316/green)](https://jira.percona.com/browse/K8SPSMDB-1316) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Operator uses cr.Name as cluster name in PMM and users have no way to override it.
**Solution:**
Add `customClusterName` field.
Helm chart PR: https://github.com/percona/percona-helm-charts/pull/524
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1316]: https://perconadev.atlassian.net/browse/K8SPSMDB-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhY …
> K8SPSMDB-1316: Allow customizing cluster name in PMM

- config/crd/bases/psmdb.percona.com_perconaservermongodbs.yaml
- deploy/bundle.yaml
- deploy/cr.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/psmdb_types.go
- pkg/apis/psmdb/v1/zz_generated.deepcopy.go
- pkg/psmdb/mongos.go
- pkg/psmdb/mongos_test.go
- pkg/psmdb/service.go
- pkg/psmdb/service_test.go
[![K8SPSMDB-1329](https://badgen.net/badge/JIRA/K8SPSMDB-1329/green)](https://jira.percona.com/browse/K8SPSMDB-1329) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Support [loadBalancerClass](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class) in expose sections.
Helm chart PR: https://github.com/percona/percona-helm-charts/pull/525
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1329]: https://perconadev.atlassian.net/browse/K8SPSMDB-1329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …
> K8SPSMDB-1329: Add loadBalancerClass

- go.mod
- go.sum
[![K8SPSMDB-1341](https://badgen.net/badge/JIRA/K8SPSMDB-1341/green)](https://jira.percona.com/browse/K8SPSMDB-1341) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Bump PBM go module to v2.9.1.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1341]: https://perconadev.atlassian.net/browse/K8SPSMDB-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1341: Bump PBM to v2.9.1

- pkg/controller/perconaservermongodb/custom_users.go
- pkg/controller/perconaservermongodb/custom_users_test.go
[![K8SPSMDB-1347](https://badgen.net/badge/JIRA/K8SPSMDB-1347/green)](https://jira.percona.com/browse/K8SPSMDB-1347) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
logs in PSMDB for each additional user we try to create with automatically generated passwords.
```
2025-04-15T14:47:50.313Z	ERROR	failed to get user secret	{"controller": "psmdb-controller", "controllerGroup": "psmdb.percona.com", "controllerKind": "PerconaServerMongoDB", "PerconaServerMongoDB": {"name":"my-cluster-name","namespace":"test4"}, "namespace": "test4", "name": …
```
> K8SPSMDB-1347 When password does not exist, properly update the secret and set the boolean to true

- e2e-tests/custom-replset-name/conf/some-name.yml
- e2e-tests/functions
- e2e-tests/init-deploy/compare/clusterAdmin-60.json
- e2e-tests/init-deploy/compare/clusterAdmin-70.json
- e2e-tests/init-deploy/compare/clusterAdmin-80.json
- e2e-tests/init-deploy/compare/clusterMonitor-60.json
- e2e-tests/init-deploy/compare/clusterMonitor-70.json
- e2e-tests/init-deploy/compare/clusterMonitor-80.json
- e2e-tests/version-service/conf/version-service-major-rs0.yml
- e2e-tests/version-service/run
- pkg/controller/perconaservermongodb/connections_test.go
- pkg/controller/perconaservermongodb/custom_users.go
- pkg/controller/perconaservermongodb/mgo.go
- pkg/controller/perconaservermongodb/mgo_test.go
- pkg/psmdb/mongo/fake/client.go
- pkg/psmdb/mongo/models.go
- pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-1325](https://badgen.net/badge/JIRA/K8SPSMDB-1325/green)](https://jira.percona.com/browse/K8SPSMDB-1325) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
This PR fixes two problems:
1. MongoDB 8.0 added a new role called `directShardOperation`. Without this role, users won't be able to perform anything by directly connecting to shards in a sharded cluster.
2. When you try to remove a shard, operator infinitely prints `draining ongoing` in logs but shard is not removed and it's impossible to understand why the operation is stuck without …
> K8SPSMDB-1325: Add directShardOperation role to clusterAdmin and clusterMonitor

- cmd/manager/main.go
- pkg/mcs/register.go
[![K8SPSMDB-1294](https://badgen.net/badge/JIRA/K8SPSMDB-1294/green)](https://jira.percona.com/browse/K8SPSMDB-1294) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Operator registers MCS APIs using `net.gke.io/v1alpha1` even though `kubectl api-resources` show `net.gke.io/v1`.
**Solution:**
Looking at the [kubectl code](https://github.com/kubernetes/kubernetes/blob/afc57a752110ac0633ff5df896ebe02ee1b19ec5/staging/src/k8s.io/kubectl/pkg/cmd/apiresources/apiresources.go#L168) shows that it uses `DiscoveryClient.ServerPreferredResources` instead of …
> K8SPSMDB-1294: Use server's preferred version of MCS APIs

- deploy/cr.yaml
- pkg/controller/perconaservermongodb/backup.go
[![K8SPSMDB-1237](https://badgen.net/badge/JIRA/K8SPSMDB-1237/green)](https://jira.percona.com/browse/K8SPSMDB-1237) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://perconadev.atlassian.net/browse/K8SPSMDB-1237
---
This PR fixes the implementation of commit https://github.com/percona/percona-server-mongodb-operator/pull/1836#discussion_r1981247701. It was intended to disable the `.spec.backup.tasks.[].keep` option for `incremental` backups, but instead it was implemented in a part of the code that is no longer used.
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-1237: fix .keep for incremental backups

- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0-oc.yml
- e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0.yml
- e2e-tests/demand-backup-eks-credentials-irsa/compare/statefulset_some-name-rs0.yml
[![K8SPSMDB-1265](https://badgen.net/badge/JIRA/K8SPSMDB-1265/green)](https://jira.percona.com/browse/K8SPSMDB-1265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
`PBM_MONGODB_URI` was outdated
**Solution:**
Change it to correct one
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1265]: https://perconadev.atlassian.net/browse/K8SPSMDB-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1265: Fix compare files with correct PBM_MONGODB_URI

- e2e-tests/init-deploy/compare/backup-80.json
- e2e-tests/rs-shard-migration/compare/statefulset_some-name-rs0.yml
- e2e-tests/rs-shard-migration/conf/backup-minio.yml
- e2e-tests/rs-shard-migration/conf/some-name.yml
- e2e-tests/rs-shard-migration/run
- pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-1366](https://badgen.net/badge/JIRA/K8SPSMDB-1366/green)](https://jira.percona.com/browse/K8SPSMDB-1366) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Operator doesn't understand that it needs to reconfigure PBM after sharding status is toggled.
**Cause:**
If sharding is enabled PBM stores its configuration and metadata in config server replset. If sharding is disabled, config server is deleted and PBM configuration is gone. 
Operator stores PBM config hash in `status.backupConfigHash` and since nothing changed in the config, it …
> K8SPSMDB-1366: Fix reconfiguring PBM after sharding is toggled

- e2e-tests/rs-shard-migration/compare/statefulset_some-name-rs0-oc.yml
[![K8SPSMDB-1265](https://badgen.net/badge/JIRA/K8SPSMDB-1265/green)](https://jira.percona.com/browse/K8SPSMDB-1265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Openshift compare file for rs-shard-migration was not updated.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
> K8SPSMDB-1265: update oc compare for rs-shard-migration

- e2e-tests/demand-backup-incremental-sharded/run
- e2e-tests/demand-backup-sharded/run
- e2e-tests/demand-backup/run
- e2e-tests/functions
- e2e-tests/pitr-physical/run
- e2e-tests/rs-shard-migration/compare/statefulset_some-name-rs0-oc.yml
[![K8SPSMDB-1265](https://badgen.net/badge/JIRA/K8SPSMDB-1265/green)](https://jira.percona.com/browse/K8SPSMDB-1265) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Hi. The following problems should be fixed:
1) From time to time `wait_restore()` does not detect that object has `requested` state and fails, although eventually restore gets ready state.
2) The presence of the backup in minio storage fails in `demand-backup-sharded`. 
3) The backups are not deleted from the storage after tests as a result resync requires a lot of time and tests run …
> K8SPSMDB-1265: clean up basmdb-backup and use kubectl wait for wait_restore

- pkg/controller/perconaservermongodbrestore/physical.go
[![K8SPSMDB-1371](https://badgen.net/badge/JIRA/K8SPSMDB-1371/green)](https://jira.percona.com/browse/K8SPSMDB-1371) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Operator panics if user tries to run a physical restore with `pitr.type: latest` and there are no oplogs are in PBM metadata.
**Solution:**
Add a sanity check.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1371]: https://perconadev.atlassian.net/browse/K8SPSMDB-1371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
> K8SPSMDB-1371: Prevent panic if no oplogs are in PBM metadata

- e2e-tests/demand-backup-incremental-sharded/run
- e2e-tests/demand-backup-incremental/run
- e2e-tests/demand-backup-physical-sharded/run
- e2e-tests/demand-backup-physical/run
- e2e-tests/functions
- pkg/apis/psmdb/v1/perconaservermongodbbackup_types.go
- pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
- pkg/k8s/lease.go
- pkg/k8s/lease_test.go
- pkg/naming/backup.go
- pkg/naming/naming.go
- pkg/psmdb/backup/backup.go
[![K8SPSMDB-1378](https://badgen.net/badge/JIRA/K8SPSMDB-1378/green)](https://jira.percona.com/browse/K8SPSMDB-1378) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
With these changes, psmdb-backup controller will create a lease object for a running backup and no other backup will be able to start until this lease is released (deleted). Lock is released when backup succeeds or fails.
We introduce a new finalizer called `internal.percona.com/release-lock` for PerconaServerMongoDBBackup objects. Operator will automatically add this finalizer to each new backup …
>  K8SPSMDB-1378: Prevent parallel backups

- e2e-tests/scheduled-backup/run
[![K8SPSMDB-1292](https://badgen.net/badge/JIRA/K8SPSMDB-1292/green)](https://jira.percona.com/browse/K8SPSMDB-1292) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Noticed that locally, when running tests that are utilizing the function `check_backup_count `, we have errors like the following:
This causes the assertion to fail because the 2 strings are not matching.
**Cause:**
**Solution:**
strip all the heading and trailing spaces from the count string.
Test:
```
count="      1 …
```
> K8SPSMDB-1292 Trim spaces from count in check_backup_count function for e2e tests

- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-cfg-oc.yml
- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-cfg.yml
- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-mongos-oc.yml
- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-mongos.yml
- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-rs0-oc.yml
- e2e-tests/monitoring-pmm3/compare/statefulset_monitoring-pmm3-rs0.yml
- pkg/psmdb/pmm/pmm.go
- pkg/psmdb/pmm/pmm_test.go
[![K8SPSMDB-1268](https://badgen.net/badge/JIRA/K8SPSMDB-1268/green)](https://jira.percona.com/browse/K8SPSMDB-1268) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Introducing this work: https://github.com/percona/percona-server-mongodb-operator/pull/1924, but for PMM3, which is introduced on the PR by the branch that is the base for this current PR.
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests** …
> K8SPSMDB-1268 && K8SPSMDB-1297 add data dir for pmm3

- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0-oc.yml
- e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0.yml
- pkg/psmdb/const.go
- pkg/psmdb/init.go
- pkg/psmdb/pmm.go
- pkg/psmdb/statefulset.go
[![K8SPSMDB-1297](https://badgen.net/badge/JIRA/K8SPSMDB-1297/green)](https://jira.percona.com/browse/K8SPSMDB-1297) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
datadir mountpoint is not access by node_exporter because it is not exposed in the /proc 
**Cause:**
**Solution:**
Expose the datadir to the sidecar so the node_exporter can gather the metrics.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1297]: …
> K8SPSMDB-1297 add data dir to proc

- e2e-tests/functions
[![K8SPSMDB-1443](https://badgen.net/badge/JIRA/K8SPSMDB-1443/green)](https://jira.percona.com/browse/K8SPSMDB-1443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Solution:**
PMM 2 is EOL. Dev Docker image can be broken for different reasons. It is better to use the latest stable release version for our tests.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1443]: https://perconadev.atlassian.net/browse/K8SPSMDB-1443?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> K8SPSMDB-1443 use the latest released ver of PMM2

- config/crd/bases/psmdb.percona.com_perconaservermongodbrestores.yaml
- deploy/bundle.yaml
- deploy/crd.yaml
- deploy/cw-bundle.yaml
- e2e-tests/version-service/conf/crd.yaml
- pkg/apis/psmdb/v1/perconaservermongodbrestore_types.go
- pkg/controller/perconaservermongodbrestore/psmdb_restore_controller_test.go
[![K8SPSMDB-1339](https://badgen.net/badge/JIRA/K8SPSMDB-1339/green)](https://jira.percona.com/browse/K8SPSMDB-1339) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
The existing validation for the pitr date does allow datetimes that are not possible. With this PR we are making the validation more restrictive so that it is following this format: `(MM: 01-12, DD: 01-31, HH: 00-23, MM/SS: 00-59)`
**Cause:**
**Solution:**
*Short explanation of the solution we are providing with this …
> K8SPSMDB-1339 make pitr date validation more restrictive

- pkg/psmdb/mongo/mongo.go
- pkg/psmdb/mongo/mongo_test.go
[![K8SPSMDB-1480](https://badgen.net/badge/JIRA/K8SPSMDB-1480/green)](https://jira.percona.com/browse/K8SPSMDB-1480) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
This PR improves our vote distribution algorithm to ensure operator adheres the max voting members limit.
There were multiple problems in the previous implementation. For example:
- When adding hidden members MaxVotingMembers rule was ignored.
- If MaxVotingMembers limit is exceeded when adding an arbiter, operator blindly removed votes from the last member without checking if that member had votes …
> K8SPSMDB-1480: Fix vote distribution algorithm
