Makefile, pkg/apis/psmdb/v1alpha1/types.go, pkg/stub/container.go, pkg/stub/handler.go, pkg/stub/handler_test.go, pkg/stub/psmdb_test.go, pkg/stub/replset.go, pkg/stub/util.go, pkg/stub/util_test.go
1. Add tests for pkg/stub/psmdb.go
1. Remove needless getPSMDBUri() func+api Status struct-var
1. Makefile change to only run unit tests on logic in pkg/stub, pkg/api/* and pkg/sdk/* don't need tests
=> Test pkg/stub/psmdb.go, remove getPSMDBUri() func+status var

pkg/stub/handler.go, pkg/stub/psmdb.go, pkg/stub/replset.go
This reverts commit cb32d258b2503cd451386127265457450dee374d.
=> Revert mistaken "Add fmt lines for logging" commit push

deploy/cr.yaml
These changes are on branch: 'release-0.1.0' but not 'master'. Merging so they're not lost next release.
=> Merge deploy/cr.yaml commits to release-0.1.0

Makefile
operator-sdk must match the version the operator was built on
=> Check for operator-sdk 0.0.7 when running 'generate k8s'

deploy/cr.yaml
the was a minor mistake in cr.yaml
=> fix on to enabled in cr.yaml

Gopkg.lock, Gopkg.toml, vendor/github.com/percona/mongodb-orchestration-tools/controller/replset/initiator.go
Update for https://github.com/percona/mongodb-orchestration-tools/pull/226
=> CLOUD-46: Skip replset initiation if already initiated

Gopkg.lock, Gopkg.toml, deploy/cr.yaml, pkg/stub/handler.go, pkg/stub/handler_test.go, vendor/github.com/percona/mongodb-orchestration-tools/controller/replset/initiator.go, vendor/github.com/percona/mongodb-orchestration-tools/glide.lock, vendor/github.com/percona/mongodb-orchestration-tools/pkg/pod/k8s/pods.go, vendor/github.com/percona/mongodb-orchestration-tools/pkg/pod/k8s/task.go
1. Support many PSMDB CRs.
1. Merge many-CR support from mongodb-orchestration-tools.
1. Merge of CLOUD-89 fix by @heartwilltell.
=> CLOUD-87: Support many PSMDB CRs

pkg/stub/extservice.go
adjust retry count and timeouts for getExtServices and updateExtService funcs
=> adjust retry count and timeouts

pkg/stub/backup/agent.go
If there is set no CredentialsSecret for S3 backup storage, it cause panic on sdk.client.Get(). With empty object name k8s returns object list instead of an object.
=> CLOUD-132: Fix no storage secrets crash

internal/mongod/container.go, pkg/stub/arbiter.go, pkg/stub/replset.go
Also remove arbiter's statefulSet when it switched off
And some clean up in the containers functions
=> Create no PVC for arbiter

source/backups.rst, source/kubernetes.rst, source/monitoring.rst, source/openshift.rst, source/private.rst, source/scaling.rst, source/users.rst
Implementing doc update after verification
=> CLOUD-310 Documentation update

e2e-tests/arbiter/run, e2e-tests/demand-backup/run, e2e-tests/functions, e2e-tests/init-deploy/run, e2e-tests/limits/run, e2e-tests/monitoring/run, e2e-tests/one-pod/run, e2e-tests/operator-self-healing/run, e2e-tests/scaling/run, e2e-tests/scheduled-backup/run, e2e-tests/self-healing/run, e2e-tests/service-per-pod/run, e2e-tests/storage/run, e2e-tests/upgrade/run
In order to make tests more stable, kubectl repeat on fail
action has been added
=> CLOUD-323 Kubectl error handling

e2e-tests/service-per-pod/run
mongo cluster startup takes more than we expect
=> Service-per-pod test fix

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/status.go
Inspired by
https://github.com/kubernetes/community/blob/57946ce0aef2e7f3540f37cc598fb8623704f6ed/contributors/devel/sig-architecture/api-conventions.md
https://github.com/kubernetes/community/blob/79748734e6225769eb5186d0496adeb9f64789cf/contributors/design-proposals/apps/statefulset-update.md
https://github.com/kubernetes/community/blob/712590c108bd4533b80e8f2753cadaa617d9bdf2/contributors/devel/sig-api-machinery/controllers.md
https://thenewstack.io/kubernetes-deployments-work/
=> K8SPSMDB-175 Add observedGeneration field

pkg/psmdb/backup/job.go
create the backup cr with curl instead of kubectl
=> K8SPSMDB-190 create the backup cr with curl

source/conf.py, source/debug.rst, source/index.rst, source/update.rst
[![SPSMDB-202](https://badgen.net/badge/JIRA/SPSMDB-202/green)](https://jira.percona.com/browse/SPSMDB-202)
=> K8SPSMDB-202 port debug images and apiversion fix from pxc docs

build/ps-entry.sh
[![K8SPSMDB-207](https://badgen.net/badge/JIRA/K8SPSMDB-207/green)](https://jira.percona.com/browse/K8SPSMDB-207)
=> K8SPSMDB-207: add generic ps-entry.sh

source/backups.rst, source/conf.py, source/debug.rst, source/index.rst, source/update.rst
[![K8SPSMDB-210](https://badgen.net/badge/JIRA/K8SPSMDB-210/green)](https://jira.percona.com/browse/K8SPSMDB-210)
=> K8SPSMDB-210 reflect pbm changes - remove coordinator, etc.

source/kubernetes.rst, source/minikube.rst, source/openshift.rst
[![K8SPSMDB-213](https://badgen.net/badge/JIRA/K8SPSMDB-213/green)](https://jira.percona.com/browse/K8SPSMDB-213)
=> K8SPSMDB-213 use v symbol in version tag

e2e-tests/self-healing/run
[![K8SPSMDB-69](https://badgen.net/badge/JIRA/K8SPSMDB-69/green)](https://jira.percona.com/browse/K8SPSMDB-69)
=> K8SPSMDB-69 Enable pbm for test

source/monitoring.rst
[![CLOUD-403](https://badgen.net/badge/JIRA/CLOUD-403/green)](https://jira.percona.com/browse/CLOUD-403)
=> CLOUD-403 update pmm installation instructions

source/operator.rst, source/scaling.rst
[![K8SPXC-320](https://badgen.net/badge/JIRA/K8SPXC-320/green)](https://jira.percona.com/browse/K8SPXC-320)
=> K8SPXC-320 improve link to options; try using a single-option link

e2e-tests/functions
[![CLOUD-556](https://badgen.net/badge/JIRA/CLOUD-556/green)](https://jira.percona.com/browse/CLOUD-556)
=> CLOUD-556 Remove extra fields in 1.17 k8s

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/status.go, pkg/controller/perconaservermongodb/version.go, pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
[![K8SPSMDB-198](https://badgen.net/badge/JIRA/K8SPSMDB-198/green)](https://jira.percona.com/browse/K8SPSMDB-198)
=> K8SPSMDB-198 Rename MongoStatus back to Status

pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-242](https://badgen.net/badge/JIRA/K8SPSMDB-242/green)](https://jira.percona.com/browse/K8SPSMDB-242)
=> K8SPSMDB-242: Ignore network error after doing step down

pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-244](https://badgen.net/badge/JIRA/K8SPSMDB-244/green)](https://jira.percona.com/browse/K8SPSMDB-244)
=> K8SPSMDB-244: Add missed unlock in reconcile loop

source/backups.rst
[![K8SPSMDB-229](https://badgen.net/badge/JIRA/K8SPSMDB-229/green)](https://jira.percona.com/browse/K8SPSMDB-229)
=> K8SPSMDB-229 mention secret keys are base64 encoded

pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-243](https://badgen.net/badge/JIRA/K8SPSMDB-243/green)](https://jira.percona.com/browse/K8SPSMDB-243)
=> K8SPSMDB-243: Set defaults after getting updated CR.

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/version.go, pkg/controller/perconaservermongodb/vs.go
[![CLOUD-566](https://badgen.net/badge/JIRA/CLOUD-566/green)](https://jira.percona.com/browse/CLOUD-566)
----
#
=> CLOUD-566: Fix issue with cached version service URL

source/index.rst
[![CLOUD-560](https://badgen.net/badge/JIRA/CLOUD-560/green)](https://jira.percona.com/browse/CLOUD-560)
=> CLOUD-560 - don't mention master term

source/System-Requirements.rst
[![CLOUD-565](https://badgen.net/badge/JIRA/CLOUD-565/green)](https://jira.percona.com/browse/CLOUD-565)
=> CLOUD-565 Add VMWare Tanzu to the list of platforms

e2e-tests/demand-backup/run, e2e-tests/functions, e2e-tests/users/conf/backup-aws-s3.yml, e2e-tests/users/conf/some-name-rs0.yml, e2e-tests/users/run
[![K8SPSMDB-237](https://badgen.net/badge/JIRA/K8SPSMDB-237/green)](https://jira.percona.com/browse/K8SPSMDB-237)
=> K8SPSMDB-237 Add test cases

source/update.rst
[![K8SPSMDB-239](https://badgen.net/badge/JIRA/K8SPSMDB-239/green)](https://jira.percona.com/browse/K8SPSMDB-239)
=> K8SPSMDB-239 update the upgrade page

e2e-tests/limits/run
[![K8SPSMDB-234](https://badgen.net/badge/JIRA/K8SPSMDB-234/green)](https://jira.percona.com/browse/K8SPSMDB-234)
=> K8SPSMDB-234 limits test should not wait for cluster readyness

deploy/bundle.yaml, deploy/cr.yaml, deploy/operator.yaml
[![K8SPSMDB-256](https://badgen.net/badge/JIRA/K8SPSMDB-256/green)](https://jira.percona.com/browse/K8SPSMDB-256)
=> K8SPSMDB-256 - Update for release 1.5.0

source/api.rst
[![CLOUD-526](https://badgen.net/badge/JIRA/CLOUD-526/green)](https://jira.percona.com/browse/CLOUD-526)
=> fix width of foldable sections

e2e-tests/demand-backup/run
[![K8SPSMDB-234](https://badgen.net/badge/JIRA/K8SPSMDB-234/green)](https://jira.percona.com/browse/K8SPSMDB-234)
=> K8SPSMDB-234 Fix for backup test on minikube

source/users.rst
[![K8SPSMDB-233](https://badgen.net/badge/JIRA/K8SPSMDB-233/green)](https://jira.percona.com/browse/K8SPSMDB-233)
=> mention the existence of the internal users secrets

source/api.rst, source/custom-registry.rst, source/operator.rst
[![K8SPSMDB-218](https://badgen.net/badge/JIRA/K8SPSMDB-218/green)](https://jira.percona.com/browse/K8SPSMDB-218)
=> K8SPSMDB-218 update few lost custom resoucer options

source/helm.rst
[![K8SPSMDB-218](https://badgen.net/badge/JIRA/K8SPSMDB-218/green)](https://jira.percona.com/browse/K8SPSMDB-218)
=> K8SPSMDB-218 update helm chart doc

source/helm.rst
[![K8SPSMDB-218](https://badgen.net/badge/JIRA/K8SPSMDB-218/green)](https://jira.percona.com/browse/K8SPSMDB-218)
=> K8SPSMDB-218 make chart doc Helm 2.x compatible

source/RN/Kubernetes-Operator-for-PSMONGODB-RN1.5.0.rst, source/conf.py
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1)
=> fix acronyms and pdf title

e2e-tests/functions
Merge release branch for v1.5.0 to master.
=> Fix wait_backup_agent func in e2e-tests for PBM 1.3.x

deploy/crd.yaml, e2e-tests/functions, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-160.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-160-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-160.yml, e2e-tests/upgrade-consistency/run, version/version.go
[![K8SPSMDB-256](https://badgen.net/badge/JIRA/K8SPSMDB-256/green)](https://jira.percona.com/browse/K8SPSMDB-256)
=> K8SPSMDB-256 - Increment versions after 1.5.0 release

build/ps-entry.sh
[![PSMDB-686](https://badgen.net/badge/JIRA/PSMDB-686/green)](https://jira.percona.com/browse/PSMDB-686)
=> PSMDB-686 add psmdb v4.4 support to ps-entry.sh

source/System-Requirements.rst, source/encryption.rst
[![K8SPXC-449](https://badgen.net/badge/JIRA/K8SPXC-449/green)](https://jira.percona.com/browse/K8SPXC-449)
=> K8SPXC-449 update minikube version

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-261](https://badgen.net/badge/JIRA/K8SPSMDB-261/green)](https://jira.percona.com/browse/K8SPSMDB-261)
=> K8SPSMDB-261 fix pause

e2e-tests/users/run, pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-269](https://badgen.net/badge/JIRA/K8SPSMDB-269/green)](https://jira.percona.com/browse/K8SPSMDB-269)
=> K8SPSMDB-269: fix users e2e test

source/TLS.rst
[![K8SPSMDB-268](https://badgen.net/badge/JIRA/K8SPSMDB-268/green)](https://jira.percona.com/browse/K8SPSMDB-268)
=> K8SPSMDB-268 update cert-manager version

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-289](https://badgen.net/badge/JIRA/K8SPSMDB-289/green)](https://jira.percona.com/browse/K8SPSMDB-289)
=> K8SPSMDB-289 - make it possible to specify custom init image

source/TLS.rst
[![K8SPSMDB-211](https://badgen.net/badge/JIRA/K8SPSMDB-211/green)](https://jira.percona.com/browse/K8SPSMDB-211)
=> K8SPSMDB-211 minor formatting improvement

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/mongos.go
[![K8SPSMDB-293](https://badgen.net/badge/JIRA/K8SPSMDB-293/green)](https://jira.percona.com/browse/K8SPSMDB-293)
=> K8SPSMDB-293: Use same version of init image as cr version

pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-296](https://badgen.net/badge/JIRA/K8SPSMDB-296/green)](https://jira.percona.com/browse/K8SPSMDB-296)
=> K8SPSMDB-296 fix sfs annotations

deploy/cr.yaml
[![K8SPSMDB-121](https://badgen.net/badge/JIRA/K8SPSMDB-121/green)](https://jira.percona.com/browse/K8SPSMDB-121)
=> K8SPSMDB-121 - Add antiAffinityTopologyKey for mongos and fix indentation for auditLog

deploy/cr.yaml
[![K8SPSMDB-312](https://badgen.net/badge/JIRA/K8SPSMDB-312/green)](https://jira.percona.com/browse/K8SPSMDB-312)
Reverting the change I did before here:
https://github.com/percona/percona-server-mongodb-operator/commit/75e67b895e693dddb4d8b5fb2ae1ba1c71329296
https://github.com/percona/percona-server-mongodb-operator/commit/f3d6cf308496a4b5d3b1e1be178216a4e3bbb05b
=> K8SPSMDB-312 - comment antiAffinity for mongos

deploy/cr.yaml
[![K8SPSMDB-311](https://badgen.net/badge/JIRA/K8SPSMDB-311/green)](https://jira.percona.com/browse/K8SPSMDB-311)
=> K8SPSMDB-311: Remove 'operationProfiling' section from deploy/cr.yaml for mongos

source/operator.rst
[![K8SPSMDB-218](https://badgen.net/badge/JIRA/K8SPSMDB-218/green)](https://jira.percona.com/browse/K8SPSMDB-218)
=> K8SPSMDB-218 update resource options

e2e-tests/arbiter/compare/statefulset_arbiter-rs0-arbiter-oc.yml, e2e-tests/arbiter/compare/statefulset_arbiter-rs0-arbiter.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-cfg.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-increased.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-increased.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-increased.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0.yml, e2e-tests/one-pod/compare/statefulset_one-pod-rs0-oc.yml, e2e-tests/one-pod/compare/statefulset_one-pod-rs0.yml, e2e-tests/upgrade/compare/statefulset_upgrade-rs0-oc.yml, e2e-tests/upgrade/compare/statefulset_upgrade-rs0.yml, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/mongos.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-312](https://badgen.net/badge/JIRA/K8SPSMDB-312/green)](https://jira.percona.com/browse/K8SPSMDB-312)
Make same component or pods from same ReplicaSet to run on different hosts.
=> K8SPSMDB-312: Fix antiAffinity for mongos

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-317](https://badgen.net/badge/JIRA/K8SPSMDB-317/green)](https://jira.percona.com/browse/K8SPSMDB-317)
=> K8SPSMDB-317: Disable arbiter for config replset

pkg/controller/perconaservermongodb/external_service.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-316](https://badgen.net/badge/JIRA/K8SPSMDB-316/green)](https://jira.percona.com/browse/K8SPSMDB-316)
=> K8SPSMDB-316: Fix config service removing

deploy/cr.yaml, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/users.go
[![K8SPSMDB-303](https://badgen.net/badge/JIRA/K8SPSMDB-303/green)](https://jira.percona.com/browse/K8SPSMDB-303)
=> K8SPSMDB-303 Manage users with sharded cluster

deploy/cr.yaml, pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-314](https://badgen.net/badge/JIRA/K8SPSMDB-314/green)](https://jira.percona.com/browse/K8SPSMDB-314)
=> K8SPSMDB-314: Fix pause for mongos

deploy/cr.yaml, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/mongos.go
[![K8SPSMDB-324](https://badgen.net/badge/JIRA/K8SPSMDB-324/green)](https://jira.percona.com/browse/K8SPSMDB-324)
=> K8SPSMDB-324: Add disruption budget for mongos

source/faq.rst, source/index.rst
[![K8SPSMDB-286](https://badgen.net/badge/JIRA/K8SPSMDB-286/green)](https://jira.percona.com/browse/K8SPSMDB-286)
=> K8SPSMDB-286 create FAQ - initial version

source/custom-registry.rst, source/images.rst, source/index.rst
[![K8SPSMDB-298](https://badgen.net/badge/JIRA/K8SPSMDB-298/green)](https://jira.percona.com/browse/K8SPSMDB-298)
=> K8SPSMDB-298 make separate doc for image hashes

source/kubernetes.rst, source/openshift.rst, source/users.rst
[![K8SPSMDB-266](https://badgen.net/badge/JIRA/K8SPSMDB-266/green)](https://jira.percona.com/browse/K8SPSMDB-266)
Since we've switched to stringData secret format, related docs
should be updated.
=> K8SPSMDB-266 Doc update for secret update

go.mod, go.sum, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-322](https://badgen.net/badge/JIRA/K8SPSMDB-322/green)](https://jira.percona.com/browse/K8SPSMDB-322)
=> K8SPSMDB-322: Add mongos status

e2e-tests/monitoring-2-0/run
[![K8SPSMDB-315](https://badgen.net/badge/JIRA/K8SPSMDB-315/green)](https://jira.percona.com/browse/K8SPSMDB-315)
=> K8SPSMDB-315 add check of mongo config and mongos metrics

pkg/controller/perconaservermongodb/smart.go
[![K8SPSMDB-334](https://badgen.net/badge/JIRA/K8SPSMDB-334/green)](https://jira.percona.com/browse/K8SPSMDB-334)
=> K8SPSMDB-334: Fix migration from replica set to sharding

e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0.yml, pkg/psmdb/pmm.go
[![K8SPSMDB-315](https://badgen.net/badge/JIRA/K8SPSMDB-315/green)](https://jira.percona.com/browse/K8SPSMDB-315)
=> K8SPSMDB-315 Update annotation message

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-336](https://badgen.net/badge/JIRA/K8SPSMDB-336/green)](https://jira.percona.com/browse/K8SPSMDB-336)
=> K8SPSMDB-336: Take mongos status to account

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-337](https://badgen.net/badge/JIRA/K8SPSMDB-337/green)](https://jira.percona.com/browse/K8SPSMDB-337)
=> K8SPSMDB-337: Set default expose type

source/users.rst
[![K8SPSMDB-266](https://badgen.net/badge/JIRA/K8SPSMDB-266/green)](https://jira.percona.com/browse/K8SPSMDB-266)
=> K8SPSMDB-266 fix password change command in doc

e2e-tests/arbiter/compare/statefulset_arbiter-clusterip-rs0-arbiter-oc.yml, e2e-tests/arbiter/compare/statefulset_arbiter-rs0-arbiter-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/demand-backup/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/init-deploy/compare/statefulset_another-name-rs0-oc.yml, e2e-tests/init-deploy/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-oc.yml, e2e-tests/liveness/compare/statefulset_liveness-rs0-changed-oc.yml, e2e-tests/liveness/compare/statefulset_liveness-rs0-oc.yml, e2e-tests/one-pod/compare/statefulset_one-pod-rs0-oc.yml, e2e-tests/scheduled-backup/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_cluster-ip-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0-oc.yml, e2e-tests/storage/compare/statefulset_emptydir-rs0-oc.yml, e2e-tests/storage/compare/statefulset_hostpath-rs0-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-100-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-110-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-130-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-140-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-150-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-160-oc.yml, e2e-tests/upgrade-sharded/compare/statefulset_upgrade-sharded-cfg-oc.yml, e2e-tests/upgrade-sharded/compare/statefulset_upgrade-sharded-rs0-oc.yml, e2e-tests/upgrade/compare/statefulset_upgrade-rs0-oc.yml
=> K8SPSMDB-341 Fix typo for openshift

source/index.rst, source/operator.rst, source/pause.rst
[![K8SPSMDB-261](https://badgen.net/badge/JIRA/K8SPSMDB-261/green)](https://jira.percona.com/browse/K8SPSMDB-261)
=> K8SPSMDB-261-document-pause-resume

source/System-Requirements.rst, source/arbiter.rst, source/operator.rst
[![K8SPXC-299](https://badgen.net/badge/JIRA/K8SPXC-299/green)](https://jira.percona.com/browse/K8SPXC-299)
=> K8SPXC-299 clarify unsafe configurations

source/images.rst
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1)
=> update images hashes in doc for 1.6.0 release

e2e-tests/service-per-pod/run, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-100-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-110-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-130-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-140-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-150-oc.yml, e2e-tests/upgrade/compare/statefulset_upgrade-rs0-oc.yml
=> K8SPSMDB-341 Fixing some tests

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-345](https://badgen.net/badge/JIRA/K8SPSMDB-345/green)](https://jira.percona.com/browse/K8SPSMDB-345)
=> K8SPSMDB-345: Reset cluster role if sharding disabled

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-344](https://badgen.net/badge/JIRA/K8SPSMDB-344/green)](https://jira.percona.com/browse/K8SPSMDB-344)
=> K8SPSMDB-344: CfgRS status clean

e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos-oc.yml, e2e-tests/rs-shard-migration/run
- Monitoring compare file fix (PMM server app version update)
- Check additional sharding parameter (https://github.com/percona/percona-server-mongodb-operator/pull/497#discussion_r539967937)
=> K8SPSMDB-341 Minor tests fixes

source/RN/Kubernetes-Operator-for-PSMONGODB-RN1.4.0.rst, source/RN/Kubernetes-Operator-for-PSMONGODB-RN1.5.0.rst, source/System-Requirements.rst, source/TLS.rst, source/api.rst, source/architecture.rst, source/backups.rst, source/conf.py, source/custom-registry.rst, source/eks.rst, source/expose.rst, source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/monitoring.rst, source/openshift.rst, source/operator.rst, source/sharding.rst, source/update.rst
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1)
=> Rn 1.6 follow up fix

e2e-tests/upgrade/compare/statefulset_upgrade-rs0-oc.yml, e2e-tests/upgrade/compare/statefulset_upgrade-rs0.yml, e2e-tests/upgrade/run
=> K8SPSMDB-341 - fix upgrade test after 1.6.0 release

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-351](https://badgen.net/badge/JIRA/K8SPSMDB-351/green)](https://jira.percona.com/browse/K8SPSMDB-351) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-351: Remove added_as_shard key when sharding not enabled

e2e-tests/monitoring-2-0/run
[![CLOUD-605](https://badgen.net/badge/JIRA/CLOUD-605/green)](https://jira.percona.com/browse/CLOUD-605) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Victoria metrics persistance added
=> CLOUD-605 PMM server chart version upgrade

pkg/psmdb/statefulset.go
[![K8SPSMDB-346](https://badgen.net/badge/JIRA/K8SPSMDB-346/green)](https://jira.percona.com/browse/K8SPSMDB-346) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-346: Do not put custom labels to selector

deploy/cr.yaml, pkg/controller/perconaservermongodb/finalizers.go, pkg/controller/perconaservermongodb/getters.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-260](https://badgen.net/badge/JIRA/K8SPSMDB-260/green)](https://jira.percona.com/browse/K8SPSMDB-260) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-260: Add finalizer for PVC

source/helm.rst
[![CLOUD-604](https://badgen.net/badge/JIRA/CLOUD-604/green)](https://jira.percona.com/browse/CLOUD-604) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-604 remove helm2 from docs

pkg/controller/perconaservermongodb/vs.go
[![K8SPSMDB-366](https://badgen.net/badge/JIRA/K8SPSMDB-366/green)](https://jira.percona.com/browse/K8SPSMDB-366) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-366 fix getting of pmm image path

deploy/cr.yaml, deploy/rbac.yaml, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, pkg/controller/perconaservermongodbbackup/backup.go, pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go, pkg/psmdb/backup/job.go
[![K8SPSMDB-335](https://badgen.net/badge/JIRA/K8SPSMDB-335/green)](https://jira.percona.com/browse/K8SPSMDB-335) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This PR adds 'keep' field for backup task.
Based on that field operator will remove backup objects AND sent `deleteBackup` request to PBM to delete real backup data.
=> K8SPSMDB-335: Backup retention based on 'Keep' parameter

source/conf.py, source/custom-registry.rst, source/debug.rst, source/eks.rst, source/faq.rst, source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst, source/operator.rst, source/sharding.rst, source/update.rst, source/users.rst
[![K8SPSMDB-349](https://badgen.net/badge/JIRA/K8SPSMDB-349/green)](https://jira.percona.com/browse/K8SPSMDB-349) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-349 Use MongoDB 4.4 version everywhere in docs

pkg/psmdb/mongos.go
[![K8SPSMDB-382](https://badgen.net/badge/JIRA/K8SPSMDB-382/green)](https://jira.percona.com/browse/K8SPSMDB-382) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-382 fix "permissions on mongodb-key are too open"

source/arbiter.rst
[![K8SPSMDB-49](https://badgen.net/badge/JIRA/K8SPSMDB-49/green)](https://jira.percona.com/browse/K8SPSMDB-49) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-49 add example for arbiter

source/minikube.rst
[![K8SPSMDB-357](https://badgen.net/badge/JIRA/K8SPSMDB-357/green)](https://jira.percona.com/browse/K8SPSMDB-357) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> fix formatting

e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos.yml, e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos-oc.yml, e2e-tests/monitoring-2-0/compare/deployment_monitoring-mongos.yml
[![K8SPSMDB-382](https://badgen.net/badge/JIRA/K8SPSMDB-382/green)](https://jira.percona.com/browse/K8SPSMDB-382) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-382 - Add --relaxPermChecks to e2e-tests for mongos

source/operator.rst
[![K8SPXC-640](https://badgen.net/badge/JIRA/K8SPXC-640/green)](https://jira.percona.com/browse/K8SPXC-640) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-640 wrong doc - similar to PXC

pkg/controller/perconaservermongodb/users.go
[![K8SPSMDB-381](https://badgen.net/badge/JIRA/K8SPSMDB-381/green)](https://jira.percona.com/browse/K8SPSMDB-381) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Do not restart mongos when ClusterAdmin was changed

e2e-tests/arbiter/compare/statefulset_arbiter-clusterip-rs0-arbiter-oc.yml, e2e-tests/arbiter/compare/statefulset_arbiter-rs0-arbiter-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-cfg-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/demand-backup/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/init-deploy/compare/statefulset_another-name-rs0-oc.yml, e2e-tests/init-deploy/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-no-limits-rs0-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-increased-oc.yml, e2e-tests/limits/compare/statefulset_no-requests-rs0-oc.yml, e2e-tests/liveness/compare/statefulset_liveness-rs0-changed-oc.yml, e2e-tests/liveness/compare/statefulset_liveness-rs0-oc.yml, e2e-tests/one-pod/compare/statefulset_one-pod-rs0-oc.yml, e2e-tests/scheduled-backup/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_cluster-ip-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0-oc.yml, e2e-tests/smart-update/compare/statefulset_smart-update-rs0-oc.yml, e2e-tests/storage/compare/statefulset_emptydir-rs0-oc.yml, e2e-tests/storage/compare/statefulset_hostpath-rs0-oc.yml, e2e-tests/version-service/compare/statefulset_version-service-exact-rs0-oc.yml, e2e-tests/version-service/compare/statefulset_version-service-latest-rs0-oc.yml, e2e-tests/version-service/compare/statefulset_version-service-recommended-rs0-oc.yml, e2e-tests/version-service/compare/statefulset_version-service-unreachable-rs0-oc.yml
[![K8SPSMDB-383](https://badgen.net/badge/JIRA/K8SPSMDB-383/green)](https://jira.percona.com/browse/K8SPSMDB-383) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-383 Openshift files fix

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/mongo/models.go
[![K8SPSMDB-392](https://badgen.net/badge/JIRA/K8SPSMDB-392/green)](https://jira.percona.com/browse/K8SPSMDB-392) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-392: Fix decoding of db list

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-391](https://badgen.net/badge/JIRA/K8SPSMDB-391/green)](https://jira.percona.com/browse/K8SPSMDB-391) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-391: Remove RS from status after shard was removed

source/update.rst
[![K8SPSMDB-395](https://badgen.net/badge/JIRA/K8SPSMDB-395/green)](https://jira.percona.com/browse/K8SPSMDB-395) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-395 fix bug in the patch command in update doc

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-390](https://badgen.net/badge/JIRA/K8SPSMDB-390/green)](https://jira.percona.com/browse/K8SPSMDB-390) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-390: Fix RS initialization

source/TLS.rst
[![K8SPXC-655](https://badgen.net/badge/JIRA/K8SPXC-655/green)](https://jira.percona.com/browse/K8SPXC-655) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-655 fix typo in TLS doc, PSMDB version

cmd/mongodb-healthcheck/main.go, healthcheck/tools/db/config.go, healthcheck/tools/db/db.go, healthcheck/tools/db/ssl.go, pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-399](https://badgen.net/badge/JIRA/K8SPSMDB-399/green)](https://jira.percona.com/browse/K8SPSMDB-399) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-399: Fix mongos readiness probe when TLS enabled but files do not exist

go.mod, go.sum, pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/backup/pbm.go, vendor/github.com/operator-framework/operator-sdk/version/version.go, vendor/github.com/percona/percona-backup-mongodb/pbm/bsontypes.go, vendor/github.com/percona/percona-backup-mongodb/pbm/cmd.go, vendor/github.com/percona/percona-backup-mongodb/pbm/config.go, vendor/github.com/percona/percona-backup-mongodb/pbm/delete.go, vendor/github.com/percona/percona-backup-mongodb/pbm/lock.go, vendor/github.com/percona/percona-backup-mongodb/pbm/log/log.go, vendor/github.com/percona/percona-backup-mongodb/pbm/node.go, vendor/github.com/percona/percona-backup-mongodb/pbm/pbm.go, vendor/github.com/percona/percona-backup-mongodb/pbm/pitr.go, vendor/github.com/percona/percona-backup-mongodb/pbm/restore.go, vendor/github.com/percona/percona-backup-mongodb/pbm/rsync.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/blackhole/blackhole.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/fs/fs.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/s3/s3.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/storage.go, vendor/github.com/percona/percona-backup-mongodb/version/version.go, vendor/modules.txt
[![K8SPSMDB-386](https://badgen.net/badge/JIRA/K8SPSMDB-386/green)](https://jira.percona.com/browse/K8SPSMDB-386) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-386
update pbm and operator-sdk packages
=> K8SPSMDB-386 feature: update pbm and operator-sdk packages

CONTRIBUTING.md, code-of-conduct.md
[![K8SPSMDB-372](https://badgen.net/badge/JIRA/K8SPSMDB-372/green)](https://jira.percona.com/browse/K8SPSMDB-372) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-372 add contributing guide

pkg/controller/perconaservermongodbbackup/backup.go, pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
[![K8SPSMDB-403](https://badgen.net/badge/JIRA/K8SPSMDB-403/green)](https://jira.percona.com/browse/K8SPSMDB-403) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-403
=> K8SPSMDB-403 fix: some typos in comments/messages

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-401](https://badgen.net/badge/JIRA/K8SPSMDB-401/green)](https://jira.percona.com/browse/K8SPSMDB-401) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-401: Fix status with arbiter in RS

pkg/psmdb/mongos.go
[![K8SPSMDB-406](https://badgen.net/badge/JIRA/K8SPSMDB-406/green)](https://jira.percona.com/browse/K8SPSMDB-406) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-406 add relaxPermChecks option only from 1.7.0

e2e-tests/functions, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, pkg/controller/perconaservermongodb/balancer.go, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/smart.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/mongos.go
[![K8SPSMDB-404](https://badgen.net/badge/JIRA/K8SPSMDB-404/green)](https://jira.percona.com/browse/K8SPSMDB-404) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-404: Add logic for syncing restore with mongos

e2e-tests/upgrade-sharded/run
[![K8SPSMDB-406](https://badgen.net/badge/JIRA/K8SPSMDB-406/green)](https://jira.percona.com/browse/K8SPSMDB-406) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-406 Checking stable configuration during operator upgrade

source/expose.rst
[![K8SPSMDB-375](https://badgen.net/badge/JIRA/K8SPSMDB-375/green)](https://jira.percona.com/browse/K8SPSMDB-375) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> minor label fix

e2e-tests/data-sharded/run, e2e-tests/demand-backup-sharded/run, e2e-tests/demand-backup/run, e2e-tests/functions, e2e-tests/scheduled-backup/conf/some-name-rs0-2.yml, e2e-tests/scheduled-backup/run, e2e-tests/users/conf/backup-minio.yml, e2e-tests/users/run
[![K8SPSMDB-372](https://badgen.net/badge/JIRA/K8SPSMDB-372/green)](https://jira.percona.com/browse/K8SPSMDB-372) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-372 add possibility of skipping backups to aws/gcp S3 storage

source/users.rst
[![K8SPSMDB-362](https://badgen.net/badge/JIRA/K8SPSMDB-362/green)](https://jira.percona.com/browse/K8SPSMDB-362) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-362  mention specifics for cluster monitor user password change

source/sharding.rst
[![K8SPSMDB-375](https://badgen.net/badge/JIRA/K8SPSMDB-375/green)](https://jira.percona.com/browse/K8SPSMDB-375) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-375 document mupltiple shards support

pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-409](https://badgen.net/badge/JIRA/K8SPSMDB-409/green)](https://jira.percona.com/browse/K8SPSMDB-409) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-409: Remove 'test' db from list of system DBs

go.mod, go.sum, healthcheck/health.go, healthcheck/readiness_test.go, healthcheck/tools/db/config_test.go, healthcheck/tools/db/db.go, healthcheck/tools/db/db_test.go, healthcheck/tools/db/ssl_test.go, pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-408](https://badgen.net/badge/JIRA/K8SPSMDB-408/green)](https://jira.percona.com/browse/K8SPSMDB-408) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-408, K8SPSMDB-401: Fix arbiter liveness probe

pkg/controller/perconaservermongodb/getters.go, pkg/controller/perconaservermongodb/smart.go
[![K8SPSMDB-415](https://badgen.net/badge/JIRA/K8SPSMDB-415/green)](https://jira.percona.com/browse/K8SPSMDB-415) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-415: Fix smart update for arbiter

e2e-tests/demand-backup-sharded/compare/deployment_some-name-mongos-4-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-cfg-4-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-cfg-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs0-4-oc.yml, e2e-tests/init-deploy/compare/statefulset_another-name-rs0-4-oc.yml, e2e-tests/init-deploy/compare/statefulset_another-name-rs0-oc.yml
[![K8SPSMDB-383](https://badgen.net/badge/JIRA/K8SPSMDB-383/green)](https://jira.percona.com/browse/K8SPSMDB-383) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-383 Fix for openshift 3.11

deploy/cr.yaml
Several commented options had wrong alignment in the arbiter section
=> Fix arbiter options misalignment

source/faq.rst
[![K8SPSMDB-367](https://badgen.net/badge/JIRA/K8SPSMDB-367/green)](https://jira.percona.com/browse/K8SPSMDB-367) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-367 document how to do initial sync of a pod

e2e-tests/functions
[![K8SPXC-622](https://badgen.net/badge/JIRA/K8SPXC-622/green)](https://jira.percona.com/browse/K8SPXC-622) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-372 set 'SKIP_BACKUPS_TO_AWS_GCP=1' by default

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/version.go, pkg/controller/perconaservermongodb/vs.go
[![K8SPSMDB-416](https://badgen.net/badge/JIRA/K8SPSMDB-416/green)](https://jira.percona.com/browse/K8SPSMDB-416) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-416: Fix version request logic

3q, source/operator.rst, source/scaling.rst
[![K8SPSMDB-355](https://badgen.net/badge/JIRA/K8SPSMDB-355/green)](https://jira.percona.com/browse/K8SPSMDB-355) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-355 update doc how to scale cluster

.github/linters/go.mod, .github/workflows/reviewdog.yml, .reviewdog.yml, build/Dockerfile
[![CLOUD-616](https://badgen.net/badge/JIRA/CLOUD-616/green)](https://jira.percona.com/browse/CLOUD-616) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/CLOUD-616
check code automatically with the following linters:
* golangci-lint
* go-consistent
* gofmt
* shfmt
* shellcheck
* misspell
* alex (insensitive, inconsiderate wording)
=> CLOUD-616 run linters automatically on each PR

source/System-Requirements.rst, source/faq.rst, source/operator.rst, source/scaling.rst, source/sharding.rst
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> label fixes

source/kubernetes.rst, source/operator.rst, source/scaling.rst
[![RN-1](https://badgen.net/badge/JIRA/RN-1/green)](https://jira.percona.com/browse/RN-1) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> minor labels fix

README.md
[![K8SPSMDB-417](https://badgen.net/badge/JIRA/K8SPSMDB-417/green)](https://jira.percona.com/browse/K8SPSMDB-417) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-417-follow-up fix

README.md
[![K8SPSMDB-417](https://badgen.net/badge/JIRA/K8SPSMDB-417/green)](https://jira.percona.com/browse/K8SPSMDB-417) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-417 add license badge

e2e-tests/functions, e2e-tests/smart-update/compare/statefulset_smart-update-rs0-arbiter.yml, e2e-tests/smart-update/compare/statefulset_smart-update-rs0-oc.yml, e2e-tests/smart-update/conf/smart-update-rs0.yml, e2e-tests/smart-update/run
[![K8SPSMDB-415](https://badgen.net/badge/JIRA/K8SPSMDB-415/green)](https://jira.percona.com/browse/K8SPSMDB-415) [&#10088;?&#10089;](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-415 - Include arbiter pod into smart-update test

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-331](https://badgen.net/badge/JIRA/K8SPSMDB-331/green)](https://jira.percona.com/browse/K8SPSMDB-331) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-331
Restricted running less than 2 pods of mongos unless allowUnsafeConfigurations flag is set to true by changing mongos size to 2 if it's lower than that.
=> K8SPSMDB-331 feature: Restrict running min pods of mongos

pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/controller/perconaservermongodb/backup.go
[![K8SPSMDB-386](https://badgen.net/badge/JIRA/K8SPSMDB-386/green)](https://jira.percona.com/browse/K8SPSMDB-386) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-386
=> K8SPSMDB-386 feature: add PITR controls validation

pkg/apis/psmdb/v1/perconaservermongodbrestore_types.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/backup/pbm.go
=> K8SPSMDB-387 feature: add restore to the latest chunk

pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/backup/pbm.go
=> K8SPSMDB-387 feature: add no oplogs check for PITRestore

deploy/backup/backup.yaml
[![K8SPSMDB-431](https://badgen.net/badge/JIRA/K8SPSMDB-431/green)](https://jira.percona.com/browse/K8SPSMDB-431) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Add finalizer to on-demand backup spec

pkg/psmdb/init.go, pkg/psmdb/mongos.go
[![K8SPSMDB-436](https://badgen.net/badge/JIRA/K8SPSMDB-436/green)](https://jira.percona.com/browse/K8SPSMDB-436) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-436 Use cr ImagePullPolicy on init containers

pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/backup/pbm.go
=> K8SPSMDB-387: fix pitrestore to latest in sharded cluster

pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-428](https://badgen.net/badge/JIRA/K8SPSMDB-428/green)](https://jira.percona.com/browse/K8SPSMDB-428) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-428 Fix mutating CR on status update

Jenkinsfile, e2e-tests/pitr/compare/find-2nd.json, e2e-tests/pitr/compare/find.json, e2e-tests/pitr/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/pitr/compare/statefulset_some-name-rs0.yml, e2e-tests/pitr/conf/backup-minio.yml, e2e-tests/pitr/conf/restore.yml, e2e-tests/pitr/conf/some-name-rs0.yml, e2e-tests/pitr/run, e2e-tests/run
=> K8SPSMDB-387: add e2e test for pitr

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-437](https://badgen.net/badge/JIRA/K8SPSMDB-437/green)](https://jira.percona.com/browse/K8SPSMDB-437) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-437: Ensure PVC's have same labels with replicasets

e2e-tests/init-deploy/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/init-deploy/compare/statefulset_some-name-rs0.yml
Reverts percona/percona-server-mongodb-operator#644
=> Revert "Fix for release 1.8.0"

ADOPTERS.md, adopters/example/README.md, adopters/users/spron-in/README.md
[![K8SPSMDB-447](https://badgen.net/badge/JIRA/K8SPSMDB-447/green)](https://jira.percona.com/browse/K8SPSMDB-447) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-447 init adopters commit

e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs0-4-oc.yml, e2e-tests/init-deploy/compare/statefulset_another-name-rs0-4-oc.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0-oc.yml
=> K8SPSMDB-442 - Update diffs for OpenShift

deploy/cr.yaml
=> K8SPSMDB-442 - add pitr option in default cr.yaml

deploy/cr.yaml
=> K8SPSMDB-442 - change apply option in default cr.yaml

e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs1-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs2-oc.yml, e2e-tests/demand-backup-sharded/run, e2e-tests/functions, e2e-tests/init-deploy/run
[![K8SPSMDB-454](https://badgen.net/badge/JIRA/K8SPSMDB-454/green)](https://jira.percona.com/browse/K8SPSMDB-454) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-454 - Fix runtimeclass for demand-backup-sharded and init-deploy tests

e2e-tests/rs-shard-migration/run, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/run
=> K8SPSMDB-442 - fix stuck upgrade tests on 1.20

source/operator.rst
[![K8SPSMDB-348](https://badgen.net/badge/JIRA/K8SPSMDB-348/green)](https://jira.percona.com/browse/K8SPSMDB-348) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-348 update unsafe flag description

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/version.go, pkg/controller/perconaservermongodb/version_test.go
[![K8SPSMDB-455](https://badgen.net/badge/JIRA/K8SPSMDB-455/green)](https://jira.percona.com/browse/K8SPSMDB-455) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-455: Fix downgrade

source/operator.rst, source/update.rst
[![K8SPSMDB-448](https://badgen.net/badge/JIRA/K8SPSMDB-448/green)](https://jira.percona.com/browse/K8SPSMDB-448) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-448 document major version upgrades

Jenkinsfile, e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-4-oc.yml, e2e-tests/pitr-sharded/compare/deployment_some-name-mongos-oc.yml, e2e-tests/pitr-sharded/compare/deployment_some-name-mongos.yml, e2e-tests/pitr-sharded/compare/find-2nd.json, e2e-tests/pitr-sharded/compare/find-3rd.json, e2e-tests/pitr-sharded/compare/find.json, e2e-tests/pitr-sharded/compare/statefulset_some-name-cfg-4-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-cfg-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-cfg.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs0-4-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs0.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs1-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs1.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs2-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs2.yml, e2e-tests/pitr-sharded/conf/backup-minio.yml, e2e-tests/pitr-sharded/conf/restore.yml, e2e-tests/pitr-sharded/conf/some-name-rs0.yml, e2e-tests/pitr-sharded/run, e2e-tests/run
=> K8SPSMDB-387: add e2e test for pitr (in sharded cluster)

pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
[![K8SPSMDB-462](https://badgen.net/badge/JIRA/K8SPSMDB-462/green)](https://jira.percona.com/browse/K8SPSMDB-462) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-462: Empty backup finalizer list if backup isn't successful

pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-398](https://badgen.net/badge/JIRA/K8SPSMDB-398/green)](https://jira.percona.com/browse/K8SPSMDB-398) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-398: Fix wrong cluster status on rs remove

deploy/crd.yaml, e2e-tests/functions, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-190.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-190-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-190.yml, e2e-tests/upgrade-consistency/run, e2e-tests/version-service/conf/crd.yaml, version/version.go
=> K8SPSMDB-442 - Post 1.8.0 release update

Jenkinsfile
[![K8SPSMDB-468](https://badgen.net/badge/JIRA/K8SPSMDB-468/green)](https://jira.percona.com/browse/K8SPSMDB-468) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-468 fix cluster deletion

docs/architecture/README.md, docs/architecture/decisions/0001-record-architecture-decisions.md, docs/architecture/decisions/index.md, docs/architecture/decisions/template.md
[![CLOUD-622](https://badgen.net/badge/JIRA/CLOUD-622/green)](https://jira.percona.com/browse/CLOUD-622) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-622 add examples of architecture decision records

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/const.go, pkg/psmdb/mongos.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-443](https://badgen.net/badge/JIRA/K8SPSMDB-443/green)](https://jira.percona.com/browse/K8SPSMDB-443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-443
=> K8SPSMDB-443: add mongos custom configuration via ConfigMaps

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/const.go, pkg/psmdb/mongos.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-444](https://badgen.net/badge/JIRA/K8SPSMDB-444/green)](https://jira.percona.com/browse/K8SPSMDB-444) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-444
=> K8SPSMDB-444: allow storing custom configuration in Secrets

deploy/cr.yaml
[![K8SPSMDB-443](https://badgen.net/badge/JIRA/K8SPSMDB-443/green)](https://jira.percona.com/browse/K8SPSMDB-443) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-443
=> K8SPSMDB-443: add examples to deploy/cr.yaml

pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/status.go, pkg/controller/perconaservermongodb/status_test.go
[![K8SPSMDB-181](https://badgen.net/badge/JIRA/K8SPSMDB-181/green)](https://jira.percona.com/browse/K8SPSMDB-181) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-181: Reduce complexity of the status handling

pkg/controller/perconaservermongodb/external_service.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-423](https://badgen.net/badge/JIRA/K8SPSMDB-423/green)](https://jira.percona.com/browse/K8SPSMDB-423) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-423: Retain replset load balancers on pause

e2e-tests/operator-self-healing/run, e2e-tests/scaling/run
[![K8SPSMDB-477](https://badgen.net/badge/JIRA/K8SPSMDB-477/green)](https://jira.percona.com/browse/K8SPSMDB-477) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-477: Fix wrong crVersion in scaling tests

pkg/psmdb/mongos.go
[![K8SPSMDB-435](https://badgen.net/badge/JIRA/K8SPSMDB-435/green)](https://jira.percona.com/browse/K8SPSMDB-435) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-435: Pass custom labels to mongos

pkg/controller/perconaservermongodb/finalizers.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-421](https://badgen.net/badge/JIRA/K8SPSMDB-421/green)](https://jira.percona.com/browse/K8SPSMDB-421) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Also run finalizers at the end of the reconciliation to not recreate
objects that are deleted by finalizers.
=> K8SPSMDB-421: Delete secrets if PVC finalizer enabled

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-451](https://badgen.net/badge/JIRA/K8SPSMDB-451/green)](https://jira.percona.com/browse/K8SPSMDB-451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-451: Don't use error status for components

source/operator.rst
[![K8SPSMDB-459](https://badgen.net/badge/JIRA/K8SPSMDB-459/green)](https://jira.percona.com/browse/K8SPSMDB-459) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-459 mention cluster name limitations

source/arbiter.rst, source/operator.rst
[![K8SPSMDB-440](https://badgen.net/badge/JIRA/K8SPSMDB-440/green)](https://jira.percona.com/browse/K8SPSMDB-440) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-440 improve arbiter related details in docs

pkg/apis/psmdb/v1/psmdb_types.go
[![K8SPSMDB-453](https://badgen.net/badge/JIRA/K8SPSMDB-453/green)](https://jira.percona.com/browse/K8SPSMDB-453) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-453: Show cluster progress fields even if eq to `0`

pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go
[![K8SPSMDB-489](https://badgen.net/badge/JIRA/K8SPSMDB-489/green)](https://jira.percona.com/browse/K8SPSMDB-489) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-489: Don't update status of ready backups

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-451](https://badgen.net/badge/JIRA/K8SPSMDB-451/green)](https://jira.percona.com/browse/K8SPSMDB-451) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-451: Take mongos into consideration for CR status

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-487](https://badgen.net/badge/JIRA/K8SPSMDB-487/green)](https://jira.percona.com/browse/K8SPSMDB-487) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-487: Make sure ready count is not bigger than total size

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/mongos.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-492](https://badgen.net/badge/JIRA/K8SPSMDB-492/green)](https://jira.percona.com/browse/K8SPSMDB-492) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-492
=> K8SPSMDB-492: add config hash annotations to pod templates

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-487](https://badgen.net/badge/JIRA/K8SPSMDB-487/green)](https://jira.percona.com/browse/K8SPSMDB-487) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-487: Fix replset and mongos ready count on downscale

pkg/controller/perconaservermongodb/smart.go
[![K8SPSMDB-494](https://badgen.net/badge/JIRA/K8SPSMDB-494/green)](https://jira.percona.com/browse/K8SPSMDB-494) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
We update the status at the end of every reconciliation loop. If something triggers a smart update, the operator waits until all pods are updated and then updates the status. Thus, during smart update, status becomes stale and usually remains ready.
To track smart update progress, we periodically (every second) check if pod is started. If we update the status every second during smart update, we can keep status fresh. The …
=> K8SPSMDB-494: Fix stale status during smart update

docs/architecture/decisions/0002-allow-downscaling-in-a-safe-manner.md, docs/architecture/decisions/index.md, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-486](https://badgen.net/badge/JIRA/K8SPSMDB-486/green)](https://jira.percona.com/browse/K8SPSMDB-486) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-486: Fix cluster crash on losing majority due to downscale

e2e-tests/one-pod/compare/statefulset_one-pod-rs0-secret-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs1-4-oc.yml, e2e-tests/pitr-sharded/compare/statefulset_some-name-rs2-4-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-190-oc.yml
=> K8SPSMDB-488 - Fix one-pod, pitr-sharded and upgrade-consistency on OpenShift

e2e-tests/users/run
=> K8SPSMDB-488 - Fix users test for OpenShift

pkg/controller/perconaservermongodb/status.go
[![K8SPSMDB-497](https://badgen.net/badge/JIRA/K8SPSMDB-497/green)](https://jira.percona.com/browse/K8SPSMDB-497) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-497: Take mongos into consideration for paused status

deploy/bundle.yaml, deploy/crd.yaml, deploy/rbac.yaml
[![K8SPSMDB-502](https://badgen.net/badge/JIRA/K8SPSMDB-502/green)](https://jira.percona.com/browse/K8SPSMDB-502) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-502 Replace deprecated Kubernetes APIs

deploy/backup/restore.yaml
=> K8SPSMDB-488 - Add backupSource example into restore.yaml

source/System-Requirements.rst, source/architecture.rst, source/faq.rst, source/update.rst
[![K8SPSMDB-482](https://badgen.net/badge/JIRA/K8SPSMDB-482/green)](https://jira.percona.com/browse/K8SPSMDB-482) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-482 remove MongoDB 3.6 mentions from docs other than Release Notes

source/operator.rst
[![K8SPSMDB-172](https://badgen.net/badge/JIRA/K8SPSMDB-172/green)](https://jira.percona.com/browse/K8SPSMDB-172) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-172 configmaps for MongoDB

source/index.rst, source/options.rst
[![K8SPSMDB-173](https://badgen.net/badge/JIRA/K8SPSMDB-173/green)](https://jira.percona.com/browse/K8SPSMDB-173) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-173 describe storing mongodb options in configmaps and secretes

deploy/backup/restore.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/operator.yaml
=> K8SPSMDB-488 - Release 1.9.0

deploy/bundle.yaml, deploy/crd.yaml, e2e-tests/functions, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-1100.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1100-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1100.yml, e2e-tests/upgrade-consistency/run, e2e-tests/version-service/conf/crd.yaml, version/version.go
=> K8SPSMDB-488 - Preparation after 1.9.0 release

source/RN/Kubernetes-Operator-for-PSMONGODB-RN1.9.0.rst, source/RN/index.rst, source/kubernetes.rst, source/options.rst
=> K8SPSMDB-488 rn 1.9.0 fixes

e2e-tests/functions
[![CLOUD-625](https://badgen.net/badge/JIRA/CLOUD-625/green)](https://jira.percona.com/browse/CLOUD-625) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-625 - Fix cleanup of chaos mesh from previous test

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-511](https://badgen.net/badge/JIRA/K8SPSMDB-511/green)](https://jira.percona.com/browse/K8SPSMDB-511) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-511: Fix addShard if replset exposed

e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml, e2e-tests/scheduled-backup/compare/statefulset_some-name-rs0-oc.yml, e2e-tests/scheduled-backup/compare/statefulset_some-name-rs0.yml, e2e-tests/scheduled-backup/conf/some-name-rs0-2.yml, e2e-tests/scheduled-backup/conf/some-name-rs0.yml, pkg/controller/perconaservermongodb/backup.go, pkg/psmdb/backup/job.go
[![K8SPSMDB-514](https://badgen.net/badge/JIRA/K8SPSMDB-514/green)](https://jira.percona.com/browse/K8SPSMDB-514) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-514 fix cronJob resources

source/openshift.rst
[![CLOUD-635](https://badgen.net/badge/JIRA/CLOUD-635/green)](https://jira.percona.com/browse/CLOUD-635) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-635 - mention openshift certification

pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-490](https://badgen.net/badge/JIRA/K8SPSMDB-490/green)](https://jira.percona.com/browse/K8SPSMDB-490) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-490: Add validation for CR name length

pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/psmdb/const.go, pkg/psmdb/mongos.go, pkg/psmdb/statefulset.go
[![K8SPSMDB-496](https://badgen.net/badge/JIRA/K8SPSMDB-496/green)](https://jira.percona.com/browse/K8SPSMDB-496) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-496
=> K8SPSMDB-496: fix custom config hash annotations

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-536](https://badgen.net/badge/JIRA/K8SPSMDB-536/green)](https://jira.percona.com/browse/K8SPSMDB-536) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-536
=> K8SPSMDB-536 report Init status if some member is down

source/System-Requirements.rst, source/assets/code/kubectl-get-minimal-response.txt, source/minikube.rst
[![CLOUD-637](https://badgen.net/badge/JIRA/CLOUD-637/green)](https://jira.percona.com/browse/CLOUD-637) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
related to https://github.com/percona/percona-server-mongodb-operator/pull/736
=> CLOUD-637 introduce cr minimal

pkg/psmdb/backup/pbm.go
[![K8SPSMDB-584](https://badgen.net/badge/JIRA/K8SPSMDB-584/green)](https://jira.percona.com/browse/K8SPSMDB-584) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-584 give PBM time to init the storage

Jenkinsfile, deploy/cr.yaml, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, pkg/controller/perconaservermongodbbackup/backup.go, pkg/controller/perconaservermongodbbackup/perconaservermongodbbackup_controller.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
[![K8SPSMDB-388](https://badgen.net/badge/JIRA/K8SPSMDB-388/green)](https://jira.percona.com/browse/K8SPSMDB-388) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-388: control how often oplogs are uploaded to S3

Jenkinsfile, pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-558](https://badgen.net/badge/JIRA/K8SPSMDB-558/green)](https://jira.percona.com/browse/K8SPSMDB-558) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-558: ignore annotations changes

healthcheck/readiness.go
[![K8SPSMDB-534](https://badgen.net/badge/JIRA/K8SPSMDB-534/green)](https://jira.percona.com/browse/K8SPSMDB-534) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-534
=> K8SPSMDB-534: replace command in a mongos readiness probe

pkg/controller/perconaservermongodb/smart.go
[![CLOUD-651](https://badgen.net/badge/JIRA/CLOUD-651/green)](https://jira.percona.com/browse/CLOUD-651) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/CLOUD-651
Fix statefulSet change detection logic
=> CLOUD-651 fix: smartupdate starts after pod deletion

deploy/cr.yaml
[![K8SPSMDB-422](https://badgen.net/badge/JIRA/K8SPSMDB-422/green)](https://jira.percona.com/browse/K8SPSMDB-422) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-422
=> K8SPSMDB-422: add `backup.annotations` to `cr.yaml`

e2e-tests/demand-backup-sharded/conf/some-name-rs0.yml, e2e-tests/demand-backup-sharded/run
[![PBM-725](https://badgen.net/badge/JIRA/PBM-725/green)](https://jira.percona.com/browse/PBM-725) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
This reverts commit 655d9f7f570a87d5486120a2fd3c3360e7219116.
=> Revert "PBM-725 - Temp disable second shard in demand-backup-sharded test (#792)"

pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-568](https://badgen.net/badge/JIRA/K8SPSMDB-568/green)](https://jira.percona.com/browse/K8SPSMDB-568) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [K8SPSMDB-568] allow to upgrade from 4.4 to 5.0

e2e-tests/default-cr/run, e2e-tests/functions, e2e-tests/monitoring-2-0/run, e2e-tests/smart-update/run, e2e-tests/version-service/conf/operator.9.9.9.psmdb-operator.json, e2e-tests/version-service/conf/version-service-exact-rs0.yml, e2e-tests/version-service/conf/version-service-major-rs0.yml, e2e-tests/version-service/conf/version-service-unreachable-rs0.yml, e2e-tests/version-service/run
=> K8SPSMDB-571 - Preparation for 1.11.0 release

pkg/psmdb/container.go
[![K8SPSMDB-603](https://badgen.net/badge/JIRA/K8SPSMDB-603/green)](https://jira.percona.com/browse/K8SPSMDB-603) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [K8SPSMDB-603] use memory resource limits to set --wiredTigerCacheSizeGB

pkg/apis/psmdb/v1/perconaservermongodbrestore_types.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go
[![K8SPSMDB-607](https://badgen.net/badge/JIRA/K8SPSMDB-607/green)](https://jira.percona.com/browse/K8SPSMDB-607) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-607
=> K8SPSMDB-607: Fix operator crashing on restore with `backupSource` and Azure Storage

e2e-tests/default-cr/compare/statefulset_minimal-cluster-cfg.yml, e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg-oc.yml, e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg.yml, e2e-tests/default-cr/run
=> K8SPSMDB-571 Fix default-cr test

e2e-tests/default-cr/compare/statefulset_my-cluster-name-cfg-oc.yml, e2e-tests/default-cr/compare/statefulset_my-cluster-name-rs0-oc.yml, e2e-tests/functions
=> K8SPSMDB-571 - Put timeout to chaos-mesh delete and fix default-cr test

go.mod, pkg/controller/perconaservermongodb/connections.go, pkg/controller/perconaservermongodb/fcv.go, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/users.go, vendor/modules.txt
[![K8SPSMDB-602](https://badgen.net/badge/JIRA/K8SPSMDB-602/green)](https://jira.percona.com/browse/K8SPSMDB-602) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> [K8SPSMDB-602]: setFCV flag causes a thread leak

deploy/cr.yaml, go.mod, go.sum, pkg/apis/psmdb/v1/psmdb_types.go, pkg/psmdb/backup/pbm.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/s3/s3.go, vendor/modules.txt
[![K8SPSMDB-609](https://badgen.net/badge/JIRA/K8SPSMDB-609/green)](https://jira.percona.com/browse/K8SPSMDB-609) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-609
=> [K8SPSMDB-609] Store additional S3 settings into PBM config

e2e-tests/functions
=> K8SPSMDB-571 - Fix service-per-pod test for kubernetes 1.22

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/operator.yaml
=> K8SPSMDB-571 - Update versions for 1.11.0 release

e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg-oc.yml
=> K8SPSMDB-571 - Fix monitoring-2-0 test for OpenShift

deploy/backup/restore.yaml, deploy/cr.yaml, e2e-tests/smart-update/run
=> K8SPSMDB-571 - Fix for smart-update and examples for azure blob storage

source/faq.rst, source/index.rst, source/sidecar.rst
[![K8SPSMDB-520](https://badgen.net/badge/JIRA/K8SPSMDB-520/green)](https://jira.percona.com/browse/K8SPSMDB-520) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-520 docs for sidecar containers

source/operator.rst
[![K8SPSMDB-527](https://badgen.net/badge/JIRA/K8SPSMDB-527/green)](https://jira.percona.com/browse/K8SPSMDB-527) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-527 document tuning options for probes

deploy/cr.yaml
=> K8SPSMDB-571 - Add example for sidecar secret/configmap/pvc

source/backups.rst, source/users.rst
[![K8SPSMDB-543](https://badgen.net/badge/JIRA/K8SPSMDB-543/green)](https://jira.percona.com/browse/K8SPSMDB-543) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-543 backup doc impromements

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/crd.yaml, deploy/operator.yaml, e2e-tests/functions, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-1120.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120.yml, e2e-tests/upgrade-consistency/run, e2e-tests/version-service/conf/crd.yaml, version/version.go
=> K8SPSMDB-571 - Update versions after 1.11.0 release

deploy/cr.yaml, go.mod, go.sum, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/apis/psmdb/v1/psmdb_types.go, pkg/psmdb/backup/pbm.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/s3/s3.go, vendor/modules.txt
[![K8SPSMDB-473](https://badgen.net/badge/JIRA/K8SPSMDB-473/green)](https://jira.percona.com/browse/K8SPSMDB-473) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Add `spec.backup.storages.NAME.s3.insecureSkipTLSVerify` option
=> [K8SPSMDB-473] Allow to skip TLS verification for backup storage

build/Dockerfile
[![K8SPSMDB-618](https://badgen.net/badge/JIRA/K8SPSMDB-618/green)](https://jira.percona.com/browse/K8SPSMDB-618) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-618 use ubi8 for psmdb operator image

source/monitoring.rst
[![K8SPSMDB-620](https://badgen.net/badge/JIRA/K8SPSMDB-620/green)](https://jira.percona.com/browse/K8SPSMDB-620) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-620 remove unneeded step from monitoring doc

e2e-tests/pitr-sharded/conf/some-name-rs0.yml, e2e-tests/pitr-sharded/run, e2e-tests/pitr/conf/some-name-rs0.yml, e2e-tests/pitr/run
[![K8SPSMDB-630](https://badgen.net/badge/JIRA/K8SPSMDB-630/green)](https://jira.percona.com/browse/K8SPSMDB-630) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-630 - PITR decrease waiting time up to 2 min

e2e-tests/README.md, e2e-tests/build
[![CLOUD-674](https://badgen.net/badge/JIRA/CLOUD-674/green)](https://jira.percona.com/browse/CLOUD-674) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-674 add info about build platform

source/index.rst
[![CLOUD-676](https://badgen.net/badge/JIRA/CLOUD-676/green)](https://jira.percona.com/browse/CLOUD-676) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-676 move helm doc to quickstart section

Jenkinsfile, e2e-tests/functions
[![CLOUD-660](https://badgen.net/badge/JIRA/CLOUD-660/green)](https://jira.percona.com/browse/CLOUD-660) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-660 public access to failed tests

e2e-tests/functions, e2e-tests/upgrade-sharded/compare/find-2nd.json, e2e-tests/upgrade-sharded/conf/backup-minio.yml, e2e-tests/upgrade-sharded/conf/restore.yml, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/compare/find-2nd.json, e2e-tests/upgrade/conf/backup-minio.yml, e2e-tests/upgrade/conf/restore.yml, e2e-tests/upgrade/run
[![CLOUD-650](https://badgen.net/badge/JIRA/CLOUD-650/green)](https://jira.percona.com/browse/CLOUD-650) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
monitoring test issue is reported here: https://jira.percona.com/browse/PMM-9563
=> CLOUD-650 - Add backup/restore step to upgrade and upgrade-sharded test

source/custom-registry.rst
[![K8SPSMDB-577](https://badgen.net/badge/JIRA/K8SPSMDB-577/green)](https://jira.percona.com/browse/K8SPSMDB-577) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-577 mention smart updates in custom registry

deploy/cr.yaml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-aws-s3.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-azure-blob-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-azure-blob.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-gcp-cs.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio-oc.yml, e2e-tests/scheduled-backup/compare/cronjob_some-name-backup-every-min-minio.yml, e2e-tests/security-context/compare/cronjob.batch_sec-context-backup-each-hour.yml, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, pkg/psmdb/backup/job.go
[![K8SPSMDB-635](https://badgen.net/badge/JIRA/K8SPSMDB-635/green)](https://jira.percona.com/browse/K8SPSMDB-635) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Add custom labels for backup parameter of PerconaServerMongoDB resource
=> K8SPSMDB-635: Add labels to backup pod template

source/conf.py
[![K8SPSMDB-580](https://badgen.net/badge/JIRA/K8SPSMDB-580/green)](https://jira.percona.com/browse/K8SPSMDB-580) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-580 add anchors to links

ADOPTERS.md, CONTRIBUTING.md, README.md, e2e-tests/README.md
[![CLOUD-677](https://badgen.net/badge/JIRA/CLOUD-677/green)](https://jira.percona.com/browse/CLOUD-677) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-677 Update README.md, other quick fixes

e2e-tests/init-deploy/compare/clusterAdmin-50.json, e2e-tests/smart-update/run
[![K8SPSMDB-562](https://badgen.net/badge/JIRA/K8SPSMDB-562/green)](https://jira.percona.com/browse/K8SPSMDB-562) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-562 - Update tests for PSMDB 5.0

e2e-tests/monitoring-2-0/run
[![CLOUD-685](https://badgen.net/badge/JIRA/CLOUD-685/green)](https://jira.percona.com/browse/CLOUD-685) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-685 fix monitoring test

Jenkinsfile
[![CLOUD-684](https://badgen.net/badge/JIRA/CLOUD-684/green)](https://jira.percona.com/browse/CLOUD-684) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-684 move notifications to private channels

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-654](https://badgen.net/badge/JIRA/K8SPSMDB-654/green)](https://jira.percona.com/browse/K8SPSMDB-654) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-654: Handle mongo member state unknown

go.mod, go.sum, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go, vendor/github.com/percona/percona-backup-mongodb/pbm/bcp_nodes_priority.go, vendor/github.com/percona/percona-backup-mongodb/pbm/config.go, vendor/github.com/percona/percona-backup-mongodb/pbm/pbm.go, vendor/github.com/percona/percona-backup-mongodb/pbm/pitr.go, vendor/github.com/percona/percona-backup-mongodb/pbm/restore.go, vendor/github.com/percona/percona-backup-mongodb/pbm/storage/s3/s3.go, vendor/modules.txt
[![K8SPSMDB-634](https://badgen.net/badge/JIRA/K8SPSMDB-634/green)](https://jira.percona.com/browse/K8SPSMDB-634) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-634
=> [K8SPSMDB-634] Support PBM's PITR compression functionality

Jenkinsfile, e2e-tests/run
[![CLOUD-672](https://badgen.net/badge/JIRA/CLOUD-672/green)](https://jira.percona.com/browse/CLOUD-672) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> turn off cross-site test

e2e-tests/cross-site-sharded/conf/cross-site-sharded-main.yml, e2e-tests/cross-site-sharded/conf/cross-site-sharded-replica.yml, e2e-tests/cross-site-sharded/run, e2e-tests/functions
[![CLOUD-672](https://badgen.net/badge/JIRA/CLOUD-672/green)](https://jira.percona.com/browse/CLOUD-672) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-672 fix service type

source/TLS.rst, source/api.rst, source/backups.rst, source/constraints.rst, source/eks.rst, source/encryption.rst, source/faq.rst, source/gke.rst, source/helm.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst, source/options.rst, source/pause.rst, source/private.rst, source/sharding.rst, source/storage.rst
[![K8SPSMDB-516](https://badgen.net/badge/JIRA/K8SPSMDB-516/green)](https://jira.percona.com/browse/K8SPSMDB-516) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-516 unify code snippets

e2e-tests/demand-backup-sharded/compare/statefulset_some-name-mongos-oc.yml, e2e-tests/demand-backup-sharded/compare/statefulset_some-name-rs0-4-oc.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0-oc.yml
=> K8SPSMDB-631 - Fix service-per-pod and demand-backup-sharded on OpenShift

source/api.rst, source/eks.rst, source/gke.rst, source/kubernetes.rst, source/minikube.rst, source/openshift.rst, source/update.rst
[![K8SPSMDB-540](https://badgen.net/badge/JIRA/K8SPSMDB-540/green)](https://jira.percona.com/browse/K8SPSMDB-540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-516 update installation docs to use server-side apply

Jenkinsfile
[![CLOUD-695](https://badgen.net/badge/JIRA/CLOUD-695/green)](https://jira.percona.com/browse/CLOUD-695) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-695_jenkinsfile_improvements add finally and count test amount

ADOPTERS.md, CONTRIBUTING.md, README.md, e2e-tests/README.md
[![CLOUD-691](https://badgen.net/badge/JIRA/CLOUD-691/green)](https://jira.percona.com/browse/CLOUD-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-691 rename the operator

source/backups.rst
[![K8SPSMDB-228](https://badgen.net/badge/JIRA/K8SPSMDB-228/green)](https://jira.percona.com/browse/K8SPSMDB-228) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-228 rename option in backup.yaml

source/backups.rst
[![K8SPSMDB-628](https://badgen.net/badge/JIRA/K8SPSMDB-628/green)](https://jira.percona.com/browse/K8SPSMDB-628) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-628 mention backups should be specifically enabled in CR

deploy/backup/backup.yaml, deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, e2e-tests/version-service/conf/crd.yaml, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/backup.go
[![K8SPSMDB-672](https://badgen.net/badge/JIRA/K8SPSMDB-672/green)](https://jira.percona.com/browse/K8SPSMDB-672) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-672: Fix compression type variable inconsistency

e2e-tests/functions, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/run
[![K8SPSMDB-681](https://badgen.net/badge/JIRA/K8SPSMDB-681/green)](https://jira.percona.com/browse/K8SPSMDB-681) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
- Add cert-manager to upgrade-sharded test
- Fix wait_deployment to check if deployment exists
Depends on: https://github.com/percona/percona-server-mongodb-operator/pull/935
=> K8SPSMDB-681 - Add cert-manager to upgrade-sharded test

source/TLS.rst, source/api.rst, source/arbiter.rst, source/backups.rst, source/conf.py, source/constraints.rst, source/custom-registry.rst, source/eks.rst, source/faq.rst, source/gke.rst, source/helm.rst, source/index.rst, source/minikube.rst, source/openshift.rst, source/operator.rst, source/private.rst, source/sharding.rst, source/storage.rst, source/update.rst
[![CLOUD-691](https://badgen.net/badge/JIRA/CLOUD-691/green)](https://jira.percona.com/browse/CLOUD-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-691 rename the operator in docs

deploy/cr.yaml
=> K8SPSMDB-631 release 1.12.0 add options to cr

e2e-tests/functions
=> K8SPSMDB-631 - Update chaos-mesh version for tests

e2e-tests/demand-backup-eks-credentials/conf/some-name-rs0.yml
=> K8 spsmdb 631 release 1.12.0 fix tests

e2e-tests/smart-update/run
=> K8SPSMDB-631 - Fix flaky smart-update test

source/index.rst, source/ldap.rst, source/operator.rst
[![K8SPSMDB-570](https://badgen.net/badge/JIRA/K8SPSMDB-570/green)](https://jira.percona.com/browse/K8SPSMDB-570) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-570 document LDAP support

source/backups.rst, source/operator.rst, source/replication.rst
[![K8SPSMDB-625](https://badgen.net/badge/JIRA/K8SPSMDB-625/green)](https://jira.percona.com/browse/K8SPSMDB-625) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-625 describe MCS support in docs

README.md
[![K8SPSMDB-540](https://badgen.net/badge/JIRA/K8SPSMDB-540/green)](https://jira.percona.com/browse/K8SPSMDB-540) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-540 use server-side apply to manage our large CRD

deploy/bundle.yaml, deploy/crd.yaml, e2e-tests/demand-backup-eks-credentials/conf/some-name-rs0.yml, e2e-tests/init-deploy/compare/clusterAdmin-42.json, e2e-tests/init-deploy/compare/clusterMonitor-42.json, e2e-tests/version-service/conf/crd.yaml, pkg/apis/psmdb/v1/psmdb_types.go
=> K8SPSMDB-631 Release 1.12.0 fix tests v2

source/custom-registry.rst, source/expose.rst, source/faq.rst, source/ldap.rst
[![CLOUD-691](https://badgen.net/badge/JIRA/CLOUD-691/green)](https://jira.percona.com/browse/CLOUD-691) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-691 fix leftovers

deploy/bundle.yaml, deploy/cr.yaml, deploy/crd.yaml, e2e-tests/version-service/conf/crd.yaml, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/apis/psmdb/v1/psmdb_types.go
[![K8SPSMDB-697](https://badgen.net/badge/JIRA/K8SPSMDB-697/green)](https://jira.percona.com/browse/K8SPSMDB-697) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-697 - Remove unused option runUid

Jenkinsfile
[![CLOUD-710](https://badgen.net/badge/JIRA/CLOUD-710/green)](https://jira.percona.com/browse/CLOUD-710) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> Cloud-710 use gke-gcloud-auth-plugin by default

pkg/controller/perconaservermongodb/psmdb_controller.go
[![K8SPSMDB-696](https://badgen.net/badge/JIRA/K8SPSMDB-696/green)](https://jira.percona.com/browse/K8SPSMDB-696) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-696
=> K8SPSMDB-696: can't delete annotations from `spec.replsets.annotations`

deploy/cr.yaml, pkg/psmdb/mongos.go
[![K8SPSMDB-690](https://badgen.net/badge/JIRA/K8SPSMDB-690/green)](https://jira.percona.com/browse/K8SPSMDB-690) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-690 Removed mongos.auditLog subsection from cr

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-676](https://badgen.net/badge/JIRA/K8SPSMDB-676/green)](https://jira.percona.com/browse/K8SPSMDB-676) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-676
Set unmanaged cluster status to `initializing` if there is no primary
=> K8SPSMDB-676: unmanaged cluster stay READY after disaster

deploy/bundle.yaml, deploy/cr.yaml, deploy/operator.yaml, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/apis/psmdb/v1/psmdb_types.go, pkg/controller/perconaservermongodb/psmdb_controller.go, pkg/controller/perconaservermongodb/version.go, pkg/controller/perconaservermongodb/vs.go
[![K8SPSMDB-699](https://badgen.net/badge/JIRA/K8SPSMDB-699/green)](https://jira.percona.com/browse/K8SPSMDB-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-699
=> K8SPSMDB-699: Disable automated upgrade by default

pkg/controller/perconaservermongodb/secrets.go
[![K8SPSMDB-636](https://badgen.net/badge/JIRA/K8SPSMDB-636/green)](https://jira.percona.com/browse/K8SPSMDB-636) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-636
=> K8SPSMDB-636: fill empty credentials in user secrets

e2e-tests/functions
[![K8SPSMDB-699](https://badgen.net/badge/JIRA/K8SPSMDB-699/green)](https://jira.percona.com/browse/K8SPSMDB-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-699: Disable telemetry while running tests

go.mod, go.sum, vendor/golang.org/x/crypto/AUTHORS, vendor/golang.org/x/crypto/CONTRIBUTORS, vendor/golang.org/x/crypto/argon2/argon2.go, vendor/golang.org/x/crypto/ocsp/ocsp.go, vendor/golang.org/x/crypto/pbkdf2/pbkdf2.go, vendor/golang.org/x/crypto/scrypt/scrypt.go, vendor/modules.txt
[![K8SPSMDB-718](https://badgen.net/badge/JIRA/K8SPSMDB-718/green)](https://jira.percona.com/browse/K8SPSMDB-718) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-718 update go modules

CODEOWNERS
[![CLOUD-724](https://badgen.net/badge/JIRA/CLOUD-724/green)](https://jira.percona.com/browse/CLOUD-724) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-724 add code owners

source/backups.rst, source/operator.rst
[![K8SPSMDB-695](https://badgen.net/badge/JIRA/K8SPSMDB-695/green)](https://jira.percona.com/browse/K8SPSMDB-695) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-695 Fix annotations description in the operator options list

source/encryption.rst
[![K8SPSMDB-727](https://badgen.net/badge/JIRA/K8SPSMDB-727/green)](https://jira.percona.com/browse/K8SPSMDB-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-727 fix broken link

source/operator.rst
[![K8SPSMDB-728](https://badgen.net/badge/JIRA/K8SPSMDB-728/green)](https://jira.percona.com/browse/K8SPSMDB-728) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-728 fix options naming and nesting

e2e-tests/functions, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/run
[![K8SPSMDB-287](https://badgen.net/badge/JIRA/K8SPSMDB-287/green)](https://jira.percona.com/browse/K8SPSMDB-287) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-287 fix crd deleting for our tests

.github/CODEOWNERS
[![CLOUD-724](https://badgen.net/badge/JIRA/CLOUD-724/green)](https://jira.percona.com/browse/CLOUD-724) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-724 do not use 'Cloud Team'

.gitignore, cmd/manager/main.go, deploy/bundle.yaml, deploy/operator.yaml, e2e-tests/functions
[![K8SPSMDB-725](https://badgen.net/badge/JIRA/K8SPSMDB-725/green)](https://jira.percona.com/browse/K8SPSMDB-725) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-725
=> K8SPSMDB-725: Support configuring logger via env variables

build/pbm-entry.sh, e2e-tests/service-per-pod/compare/statefulset_cluster-ip-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_cluster-ip-rs0.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0-oc.yml, e2e-tests/service-per-pod/compare/statefulset_local-balancer-rs0.yml, e2e-tests/service-per-pod/conf/cluster-ip-rs0.yml, e2e-tests/service-per-pod/conf/local-balancer-rs0.yml, pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-515](https://badgen.net/badge/JIRA/K8SPSMDB-515/green)](https://jira.percona.com/browse/K8SPSMDB-515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-515 fix changing votes for multiple external nodes, Fix PBM TLS error if replset is exposed

pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/ssl.go, pkg/controller/perconaservermongodb/status.go, pkg/psmdb/mongo/mongo.go
[![K8SPSMDB-666](https://badgen.net/badge/JIRA/K8SPSMDB-666/green)](https://jira.percona.com/browse/K8SPSMDB-666) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-666, K8SPSMDB-515 and logging

pkg/psmdb/container.go
[![K8SPSMDB-515](https://badgen.net/badge/JIRA/K8SPSMDB-515/green)](https://jira.percona.com/browse/K8SPSMDB-515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-515: Don't restart mongod nodes after upgrade

pkg/psmdb/mongos.go
[![K8SPSMDB-515](https://badgen.net/badge/JIRA/K8SPSMDB-515/green)](https://jira.percona.com/browse/K8SPSMDB-515) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-515: Don't restart mongos nodes after upgrade

e2e-tests/functions, pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-699](https://badgen.net/badge/JIRA/K8SPSMDB-699/green)](https://jira.percona.com/browse/K8SPSMDB-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-699: Fix telemetry

e2e-tests/conf/client_with_tls.yml, e2e-tests/data-sharded/conf/some-name.yml, e2e-tests/data-sharded/run, e2e-tests/functions
[![K8SPSMDB-763](https://badgen.net/badge/JIRA/K8SPSMDB-763/green)](https://jira.percona.com/browse/K8SPSMDB-763) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-763 - Convert data-sharded test to use requireTLS mode

e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg-oc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-cfg.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos-oc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-mongos.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0-oc.yml, e2e-tests/monitoring-2-0/compare/statefulset_monitoring-rs0.yml, e2e-tests/monitoring-2-0/conf/monitoring-rs0.yml, e2e-tests/monitoring-2-0/run, pkg/psmdb/pmm.go
[![K8SPSMDB-765](https://badgen.net/badge/JIRA/K8SPSMDB-765/green)](https://jira.percona.com/browse/K8SPSMDB-765) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-765: Use TLS certs in pmm-client

pkg/controller/perconaservermongodb/mgo.go
[![K8SPSMDB-772](https://badgen.net/badge/JIRA/K8SPSMDB-772/green)](https://jira.percona.com/browse/K8SPSMDB-772) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-772: Ignore setDefaultRWConcern not found errors

cmd/manager/main.go
[![K8SPSMDB-773](https://badgen.net/badge/JIRA/K8SPSMDB-773/green)](https://jira.percona.com/browse/K8SPSMDB-773) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-773
=> K8SPSMDB-773: fix `WATCH_NAMESPACE` to support multiple values

deploy/cr-minimal.yaml
[![K8SPSMDB-699](https://badgen.net/badge/JIRA/K8SPSMDB-699/green)](https://jira.percona.com/browse/K8SPSMDB-699) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-699 disable update in cr-minimal

e2e-tests/demand-backup-eks-credentials/compare/statefulset_some-name-rs0.yml
[![K8SPSMDB-764](https://badgen.net/badge/JIRA/K8SPSMDB-764/green)](https://jira.percona.com/browse/K8SPSMDB-764) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-764 Release 1.13.0 fix demand-backup-eks-credentials

pkg/psmdb/pmm.go
[![K8SPSMDB-779](https://badgen.net/badge/JIRA/K8SPSMDB-779/green)](https://jira.percona.com/browse/K8SPSMDB-779) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-779 do not use TLS for PMM in case  unsafe flag is set to true

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, e2e-tests/functions, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-1120.yml, e2e-tests/upgrade-consistency/compare/service_some-name-rs0-1140.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1110-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1110.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1120.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1130-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1130.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1140-oc.yml, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1140.yml, e2e-tests/upgrade-consistency/conf/some-name-rs0.yml, e2e-tests/upgrade-consistency/run, version/version.go
[![K8SPSMDB-764](https://badgen.net/badge/JIRA/K8SPSMDB-764/green)](https://jira.percona.com/browse/K8SPSMDB-764) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-764 post release changes

.github/dependabot.yml, .github/workflows/scan.yml
[![K8SPSMDB-795](https://badgen.net/badge/JIRA/K8SPSMDB-795/green)](https://jira.percona.com/browse/K8SPSMDB-795) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
* start to scan docker image each PR
=> K8SPSMDB-795 add dependabot

e2e-tests/demand-backup-sharded/run, e2e-tests/demand-backup/run, e2e-tests/scheduled-backup/run
[![K8SPXC-1043](https://badgen.net/badge/JIRA/K8SPXC-1043/green)](https://jira.percona.com/browse/K8SPXC-1043) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPXC-1043 move_azure_backups_to_new_subscription

Jenkinsfile
[![CLOUD-705](https://badgen.net/badge/JIRA/CLOUD-705/green)](https://jira.percona.com/browse/CLOUD-705) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
Signed-off-by: Natalia Marukovich <natalia.marukovich@percona.com>
=> CLOUD-705 add labels under cluster creation

.github/workflows/test.yml, pkg/apis/psmdb/v1/psmdb_defaults.go, pkg/apis/psmdb/v1/psmdb_defaults_test.go, pkg/controller/perconaservermongodb/status_test.go, pkg/psmdb/mongo/mongo_test.go
[![K8SPSMDB-825](https://badgen.net/badge/JIRA/K8SPSMDB-825/green)](https://jira.percona.com/browse/K8SPSMDB-825) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-825
=> K8SPSMDB-825: GitHub actions unit test

e2e-tests/functions, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/run
[![K8SPSMDB-828](https://badgen.net/badge/JIRA/K8SPSMDB-828/green)](https://jira.percona.com/browse/K8SPSMDB-828) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> K8SPSMDB-828 fix upgrade tests

pkg/controller/perconaservermongodb/version.go
[![K8SPSMDB-737](https://badgen.net/badge/JIRA/K8SPSMDB-737/green)](https://jira.percona.com/browse/K8SPSMDB-737) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Upgrade major version logic missed upgrading from 5.0 to 6.0.
**Solution:**
Update the logic to support the necessary upgrade.
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-737: Update major upgrade to support upgrade from v5.0 to 6.0.

Jenkinsfile
[![K8SPSMDB-817](https://badgen.net/badge/JIRA/K8SPSMDB-817/green)](https://jira.percona.com/browse/K8SPSMDB-817) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
We need to comment the test since it's broken and I fix it ASAP. 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-817 comment broken test

pkg/controller/perconaservermongodb/users.go, pkg/psmdb/pmm.go
[![K8SPSMDB-866](https://badgen.net/badge/JIRA/K8SPSMDB-866/green)](https://jira.percona.com/browse/K8SPSMDB-866) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
https://jira.percona.com/browse/K8SPSMDB-866
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-866: decrease the amount of pmm secret logs

e2e-tests/rs-shard-migration/run
[![K8SPSMDB-794](https://badgen.net/badge/JIRA/K8SPSMDB-794/green)](https://jira.percona.com/browse/K8SPSMDB-794) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Fix for update rs-shard-migration based on this problem https://jira.percona.com/browse/K8SPSMDB-686
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-769 update rs-shard-migration

e2e-tests/mongod-major-upgrade-sharded/run, e2e-tests/mongod-major-upgrade/run, e2e-tests/upgrade-consistency/compare/statefulset_some-name-rs0-1130-oc.yml, e2e-tests/upgrade-consistency/run, e2e-tests/upgrade-sharded/run, e2e-tests/upgrade/run
---
**Problem:**
Minor file inconsistency occurred
**Cause:**
Lack of attention to openshift platform
**Solution:**
Minor adjustments have been added
**CHECKLIST**
---
**Jira**
**Tests**
=> Fixing compare files for openshift

e2e-tests/functions
---
**Problem:**
Vague if clause results in inefficient attempts for debug enabling 
**Cause:**
Nothing to complain.
**Solution:**
Narrowing down the scope of the possible input cases
**CHECKLIST**
---
**Jira**
**Tests**
=> Enhance debug processing section

Jenkinsfile, deploy/cr.yaml, e2e-tests/functions, e2e-tests/serviceless-external-nodes/run
[![CLOUD-762](https://badgen.net/badge/JIRA/CLOUD-762/green)](https://jira.percona.com/browse/CLOUD-762) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-762 fix debug options and init image

pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/psmdb_controller.go
[![CUSTOM-144](https://badgen.net/badge/JIRA/CUSTOM-144/green)](https://jira.percona.com/browse/CUSTOM-144) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CUSTOM-144 fix backups for custom replSetName

Jenkinsfile
[![CLOUD-793](https://badgen.net/badge/JIRA/CLOUD-793/green)](https://jira.percona.com/browse/CLOUD-793) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
*Different tool versions can cause issues with the tests.*
**Solution:**
*Fix version.*
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-793 - Set fixed version of jq to 1.6

deploy/bundle.yaml, deploy/operator.yaml
[![CUSTOM-149](https://badgen.net/badge/JIRA/CUSTOM-149/green)](https://jira.percona.com/browse/CUSTOM-149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> 1.12.0-custom-149 update cr

Jenkinsfile, e2e-tests/custom-replset-name/compare/find-2nd.json, e2e-tests/custom-replset-name/compare/find.json, e2e-tests/custom-replset-name/conf/backup-aws-s3.yml, e2e-tests/custom-replset-name/conf/backup-gcp-cs.yml, e2e-tests/custom-replset-name/conf/backup-minio.yml, e2e-tests/custom-replset-name/conf/restore.yml, e2e-tests/custom-replset-name/conf/some-name.yml, e2e-tests/custom-replset-name/run, e2e-tests/functions, e2e-tests/init-deploy/compare/backup-44.json, e2e-tests/init-deploy/compare/clusterAdmin-44.json, pkg/psmdb/container.go, pkg/psmdb/mongos.go
[![CUSTOM-149](https://badgen.net/badge/JIRA/CUSTOM-149/green)](https://jira.percona.com/browse/CUSTOM-149) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CUSTOM-149: Fix liveness probe if custom replset name for 1.14.0

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-886 - Update images for 1.15.0 release

.github/dependabot.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> CLOUD-727 set day and time for all packages

e2e-tests/balancer/run, e2e-tests/demand-backup-physical-sharded/run, e2e-tests/expose-sharded/run, e2e-tests/functions, e2e-tests/one-pod/run, e2e-tests/pitr-physical/run, e2e-tests/pitr-sharded/run, e2e-tests/rs-shard-migration/run, e2e-tests/serviceless-external-nodes/run, e2e-tests/split-horizon/run
---
Fixes for tests
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-886 - Fix tests for release

e2e-tests/monitoring-2-0/run
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-886 - Fix monitoring test to work with cluster wide on OpenShift

deploy/cr.yaml
[![K8SPSMDB-929](https://badgen.net/badge/JIRA/K8SPSMDB-929/green)](https://jira.percona.com/browse/K8SPSMDB-929) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-929 - Add example for splitHorizons to cr.yaml

.github/CODEOWNERS
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> Prune codeowners for github

Jenkinsfile
[![CLOUD-814](https://badgen.net/badge/JIRA/CLOUD-814/green)](https://jira.percona.com/browse/CLOUD-814) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
=> CLOUD-814 Move from Kubernetes Platfrom v 1.14 to v 1.25 for all operator test cases

deploy/cr.yaml, pkg/apis/psmdb/v1/psmdb_defaults.go
[![K8SPSMDB-999](https://badgen.net/badge/JIRA/K8SPSMDB-999/green)](https://jira.percona.com/browse/K8SPSMDB-999) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
Deprecate SA for backup
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-999]: https://perconadev.atlassian.net/browse/K8SPSMDB-999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …
=> K8SPSMDB-999 deprecate SA for backup

Makefile
[![CLOUD-833](https://badgen.net/badge/JIRA/CLOUD-833/green)](https://jira.percona.com/browse/CLOUD-833) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-833]: https://perconadev.atlassian.net/browse/CLOUD-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-833 - Minor update for release and after-release Makefile targets

deploy/cr.yaml
[![K8SPSMDB-940](https://badgen.net/badge/JIRA/K8SPSMDB-940/green)](https://jira.percona.com/browse/K8SPSMDB-940) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
add SA example to Cr 
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-940]: https://perconadev.atlassian.net/browse/K8SPSMDB-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3M …
=> [K8SPSMDB-940 add SA to CR

e2e-tests/conf/cmctl.yml, e2e-tests/functions, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-cfg-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-cfg.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-mongos-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-mongos.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-rs0-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-rs0.yml, e2e-tests/tls-issue-cert-manager/conf/some-name.yml, e2e-tests/tls-issue-cert-manager/run, pkg/controller/perconaservermongodb/status_test.go, pkg/psmdb/mongos.go
[![K8SPSMDB-755](https://badgen.net/badge/JIRA/K8SPSMDB-755/green)](https://jira.percona.com/browse/K8SPSMDB-755) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-755]: https://perconadev.atlassian.net/browse/K8SPSMDB-755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> K8SPSMDB-755: Fix tlsMode for mongos

pkg/controller/perconaservermongodbrestore/physical.go
[![K8SPSMDB-1054](https://badgen.net/badge/JIRA/K8SPSMDB-1054/green)](https://jira.percona.com/browse/K8SPSMDB-1054) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
`db.isMaster` output complains about history file and it messes up our checks.
**Solution:**
Ensure we get only `true` or `false` from the output.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1054]: https://perconadev.atlassian.net/browse/K8SPSMDB-1054?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1054: Fix isMaster output during physical restore

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/cfg-arbiter.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/cfg-mongod.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/cfg-nv.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/rs0-arbiter.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/rs0-mongod.yaml, pkg/controller/perconaservermongodb/testdata/reconcile-statefulset/rs0-nv.yaml, version/version.go
[![K8SPSMDB-998](https://badgen.net/badge/JIRA/K8SPSMDB-998/green)](https://jira.percona.com/browse/K8SPSMDB-998) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-998]: https://perconadev.atlassian.net/browse/K8SPSMDB-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …
=> K8SPSMDB-998 new version code preparations in main branch for the next version

Jenkinsfile
[![CLOUD-851](https://badgen.net/badge/JIRA/CLOUD-851/green)](https://jira.percona.com/browse/CLOUD-851) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-851]: https://perconadev.atlassian.net/browse/CLOUD-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-851 updating-jq-and-yq-versions

Jenkinsfile, deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, version/version.go
[![K8SPSMDB-1120](https://badgen.net/badge/JIRA/K8SPSMDB-1120/green)](https://jira.percona.com/browse/K8SPSMDB-1120) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1120]: https://perconadev.atlassian.net/browse/K8SPSMDB-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1120 Update images and versions for 1.16.2 release

go.mod, go.sum, pkg/psmdb/backup/pbm.go
[![K8SPSMDB-1119](https://badgen.net/badge/JIRA/K8SPSMDB-1119/green)](https://jira.percona.com/browse/K8SPSMDB-1119) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Bump PBM to v2.5.0.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1119]: https://perconadev.atlassian.net/browse/K8SPSMDB-1119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1119: Bump PBM to v2.5.0

deploy/bundle.yaml, deploy/cr-minimal.yaml, deploy/cr.yaml, deploy/cw-bundle.yaml, deploy/cw-operator.yaml, deploy/operator.yaml, version/version.go
[![K8SPSMDB-1120](https://badgen.net/badge/JIRA/K8SPSMDB-1120/green)](https://jira.percona.com/browse/K8SPSMDB-1120) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1120]: https://perconadev.atlassian.net/browse/K8SPSMDB-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1120 new version code preparations in main branch for the next release

e2e-tests/functions, e2e-tests/liveness/run, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-cfg-tls-disabled-oc.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-cfg-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-mongos-tls-disabled-oc.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-mongos-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-rs0-tls-disabled-oc.yml, e2e-tests/tls-issue-cert-manager/compare/statefulset_some-name-rs0-tls-disabled.yml, e2e-tests/tls-issue-cert-manager/run
[![K8SPSMDB-1098](https://badgen.net/badge/JIRA/K8SPSMDB-1098/green)](https://jira.percona.com/browse/K8SPSMDB-1098) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1098]: https://perconadev.atlassian.net/browse/K8SPSMDB-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1098 fix tls-issue-cert-manager test

e2e-tests/functions, e2e-tests/monitoring-2-0/run
[![K8SPSMDB-1098](https://badgen.net/badge/JIRA/K8SPSMDB-1098/green)](https://jira.percona.com/browse/K8SPSMDB-1098) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1098]: https://perconadev.atlassian.net/browse/K8SPSMDB-1098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1098 fix monitoring test

pkg/controller/perconaservermongodb/custom_users.go
[![K8SPSMDB-1146](https://badgen.net/badge/JIRA/K8SPSMDB-1146/green)](https://jira.percona.com/browse/K8SPSMDB-1146) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
In the case of user creation, the wrong user secret annotation key was used.
**Solution:**
Set a correct annotation key when creating the user.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1146]: https://perconadev.atlassian.net/browse/K8SPSMDB-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1146: Fix annotation key

.github/workflows/scan.yml, Jenkinsfile
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> K8SPSMDB-1181 use Snyk for container scanning

pkg/controller/perconaservermongodb/finalizers.go
https://perconadev.atlassian.net/browse/K8SPSMDB-1156
---
**Problem:**
*Deleting a cluster with the `percona.com/delete-psmdb-pods-in-order` finalizer is currently not possible if the cluster is in an error state.*
Steps to reproduce:
- deploy default `cr.yaml`
- update `.spec.tls.allowInvalidCertificates` to `false`
- delete the cluster
**Cause:**
*The operator only ignores finalizers when the cluster is in an error state and a finalizer function has failed. However, the `percona.com/delete-psmdb-pods-in-order` finalizer function returns the `errWaitingTermination` error, which is not considered as failure and keeps the finalizer in the cluster until all pods are deleted using `smartUpdate`. In this case, `smartUpdate` fails, causing the cluster deletion process to become …
=> K8SPSMDB-1156: fix deletion of cluster with finalizers

.gitignore
[![K8SPSMDB-1270](https://badgen.net/badge/JIRA/K8SPSMDB-1270/green)](https://jira.percona.com/browse/K8SPSMDB-1270) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1270]: https://perconadev.atlassian.net/browse/K8SPSMDB-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1270 gitignore vendor since it is not used

e2e-tests/balancer/run, pkg/controller/perconaservermongodb/connections.go, pkg/controller/perconaservermongodb/mgo.go, pkg/controller/perconaservermongodb/secrets.go, pkg/controller/perconaservermongodbrestore/perconaservermongodbrestore_controller.go, pkg/psmdb/client.go, pkg/psmdb/connections.go, pkg/psmdb/credentials.go
[![K8SPSMDB-1274](https://badgen.net/badge/JIRA/K8SPSMDB-1274/green)](https://jira.percona.com/browse/K8SPSMDB-1274) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
We need to disable balancer before restores.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1274]: https://perconadev.atlassian.net/browse/K8SPSMDB-1274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1274: Disable balancer before restore

deploy/cr-minimal.yaml, deploy/cr.yaml
[![K8SPSMDB-1283](https://badgen.net/badge/JIRA/K8SPSMDB-1283/green)](https://jira.percona.com/browse/K8SPSMDB-1283) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1283]: https://perconadev.atlassian.net/browse/K8SPSMDB-1283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …
=> K8SPSMDB-1283 - use 7.0.15-9-multi for 1.19.1 as default in cr

e2e-tests/functions
[![K8SPSMDB-1290](https://badgen.net/badge/JIRA/K8SPSMDB-1290/green)](https://jira.percona.com/browse/K8SPSMDB-1290) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
Mistakenly merged into main.
**CHECKLIST**
---
**Jira**
**Tests**
[K8SPSMDB-1290]: https://perconadev.atlassian.net/browse/K8SPSMDB-1290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> K8SPSMDB-1290: Revert custom PBM image in e2e-tests

.github/workflows/labeler.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-727 fix labeler

.github/workflows/labeler.yml
[![CLOUD-727](https://badgen.net/badge/JIRA/CLOUD-727/green)](https://jira.percona.com/browse/CLOUD-727) [<img width="16" alt="Powered by Pull Request Badge" src="https://user-images.githubusercontent.com/1393946/111216524-d2bb8e00-85d4-11eb-821b-ed4c00989c02.png">](https://pullrequestbadge.com/?utm_medium=github&utm_source=percona&utm_campaign=badge_info)
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
[CLOUD-727]: https://perconadev.atlassian.net/browse/CLOUD-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aH …
=> CLOUD-727 fix misprint

e2e-tests/demand-backup-sharded/run, e2e-tests/demand-backup/run, e2e-tests/init-deploy/run, e2e-tests/monitoring-2-0/run, e2e-tests/monitoring-pmm3/run
---
**Problem:**
**Cause:**
**Solution:**
**CHECKLIST**
---
**Jira**
**Tests**
=> Disable pass check in tests
